/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module customerFeedback/src/schemas/schemas @description Defines feedback, follow-up, resolution, handoff, survey, and derived-insight evidence. @layer schema @owner customerFeedback @override Later modules may add governed fields without weakening tenant, ownership, traceability, or correction guarantees. */
module.exports = { customerFeedback: {
    customerFeedback: Object.assign({ super: 'base', model: true, schemaPolicies: ['customerOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, anonymous: { type: 'bool', required: true, default: false }, type: { type: 'string', required: true, enum: ['SUGGESTION', 'COMPLAINT', 'EXPERIENCE', 'SURVEY_RESPONSE', 'PRAISE', 'OTHER'] }, targetType: { type: 'string', required: false }, targetCode: { type: 'string', required: false }, subject: { type: 'string', required: false }, message: { type: 'string', required: false }, structuredAnswers: { type: 'object', required: false }, scores: { type: 'object', required: false }, desiredOutcome: { type: 'string', required: false }, attachmentCodes: { type: 'array', required: false }, preferredChannel: { type: 'string', required: false }, status: { type: 'string', required: true, enum: ['RECEIVED', 'TRIAGED', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_CUSTOMER', 'WAITING_INTERNAL', 'ESCALATED', 'RESOLVED', 'CLOSED', 'REJECTED'] }, category: { type: 'string', required: false }, topic: { type: 'string', required: false }, sentiment: { type: 'string', required: false }, priority: { type: 'string', required: true }, severity: { type: 'string', required: false }, queueCode: { type: 'string', required: false }, assigneeId: { type: 'string', required: false }, dueAt: { type: 'date', required: false }, revision: { type: 'int', required: true, default: 0 }, formDefinitionCode: { type: 'string', required: false }, formVersion: { type: 'int', required: false }, submittedAt: { type: 'date', required: true }, resolvedAt: { type: 'date', required: false }, closedAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true }
    } }),
    customerFeedbackClassification: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true }, feedbackCode: { type: 'string', required: true }, category: { type: 'string', required: false }, topic: { type: 'string', required: false }, sentiment: { type: 'string', required: false }, priority: { type: 'string', required: false }, severity: { type: 'string', required: false }, source: { type: 'string', required: true, enum: ['RULE', 'OPERATOR', 'AI', 'IMPORT'] }, confidence: { type: 'number', required: true }, policyVersion: { type: 'string', required: true }, modelReference: { type: 'string', required: false }, correctedFromCode: { type: 'string', required: false }, correctedBy: { type: 'string', required: false }, evidence: { type: 'object', required: false }, classifiedAt: { type: 'date', required: true }, correlationId: { type: 'string', required: true }
    } }),
    customerFeedbackFollowUp: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true }, feedbackCode: { type: 'string', required: true }, channel: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['OFFERED', 'ATTEMPTED', 'CONTACTED', 'RESOLVED', 'ACCEPTED', 'NO_RESPONSE', 'FAILED', 'SUPPRESSED'] }, attempt: { type: 'int', required: true }, providerReference: { type: 'string', required: false }, outcomeCode: { type: 'string', required: false }, occurredAt: { type: 'date', required: true }, correlationId: { type: 'string', required: true }
    } }),
    customerFeedbackResolution: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true }, feedbackCode: { type: 'string', required: true }, version: { type: 'int', required: true }, outcomeCode: { type: 'string', required: true }, summary: { type: 'string', required: true }, customerConfirmed: { type: 'bool', required: false }, resolvedBy: { type: 'string', required: true }, resolvedAt: { type: 'date', required: true }, status: { type: 'string', required: true, enum: ['PROPOSED', 'RESOLVED', 'ACCEPTED', 'REOPENED', 'SUPERSEDED'] }, correlationId: { type: 'string', required: true }
    } }),
    customerFeedbackHandoff: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true }, feedbackCode: { type: 'string', required: true }, targetModule: { type: 'string', required: true }, targetOperation: { type: 'string', required: true }, externalReference: { type: 'string', required: false }, idempotencyKey: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['PENDING', 'IN_PROGRESS', 'SUCCEEDED', 'RETRY_PENDING', 'FAILED', 'DEAD_LETTER', 'RECONCILED'] }, attemptCount: { type: 'int', required: true, default: 0 }, nextAttemptAt: { type: 'date', required: false }, lastOutcome: { type: 'object', required: false }, correlationId: { type: 'string', required: true }
    } }),
    customerFeedbackInsight: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true }, insightType: { type: 'string', required: true, enum: ['TOPIC', 'CLUSTER', 'TREND', 'ANOMALY', 'SUMMARY'] }, sourceFeedbackCodes: { type: 'array', required: true }, value: { type: 'object', required: true }, confidence: { type: 'number', required: true }, source: { type: 'string', required: true, enum: ['RULE', 'OPERATOR', 'AI'] }, policyVersion: { type: 'string', required: true }, modelReference: { type: 'string', required: false }, promptVersion: { type: 'string', required: false }, status: { type: 'string', required: true, enum: ['PROPOSED', 'ACCEPTED', 'CORRECTED', 'REJECTED', 'STALE', 'DELETED'] }, correctedBy: { type: 'string', required: false }, correctionReason: { type: 'string', required: false }, generatedAt: { type: 'date', required: true }, deletedAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true }
    } })
} };
