/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
'use strict';
const crypto = require('crypto');
/** @module localizationCore/service/DefaultLocalizationReleaseManagementService @description Builds deterministic immutable translation releases from approved values through a replaceable repository port. @layer service @owner localizationCore @override Repository implementations may vary while preserving tenant isolation and immutable checksums. */
module.exports = {
    /** Resolves the configured repository port. */ repository: function () { let name = ((CONFIG.get('localization') || {}).authority || {}).repositoryService; let repository = name && SERVICE[name]; if (!repository) throw this.error('ERR_LOC_00003', 'Localization repository is unavailable'); return repository; },
    /** Produces a stable checksum independent of object insertion order. */ checksum: function (value) { let stable = input => Array.isArray(input) ? input.map(stable) : input && typeof input === 'object' ? Object.fromEntries(Object.keys(input).sort().map(key => [key, stable(input[key])])) : input; return crypto.createHash('sha256').update(JSON.stringify(stable(value))).digest('hex'); },
    /** Builds and stores one immutable release using STANDARD then PROJECT then TENANT override precedence. */ build: async function (request) { this.requireScope(request); let repository = this.repository(); let keys = await repository.listKeys(request); let values = await repository.listApprovedValues(request); let rank = { STANDARD: 1, PROJECT: 2, TENANT: 3 }; let eligible = values.filter(value => value.scopeType === 'STANDARD' || (value.scopeType === 'PROJECT' && value.scopeCode === request.projectCode) || (value.scopeType === 'TENANT' && value.scopeCode === request.tenant)); let byIdentity = new Map(); eligible.sort((left, right) => (rank[left.scopeType] || 0) - (rank[right.scopeType] || 0)).forEach(value => byIdentity.set(value.namespace + ':' + value.key, value)); let entries = {}; keys.forEach(key => { let value = byIdentity.get(key.namespace + ':' + key.key); if (!value && request.locale === request.defaultLocale && ((CONFIG.get('localization') || {}).authority || {}).requireCompleteDefaultLocale !== false) throw this.error('ERR_LOC_00000', 'Default locale is incomplete'); if (value) entries[key.namespace + ':' + key.key] = { message: value.message, parameters: key.parameters, exposure: key.exposure, ownerModule: key.ownerModule, resolvedScope: value.scopeType }; }); let release = { tenant: request.tenant, scopeCode: request.scopeCode, channel: request.channel, locale: request.locale, namespaces: [...new Set(request.namespaces)].sort(), entries: entries, createdBy: this.actor(request), createdAt: new Date().toISOString() }; release.checksum = this.checksum(release.entries); release.version = request.version || release.checksum.slice(0, 16); return repository.createRelease(Object.freeze(release), request); },
    /** Validates an immutable release before nPublish activation. */ validate: function (release) { if (!release || !release.checksum || release.checksum !== this.checksum(release.entries || {})) throw this.error('ERR_LOC_00004', 'Localization release checksum is invalid'); let maximum = Number(((CONFIG.get('localization') || {}).authority || {}).maximumKeysPerRelease || 10000); if (Object.keys(release.entries || {}).length > maximum) throw this.error('ERR_LOC_00005', 'Localization release contains too many entries'); Object.values(release.entries || {}).forEach(entry => SERVICE.DefaultLocalizationMessageValidationService.validate(entry.message, entry.parameters || [])); return { valid: true, checksum: release.checksum, entryCount: Object.keys(release.entries || {}).length }; },
    /** Requires trusted tenant and bundle scope. */ requireScope: function (request) { ['tenant', 'scopeCode', 'channel', 'locale'].forEach(key => { if (!request || typeof request[key] !== 'string' || !request[key]) throw this.error('ERR_LOC_00002', 'Trusted localization scope is required'); }); if (!Array.isArray(request.namespaces) || !request.namespaces.length) throw this.error('ERR_LOC_00000', 'Namespaces are required'); },
    /** Resolves an audit-safe actor. */ actor: function (request) { let auth = request.authData || {}; return String(auth.principalId || auth.code || 'system'); },
    /** Creates a stable release error. */ error: function (code, message) { let error = typeof CLASSES !== 'undefined' && CLASSES.NodicsError ? new CLASSES.NodicsError(code, message) : new Error(message); error.code = error.code || code; return error; }
};
