/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
'use strict';
/** @module localizationCore/service/DefaultLocalizationValueLifecycleService @description Governs tenant-scoped draft, review, and approval transitions for translation values using repository CAS and audit. @layer service @owner localizationCore @override Workflow integration may wrap transitions while preserving expected revision and actor evidence. */
module.exports = {
    /** Resolves the repository port. */ repository: function () { return SERVICE.DefaultLocalizationReleaseManagementService.repository(); },
    /** Creates or replaces a draft after validating it against the immutable key parameter and override contracts. */ saveDraft: async function (request) { this.requireRequest(request); let repository = this.repository(); let key = await repository.getKey(request.namespace, request.key, request); if (!key) throw this.error('ERR_LOC_00000', 'Localization key is unavailable'); let scope = SERVICE.DefaultLocalizationOverridePolicyService.validate(request, key); SERVICE.DefaultLocalizationMessageValidationService.validate(request.message, key.parameters || []); let scopedRequest = Object.assign({}, request, scope); let current = await repository.getValue(request.namespace, request.key, request.locale, scopedRequest); this.assertRevision(request.expectedRevision, current); return repository.saveValue({ tenant: request.tenant, namespace: request.namespace, key: request.key, locale: request.locale, message: request.message, state: 'DRAFT', revision: Number(current && current.revision || 0) + 1, scopeType: scope.scopeType, scopeCode: scope.scopeCode, provenance: request.provenance }, this.audit('DRAFT', scopedRequest), scopedRequest); },
    /** Submits one current draft for review. */ submitReview: function (request) { return this.transition(request, 'DRAFT', 'REVIEW'); },
    /** Approves one reviewed value and records reusable human translation memory. */ approve: async function (request) { let approved = await this.transition(request, 'REVIEW', 'APPROVED'); let repository = this.repository(); let key = await repository.getKey(request.namespace, request.key, request); if (key && request.locale !== (request.sourceLocale || request.defaultLocale || 'en')) await SERVICE.DefaultLocalizationTranslationMemoryPortService.record({ tenant: request.tenant, authData: request.authData, sourceLocale: request.sourceLocale || request.defaultLocale || 'en', targetLocale: request.locale, sourceMessage: key.defaultMessage, targetMessage: approved.message, ownerModule: key.ownerModule }); return approved; },
    /** Executes one expected-state and expected-revision transition. */ transition: async function (request, fromState, toState) { this.requireRequest(request); let repository = this.repository(); let current = await repository.getValue(request.namespace, request.key, request.locale, request); if (!current || current.state !== fromState) throw this.error('ERR_LOC_00004', 'Localization value transition is invalid'); this.assertRevision(request.expectedRevision, current); return repository.transitionValue(current, toState, Number(current.revision) + 1, this.audit(toState, request), request); },
    /** Enforces optimistic revision. */ assertRevision: function (expected, current) { let revision = Number(current && current.revision || 0); if (expected === undefined || Number(expected) !== revision) throw this.error('ERR_LOC_00004', 'Expected localization value revision is required or stale'); },
    /** Validates trusted scope and value identity. */ requireRequest: function (request) { ['tenant', 'namespace', 'key', 'locale'].forEach(field => { if (!request || typeof request[field] !== 'string' || !request[field]) throw this.error('ERR_LOC_00002', 'Localization value scope is invalid'); }); },
    /** Produces immutable audit evidence without message content. */ audit: function (state, request) { let auth = request.authData || {}; return Object.freeze({ tenant: request.tenant, namespace: request.namespace, key: request.key, locale: request.locale, toState: state, actor: String(auth.principalId || auth.code || 'system'), reason: request.reason, correlationId: request.correlationId || request.requestId, occurredAt: new Date().toISOString() }); },
    /** Creates a stable lifecycle error. */ error: function (code, message) { let error = typeof CLASSES !== 'undefined' && CLASSES.NodicsError ? new CLASSES.NodicsError(code, message) : new Error(message); error.code = error.code || code; return error; }
};
