/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module copilotApi/src/router/routers @description Defines the employee-secured Axis conversation, turn, replay, and stream contract. @layer definition @owner copilotApi @override Later API modules may extend routes while preserving ownership and permission checks. */
module.exports = {
  copilotApi: {
    workflow: {
      sourceChanged: {
        secured: true,
        authTokenTypes: ["service"],
        accessGroups: ["serviceAccountUserGroup"],
        permission: "copilot.knowledge.source.notify",
        apiExposure: "moduleInternal",
        key: "/knowledge/events/sourceChanged",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "notifyKnowledgeSourceChanged",
        cache: { enabled: false },
      },
      refreshKnowledge: {
        secured: true,
        authTokenTypes: ["service"],
        accessGroups: ["userGroup"],
        permissionConfig: "authSecurity.internalToken.routePermission",
        apiExposure: "moduleInternal",
        key: "/workflow/actions/refreshKnowledge",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "refreshWorkflowKnowledge",
        cache: { enabled: false },
      },
    },
    administration: {
      administrationHistory: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.configuration.read",
        apiExposure: "copilotApi",
        key: "/administration/history",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getAdministrationHistory",
      },
      getAdministration: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.configuration.read",
        apiExposure: "copilotApi",
        key: "/administration",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getAdministration",
      },
      previewAdministration: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.configuration.manage",
        apiExposure: "copilotApi",
        key: "/administration/preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewAdministration",
      },
      submitAdministration: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.configuration.manage",
        apiExposure: "copilotApi",
        key: "/administration/requests",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "submitAdministration",
      },
    },
    providerReadiness: {
      check: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.provider.check",
        apiExposure: "copilotApi",
        key: "/providers/check",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "checkProvider",
      },
    },
    usageReconciliation: {
      detail: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.read",
        apiExposure: "copilotApi",
        key: "/usage/call",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getUsageCall",
      },
      previewUsageReconciliation: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.usage.reconcile",
        apiExposure: "copilotApi",
        key: "/usage/reconciliation/preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewReconciliation",
      },
      reconcile: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.usage.reconcile",
        apiExposure: "copilotApi",
        key: "/usage/reconciliation",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "reconcileUsage",
      },
    },
    budgets: {
      getBudgets: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.usage.read",
        apiExposure: "copilotApi",
        key: "/budgets",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getBudgets",
      },
      previewBudgets: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.usage.read",
        apiExposure: "copilotApi",
        key: "/budgets/preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewBudget",
      },
      change: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.usage.read",
        apiExposure: "copilotApi",
        key: "/budgets/allocations",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "changeBudget",
      },
    },
    usage: {
      getUsage: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.read",
        apiExposure: "copilotApi",
        key: "/usage",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getUsage",
      },
    },
    conversationContext: {
      getConversationContext: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.read",
        apiExposure: "copilotApi",
        key: "/context",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getConversationContext",
      },
    },
    activity: {
      auditRetentionPreview: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.audit.retention.execute",
        apiExposure: "copilotApi",
        key: "/activity/audit-retention/preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewAuditRetention",
      },
      auditRetentionExecute: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.audit.retention.execute",
        apiExposure: "copilotApi",
        key: "/activity/audit-retention/execute",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "executeAuditRetention",
      },
      auditRetentionInspect: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.audit.retention.execute",
        apiExposure: "copilotApi",
        key: "/activity/audit-retention/inspect",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "inspectAuditRetention",
      },
      auditRetentionStop: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.audit.retention.execute",
        apiExposure: "copilotApi",
        key: "/activity/audit-retention/stop",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "stopAuditRetention",
      },
      search: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.activity.content.search",
        apiExposure: "copilotApi",
        key: "/activity/search",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "searchRecordedActivity",
      },
      retention: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.activity.lifecycle.read",
        apiExposure: "copilotApi",
        key: "/activity/retention",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getRetentionPreview",
      },
      previewRetentionExecution: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.activity.lifecycle.execute",
        apiExposure: "copilotApi",
        key: "/activity/:conversationCode/retention/preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewRetentionExecution",
      },
      beginRetentionExecution: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.activity.lifecycle.execute",
        apiExposure: "copilotApi",
        key: "/activity/:conversationCode/retention/begin",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "beginRetentionExecution",
      },
      inspectRetentionExecution: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.activity.lifecycle.execute",
        apiExposure: "copilotApi",
        key: "/activity/:conversationCode/retention/inspect",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "inspectRetentionExecution",
      },
      advanceRetentionExecution: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.activity.lifecycle.execute",
        apiExposure: "copilotApi",
        key: "/activity/:conversationCode/retention/advance",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "advanceRetentionExecution",
      },
      previewRetentionResume: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.activity.lifecycle.execute",
        apiExposure: "copilotApi",
        key: "/activity/:conversationCode/retention/resume-preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewRetentionResume",
      },
      previewConversationClosure: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.activity.lifecycle.execute",
        apiExposure: "copilotApi",
        key: "/activity/:conversationCode/retention/close-preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewConversationClosure",
      },
      closeConversation: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.activity.lifecycle.execute",
        apiExposure: "copilotApi",
        key: "/activity/:conversationCode/retention/close",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "closeConversation",
      },
      inspectConversationClosure: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.activity.lifecycle.execute",
        apiExposure: "copilotApi",
        key: "/activity/:conversationCode/retention/close-inspect",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "inspectConversationClosure",
      },
      resumeRetentionExecution: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.activity.lifecycle.execute",
        apiExposure: "copilotApi",
        key: "/activity/:conversationCode/retention/resume",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "resumeRetentionExecution",
      },
      stopRetentionExecution: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        permission: "copilot.activity.lifecycle.execute",
        apiExposure: "copilotApi",
        key: "/activity/:conversationCode/retention/stop",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "stopRetentionExecution",
      },
      inspect: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.activity.transcript.read",
        apiExposure: "copilotApi",
        key: "/activity/:conversationCode/transcript",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "inspectTranscript",
      },
      getActivity: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.activity.read",
        apiExposure: "copilotApi",
        key: "/activity",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getActivity",
      },
    },
    workspace: {
      getWorkspace: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.read",
        apiExposure: "copilotApi",
        key: "/workspace",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getWorkspace",
      },
    },
    conversations: {
      create: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.use",
        apiExposure: "copilotApi",
        key: "/conversations",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "createConversation",
        requestPrivacy: { sensitive: true },
      },
      list: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.read",
        apiExposure: "copilotApi",
        key: "/conversations",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "listConversations",
      },
      getConversation: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.read",
        apiExposure: "copilotApi",
        key: "/conversations/:conversationCode",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getConversation",
      },
      conversationHistory: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.read",
        apiExposure: "copilotApi",
        key: "/conversations/:conversationCode/history",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getConversationHistory",
      },
    },
    turns: {
      submit: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.use",
        apiExposure: "copilotApi",
        key: "/conversations/:conversationCode/turns",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "submitTurn",
        requestPrivacy: { sensitive: true },
      },
      getTurn: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.read",
        apiExposure: "copilotApi",
        key: "/conversations/:conversationCode/turns/:turnCode",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getTurn",
      },
      events: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.read",
        apiExposure: "copilotApi",
        key: "/conversations/:conversationCode/turns/:turnCode/events",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "replayEvents",
      },
      stream: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.read",
        apiExposure: "copilotApi",
        key: "/conversations/:conversationCode/turns/:turnCode/stream",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "streamTurn",
        responseHandler: "copilotSseResponseHandler",
      },
      cancel: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.assistant.cancel",
        apiExposure: "copilotApi",
        key: "/conversations/:conversationCode/turns/:turnCode/cancel",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "cancelTurn",
      },
    },
    knowledge: {
      erasureReview: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.knowledge.migration.erase",
        apiExposure: "copilotApi",
        key: "/knowledge/migrations/:migrationCode/erasure-preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewKnowledgeErasure",
        sensitive: true,
        cache: { enabled: false },
      },
      erasureExecute: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.knowledge.migration.erase",
        apiExposure: "copilotApi",
        key: "/knowledge/migrations/:migrationCode/erase",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "eraseKnowledgeIndex",
        sensitive: true,
        cache: { enabled: false },
      },
      erasureInspect: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.knowledge.migration.read",
        apiExposure: "copilotApi",
        key: "/knowledge/migrations/:migrationCode/erasure-inspect",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "inspectKnowledgeErasure",
        sensitive: true,
        cache: { enabled: false },
      },
      migrationReview: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.knowledge.migration.execute",
        apiExposure: "copilotApi",
        key: "/knowledge/migrations/:migrationCode/preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewKnowledgeMigration",
        sensitive: true,
        cache: { enabled: false },
      },
      migrationRetire: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.knowledge.migration.execute",
        apiExposure: "copilotApi",
        key: "/knowledge/migrations/:migrationCode/retire",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "retireKnowledgeIndex",
        sensitive: true,
        cache: { enabled: false },
      },
      migrationInspect: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.knowledge.migration.read",
        apiExposure: "copilotApi",
        key: "/knowledge/migrations/:migrationCode/inspect",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "inspectKnowledgeMigration",
        sensitive: true,
        cache: { enabled: false },
      },
      writerReview: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.knowledge.recovery.execute",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/writer-recovery/preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewKnowledgeWriterRecovery",
        cache: { enabled: false },
      },
      manualRefreshPreview: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.knowledge.source.manage",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/refresh/preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewManualKnowledgeRefresh",
        cache: { enabled: false },
      },
      manualRefreshStart: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.knowledge.source.manage",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/refresh/start",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "startManualKnowledgeRefresh",
        cache: { enabled: false },
      },
      manualRefreshInspect: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.knowledge.internal.read",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/refresh/inspect",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "inspectManualKnowledgeRefresh",
        cache: { enabled: false },
      },
      writerRetire: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.knowledge.recovery.execute",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/writer-recovery",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "retireKnowledgeWriter",
        cache: { enabled: false },
      },
      knowledgeMaintenanceHistory: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.knowledge.maintenance.read",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/maintenance",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getKnowledgeMaintenanceHistory",
        cache: { enabled: false },
      },
      cleanupPreview: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.knowledge.cleanup.execute",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/cleanup/preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewKnowledgeCleanup",
        cache: { enabled: false },
      },
      cleanup: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.knowledge.cleanup.execute",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/cleanup",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "cleanupKnowledgeSource",
        cache: { enabled: false },
      },
      collections: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.data.query",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/collections",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getSourceCollections",
      },
      query: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.data.query",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/query",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "querySourceCollection",
      },
      incidents: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.logs.read",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/incidents",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "queryIncidentEvidence",
      },
      inventory: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.knowledge.internal.read",
        apiExposure: "copilotApi",
        key: "/knowledge/sources",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getKnowledgeInventory",
      },
      history: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.knowledge.internal.read",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/history",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getKnowledgeHistory",
        cache: { enabled: false },
      },
      preview: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.knowledge.source.manage",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/preview",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "previewKnowledgeSource",
      },
      status: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.knowledge.internal.read",
        apiExposure: "copilotApi",
        key: "/knowledge/status",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getKnowledgeStatus",
      },
      refresh: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.knowledge.source.manage",
        apiExposure: "copilotApi",
        key: "/knowledge/sources/:sourceCode/refresh",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "refreshKnowledgeSource",
      },
    },
    productPlans: {
      couponWorkspace: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.mutation.prepare",
        apiExposure: "copilotApi",
        key: "/coupons/workspace",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getCouponWorkspace",
        cache: { enabled: false },
      },
      couponRedemptions: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.data.query",
        apiExposure: "copilotApi",
        key: "/coupons/redemptions",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getCouponRedemptions",
        cache: { enabled: false },
      },
      prepareCoupon: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.mutation.prepare",
        apiExposure: "copilotApi",
        key: "/coupons/prepare",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "prepareCouponPlan",
        requestPrivacy: { sensitive: true },
        cache: { enabled: false },
      },
      prepareEnterprise: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.mutation.prepare",
        apiExposure: "copilotApi",
        key: "/enterprises/prepare",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "prepareEnterprisePlan",
      },
      prepareInvitations: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.mutation.prepare",
        apiExposure: "copilotApi",
        key: "/invitations/prepare",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "prepareInvitationPlan",
        requestPrivacy: { sensitive: true },
        cache: { enabled: false },
      },
      preparePrices: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.mutation.prepare",
        apiExposure: "copilotApi",
        key: "/prices/prepare",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "preparePricePlan",
        requestPrivacy: { sensitive: true },
        cache: { enabled: false },
      },
      prepareCollectionCentres: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.mutation.prepare",
        apiExposure: "copilotApi",
        key: "/collection-centres/prepare",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "prepareCollectionCentrePlan",
      },
      prepareProducts: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.mutation.prepare",
        apiExposure: "copilotApi",
        key: "/products/prepare",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "prepareProductPlan",
      },
    },
    confirmations: {
      reconcileOriginal: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.mutation.reconcile",
        apiExposure: "copilotApi",
        cache: { enabled: false },
        requestPrivacy: { sensitive: true },
        key: "/confirmations/:confirmationCode/original-results",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "reconcileConfirmation",
      },
      get: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.mutation.prepare",
        apiExposure: "copilotApi",
        key: "/confirmations/:confirmationCode",
        method: "GET",
        controller: "DefaultCopilotController",
        operation: "getConfirmation",
      },
      approve: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.mutation.prepare",
        apiExposure: "copilotApi",
        key: "/confirmations/:confirmationCode/approve",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "approveConfirmation",
      },
      reject: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.mutation.prepare",
        apiExposure: "copilotApi",
        key: "/confirmations/:confirmationCode/reject",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "rejectConfirmation",
      },
      couponReceipt: {
        secured: true,
        authTokenTypes: ["access"],
        accessGroups: ["employeeUserGroup"],
        permission: "copilot.mutation.execute",
        apiExposure: "copilotApi",
        key: "/confirmations/:confirmationCode/coupon-receipt",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "reconcileCouponReceipt",
        requestPrivacy: { sensitive: true },
        cache: { enabled: false },
      },
      execute: {
        secured: true,
        accessGroups: ["userGroup"],
        permission: "copilot.mutation.execute",
        apiExposure: "copilotApi",
        key: "/confirmations/:confirmationCode/execute",
        method: "POST",
        controller: "DefaultCopilotController",
        operation: "executeConfirmation",
        requestPrivacy: { sensitive: true },
      },
    },
  },
};
