/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module wasteCore/src/schemas/schemas @description Defines shared Waste policy, asset, and extension-point schemas. @layer schema @owner wasteCore @override Later modules may add governed policies without moving child capability ownership. */
module.exports = { wasteCore: {
    wasteLifecyclePolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true },
        ownerModule: { type: 'string', required: true },
        lifecycleType: { type: 'string', required: true, enum: ['SUBMISSION', 'VERIFICATION', 'RECEIPT', 'IMPACT', 'MOVEMENT', 'COMPLIANCE', 'ASSET', 'ASSET_CREATION', 'TRANSFER', 'MARKETPLACE', 'REWARD_SETTLEMENT', 'CARBON_SETTLEMENT', 'COUPON_REDEMPTION'] },
        triggerEventCodes: { type: 'array', required: false },
        idempotencyRequired: { type: 'bool', required: true, default: true },
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] },
        revision: { type: 'int', required: true, default: 0 },
        metadata: { type: 'object', required: false }
    } }),
    wasteAssetCreationPolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true },
        name: { type: 'object', required: true },
        assetTypeCode: { type: 'string', required: false },
        sourceStatusRequired: { type: 'string', required: true, default: 'APPROVED' },
        verificationStatusRequired: { type: 'string', required: false },
        requiresEvidence: { type: 'bool', required: true, default: true },
        requiresReceipt: { type: 'bool', required: true, default: false },
        requiresImpactResult: { type: 'bool', required: true, default: false },
        duplicateStrategy: { type: 'string', required: true, enum: ['RETURN_EXISTING', 'FAIL'], default: 'RETURN_EXISTING' },
        assetCodeStrategy: { type: 'string', required: true, enum: ['SOURCE_SUBMISSION', 'REQUESTED', 'POLICY_PREFIX'], default: 'SOURCE_SUBMISSION' },
        assetCodePrefix: { type: 'string', required: false },
        initialCustodyStatus: { type: 'string', required: true, enum: ['CUSTOMER_HELD', 'DROPPED_AT_COLLECTION_POINT', 'RECEIVED_BY_OPERATOR', 'TRANSFERRED_TO_RECYCLER', 'PROCESSED', 'RECYCLED', 'CERTIFICATE_ISSUED', 'UNKNOWN'], default: 'CUSTOMER_HELD' },
        initialAssetStatus: { type: 'string', required: true, enum: ['OWNED', 'LOCKED', 'PENDING_ASSET_CREATION'], default: 'OWNED' },
        rewardSettlementPolicyCode: { type: 'string', required: false },
        carbonSettlementPolicyCode: { type: 'string', required: false },
        settlementReferenceFailureMode: { type: 'string', required: true, enum: ['STOP_CREATION', 'LOCK_ASSET'], default: 'STOP_CREATION' },
        effectiveFrom: { type: 'date', required: false },
        effectiveTo: { type: 'date', required: false },
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] },
        revision: { type: 'int', required: true, default: 0 },
        metadata: { type: 'object', required: false }
    } }),
    wasteAssetType: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true },
        name: { type: 'object', required: true },
        familyCode: { type: 'string', required: false },
        categoryCode: { type: 'string', required: false },
        itemTypeCode: { type: 'string', required: false },
        materialTypeCodes: { type: 'array', required: false },
        defaultImpactProfileCode: { type: 'string', required: false },
        defaultTransferPolicyCode: { type: 'string', required: false },
        defaultMarketplaceEligibilityPolicyCode: { type: 'string', required: false },
        defaultRewardSettlementPolicyCode: { type: 'string', required: false },
        defaultCarbonSettlementPolicyCode: { type: 'string', required: false },
        defaultCouponRedemptionSettlementPolicyCode: { type: 'string', required: false },
        certificateAllowed: { type: 'bool', required: true, default: true },
        marketplaceEligibleByDefault: { type: 'bool', required: true, default: false },
        giftableByDefault: { type: 'bool', required: true, default: false },
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] },
        revision: { type: 'int', required: true, default: 0 },
        metadata: { type: 'object', required: false }
    } }),
    wasteAsset: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true },
        assetTypeCode: { type: 'string', required: true },
        sourceSubmissionCode: { type: 'string', required: true },
        sourceCategoryCode: { type: 'string', required: false },
        sourceItemTypeCode: { type: 'string', required: false },
        ownerRef: { type: 'object', required: true },
        originalOwnerRef: { type: 'object', required: true },
        physicalOwnerRef: { type: 'object', required: false },
        digitalOwnerRef: { type: 'object', required: false },
        verificationRef: { type: 'object', required: true },
        receiptRef: { type: 'object', required: false },
        impactRef: { type: 'object', required: false },
        evidenceRefs: { type: 'array', required: false },
        custodyStatus: { type: 'string', required: true, enum: ['CUSTOMER_HELD', 'DROPPED_AT_COLLECTION_POINT', 'RECEIVED_BY_OPERATOR', 'TRANSFERRED_TO_RECYCLER', 'PROCESSED', 'RECYCLED', 'CERTIFICATE_ISSUED', 'UNKNOWN'] },
        assetStatus: { type: 'string', required: true, enum: ['PENDING_ASSET_CREATION', 'OWNED', 'LISTING_REQUESTED', 'LISTED', 'LISTING_FAILED', 'BID_RECEIVED', 'SALE_PENDING', 'SOLD', 'GIFT_PENDING', 'GIFTED', 'REDEMPTION_PENDING', 'REDEEMED', 'DONATION_PENDING', 'DONATED', 'LOCKED', 'DISPUTED', 'ARCHIVED'] },
        rewardSettlementRefs: { type: 'array', required: false },
        carbonSettlementRefs: { type: 'array', required: false },
        marketplaceProjectionRef: { type: 'object', required: false },
        couponEntitlementRefs: { type: 'array', required: false },
        lockRef: { type: 'object', required: false },
        policyContextRef: { type: 'object', required: false },
        sourceContext: { type: 'object', required: false },
        createdAt: { type: 'date', required: true },
        correlationId: { type: 'string', required: false },
        idempotencyKey: { type: 'string', required: false },
        revision: { type: 'int', required: true, default: 0 },
        metadata: { type: 'object', required: false }
    } }),
    wasteAssetMarketplaceProjection: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true },
        assetCode: { type: 'string', required: true },
        ownerRef: { type: 'object', required: true },
        policyCode: { type: 'string', required: true },
        projectionStatus: { type: 'string', required: true, enum: ['REQUESTED', 'PROJECTED', 'LISTED', 'SALE_PENDING', 'FAILED', 'CANCELLED', 'EXPIRED', 'SOLD', 'REVERSED'] },
        listingMode: { type: 'string', required: true, enum: ['FIXED_PRICE', 'BIDDING', 'BOTH'] },
        visibilityMode: { type: 'string', required: true, enum: ['PRIVATE', 'PUBLIC_MARKETPLACE', 'FRIENDS_ONLY', 'ENTERPRISE_BUYERS', 'RECYCLER_NETWORK'] },
        productProjectionMode: { type: 'string', required: true, enum: ['COMMERCE_PRODUCT', 'COMMERCE_LISTING', 'POLICY_RESOLVED'] },
        commerceProductRef: { type: 'object', required: false },
        commerceListingRef: { type: 'object', required: false },
        commerceOrderRef: { type: 'object', required: false },
        paymentRef: { type: 'object', required: false },
        transferPolicyCode: { type: 'string', required: false },
        rewardSettlementPolicyCode: { type: 'string', required: false },
        carbonSettlementPolicyCode: { type: 'string', required: false },
        evidenceRefs: { type: 'array', required: false },
        listingFacts: { type: 'object', required: false },
        requestedAt: { type: 'date', required: false },
        projectedAt: { type: 'date', required: false },
        closedAt: { type: 'date', required: false },
        correlationId: { type: 'string', required: false },
        idempotencyKey: { type: 'string', required: false },
        revision: { type: 'int', required: true, default: 0 },
        metadata: { type: 'object', required: false }
    } }),
    wasteAssetOwnershipEvent: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true },
        assetCode: { type: 'string', required: true },
        fromOwnerRef: { type: 'object', required: false },
        toOwnerRef: { type: 'object', required: true },
        transferType: { type: 'string', required: true, enum: ['CREATE', 'SELL', 'GIFT', 'DONATE', 'REDEEM', 'ADMIN_OVERRIDE', 'REVERSAL'] },
        transferStatus: { type: 'string', required: true, enum: ['REQUESTED', 'RESERVED', 'PENDING_ACCEPTANCE', 'COMPLETED', 'FAILED', 'CANCELLED', 'REVERSED', 'EXPIRED'] },
        policyCode: { type: 'string', required: false },
        triggerRef: { type: 'object', required: false },
        rewardSettlementRefs: { type: 'array', required: false },
        carbonSettlementRefs: { type: 'array', required: false },
        commerceProjectionRef: { type: 'object', required: false },
        commerceOrderRef: { type: 'object', required: false },
        paymentRef: { type: 'object', required: false },
        couponEntitlementRef: { type: 'object', required: false },
        movementRef: { type: 'object', required: false },
        complianceEvidenceRef: { type: 'object', required: false },
        evidenceRefs: { type: 'array', required: false },
        occurredAt: { type: 'date', required: true },
        correlationId: { type: 'string', required: false },
        idempotencyKey: { type: 'string', required: false },
        revision: { type: 'int', required: true, default: 0 },
        metadata: { type: 'object', required: false }
    } }),
    wasteAssetTransferPolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true },
        name: { type: 'object', required: true },
        assetTypeCode: { type: 'string', required: false },
        transferType: { type: 'string', required: true, enum: ['SELL', 'GIFT', 'DONATE', 'REDEEM', 'EXPIRE', 'ADMIN_OVERRIDE'] },
        ownershipTransferMode: { type: 'string', required: true, enum: ['TRANSFER_TO_COUNTERPARTY', 'RETAIN_CURRENT_OWNER', 'TRANSFER_TO_ENTERPRISE', 'POLICY_RESOLVED'] },
        rewardTransferMode: { type: 'string', required: true, enum: ['RETAIN_ORIGINAL_OWNER', 'TRANSFER_TO_COUNTERPARTY', 'TRANSFER_TO_ENTERPRISE', 'SPLIT', 'CONSUME', 'NONE', 'POLICY_RESOLVED'] },
        carbonTransferMode: { type: 'string', required: true, enum: ['TRANSFER_TO_COUNTERPARTY', 'TRANSFER_TO_ISSUER_ENTERPRISE', 'TRANSFER_TO_DEFAULT_ENTERPRISE', 'TRANSFER_TO_FIXED_ENTERPRISE', 'RETAIN_CURRENT_OWNER', 'SPLIT', 'NONE', 'POLICY_RESOLVED'] },
        eligibleAssetStatuses: { type: 'array', required: false },
        allowSelfTransfer: { type: 'bool', required: true, default: false },
        requiresOwnerApproval: { type: 'bool', required: true, default: true },
        requiresCounterpartyAcceptance: { type: 'bool', required: true, default: false },
        requiresReceiptConfirmation: { type: 'bool', required: true, default: false },
        requiresComplianceReview: { type: 'bool', required: true, default: false },
        lockRequired: { type: 'bool', required: true, default: true },
        completionAssetStatus: { type: 'string', required: false, enum: ['OWNED', 'LISTED', 'SOLD', 'GIFTED', 'REDEEMED', 'DONATED', 'LOCKED', 'ARCHIVED'] },
        completionCustodyStatus: { type: 'string', required: false, enum: ['CUSTOMER_HELD', 'DROPPED_AT_COLLECTION_POINT', 'RECEIVED_BY_OPERATOR', 'TRANSFERRED_TO_RECYCLER', 'PROCESSED', 'RECYCLED', 'CERTIFICATE_ISSUED', 'UNKNOWN'] },
        cancellationAssetStatus: { type: 'string', required: false, enum: ['OWNED', 'LISTED', 'LOCKED'] },
        reversalAssetStatus: { type: 'string', required: false, enum: ['OWNED', 'LISTED', 'LOCKED'] },
        effectiveFrom: { type: 'date', required: false },
        effectiveTo: { type: 'date', required: false },
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] },
        revision: { type: 'int', required: true, default: 0 },
        metadata: { type: 'object', required: false }
    } }),
    wasteMarketplaceEligibilityPolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true },
        name: { type: 'object', required: true },
        assetTypeCode: { type: 'string', required: false },
        eligibleAssetStatuses: { type: 'array', required: true },
        eligibleCustodyStatuses: { type: 'array', required: false },
        listingMode: { type: 'string', required: true, enum: ['FIXED_PRICE', 'BIDDING', 'BOTH', 'DISABLED'] },
        visibilityMode: { type: 'string', required: true, enum: ['PRIVATE', 'PUBLIC_MARKETPLACE', 'FRIENDS_ONLY', 'ENTERPRISE_BUYERS', 'RECYCLER_NETWORK'] },
        valuationMode: { type: 'string', required: true, enum: ['MANUAL', 'CATEGORY_SUGGESTED', 'MATERIAL_SUGGESTED', 'CARBON_VALUE_SUGGESTED', 'REWARD_VALUE_SUGGESTED', 'EXTERNAL_ADAPTER'] },
        productProjectionMode: { type: 'string', required: true, enum: ['NONE', 'COMMERCE_PRODUCT', 'COMMERCE_LISTING', 'POLICY_RESOLVED'] },
        requiresComplianceReview: { type: 'bool', required: true, default: false },
        effectiveFrom: { type: 'date', required: false },
        effectiveTo: { type: 'date', required: false },
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] },
        revision: { type: 'int', required: true, default: 0 },
        metadata: { type: 'object', required: false }
    } }),
    wasteRewardSettlementPolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true },
        name: { type: 'object', required: true },
        assetTypeCode: { type: 'string', required: false },
        triggerType: { type: 'string', required: true, enum: ['APPROVAL', 'RECEIPT', 'SALE', 'GIFT', 'DONATION', 'COUPON_PURCHASE', 'REVERSAL'] },
        settlementMode: { type: 'string', required: true, enum: ['CREDIT_ORIGINAL_OWNER', 'TRANSFER_TO_COUNTERPARTY', 'TRANSFER_TO_ENTERPRISE', 'RESERVE', 'DEBIT_FIXED', 'DEBIT_PROPORTIONAL', 'DEBIT_FULL_ELIGIBLE', 'SPLIT', 'NONE', 'POLICY_RESOLVED'] },
        walletCurrencyCode: { type: 'string', required: false },
        fixedAmount: { type: 'string', required: false },
        splitRules: { type: 'array', required: false },
        sponsorRef: { type: 'object', required: false },
        expiryPolicyCode: { type: 'string', required: false },
        reversalAllowed: { type: 'bool', required: true, default: true },
        effectiveFrom: { type: 'date', required: false },
        effectiveTo: { type: 'date', required: false },
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] },
        revision: { type: 'int', required: true, default: 0 },
        metadata: { type: 'object', required: false }
    } }),
    wasteCarbonSettlementPolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true },
        name: { type: 'object', required: true },
        assetTypeCode: { type: 'string', required: false },
        triggerType: { type: 'string', required: true, enum: ['APPROVAL', 'RECEIPT', 'SALE', 'GIFT', 'DONATION', 'COUPON_PURCHASE', 'REVERSAL'] },
        settlementMode: { type: 'string', required: true, enum: ['ISSUE_TO_OWNER', 'TRANSFER_TO_COUNTERPARTY', 'TRANSFER_TO_ISSUER_ENTERPRISE', 'TRANSFER_TO_DEFAULT_ENTERPRISE', 'TRANSFER_TO_FIXED_ENTERPRISE', 'RETAIN_CURRENT_OWNER', 'SPLIT', 'NONE', 'POLICY_RESOLVED'] },
        carbonUnitCode: { type: 'string', required: false },
        receiverRef: { type: 'object', required: false },
        splitRules: { type: 'array', required: false },
        provenanceRequired: { type: 'bool', required: true, default: true },
        complianceReviewRequired: { type: 'bool', required: true, default: false },
        reversalAllowed: { type: 'bool', required: true, default: true },
        effectiveFrom: { type: 'date', required: false },
        effectiveTo: { type: 'date', required: false },
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] },
        revision: { type: 'int', required: true, default: 0 },
        metadata: { type: 'object', required: false }
    } }),
    wasteCouponRedemptionSettlementPolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true },
        name: { type: 'object', required: true },
        assetTypeCode: { type: 'string', required: false },
        couponListingRef: { type: 'object', required: false },
        eligibleAssetStatuses: { type: 'array', required: false },
        rewardDebitMode: { type: 'string', required: true, enum: ['FIXED_AMOUNT', 'PROPORTIONAL_AMOUNT', 'FULL_ELIGIBLE_BALANCE', 'POLICY_RESOLVED'] },
        rewardReserveRequired: { type: 'bool', required: true, default: true },
        carbonReceiverMode: { type: 'string', required: true, enum: ['ISSUER_ENTERPRISE', 'DEFAULT_ENTERPRISE', 'FIXED_ENTERPRISE', 'SPLIT_ENTERPRISE', 'NONE', 'POLICY_RESOLVED'] },
        carbonTransferQuantityMode: { type: 'string', required: true, enum: ['FULL_AVAILABLE', 'PROPORTIONAL_TO_REWARD_COST', 'FIXED', 'NONE', 'POLICY_RESOLVED'] },
        defaultCarbonReceiverRef: { type: 'object', required: false },
        rewardSettlementPolicyCode: { type: 'string', required: false },
        carbonSettlementPolicyCode: { type: 'string', required: false },
        entitlementMode: { type: 'string', required: true, enum: ['CUSTOMER_OWNED', 'ISSUER_OWNED', 'POLICY_RESOLVED'] },
        cancellationPolicyCode: { type: 'string', required: false },
        expiryPolicyCode: { type: 'string', required: false },
        effectiveFrom: { type: 'date', required: false },
        effectiveTo: { type: 'date', required: false },
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] },
        revision: { type: 'int', required: true, default: 0 },
        metadata: { type: 'object', required: false }
    } })
} };
