/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module wasteCore/src/schemas/schemas @description Defines shared Waste policy, asset, and extension-point schemas. @layer schema @owner wasteCore @override Later modules may add governed policies without moving child capability ownership. */


module.exports = { wasteCore: {
    wasteLifecyclePolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'},
        ownerModule: { type: 'string', required: true , description: 'Stores the owner module value used by this record.'},
        lifecycleType: { type: 'string', required: true, enum: ['SUBMISSION', 'VERIFICATION', 'RECEIPT', 'IMPACT', 'MOVEMENT', 'COMPLIANCE', 'ASSET', 'ASSET_CREATION', 'TRANSFER', 'MARKETPLACE', 'REWARD_SETTLEMENT', 'CARBON_SETTLEMENT', 'COUPON_REDEMPTION'] , description: 'Classifies this record by lifecycle type for validation and business handling.'},
        triggerEventCodes: { type: 'array', required: false , description: 'Lists trigger event codes used to classify, link, or resolve this record.'},
        idempotencyRequired: { type: 'bool', required: true, default: true , description: 'Indicates whether idempotency is required for this record.'},
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'},
        metadata: { type: 'object', required: false , description: 'Stores additional structured metadata needed by extensions without changing the core schema contract.'}
    } }),
    wasteAssetCreationPolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'},
        name: { type: 'object', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'},
        assetTypeCode: { type: 'string', required: false , description: 'Stores the asset type code used to classify, link, or resolve this record.'},
        sourceStatusRequired: { type: 'string', required: true, default: 'APPROVED' , description: 'Stores the source status required value, using the configured default when no explicit value is provided.'},
        verificationStatusRequired: { type: 'string', required: false , description: 'Stores the verification status required value used by this record.'},
        requiresEvidence: { type: 'bool', required: true, default: true , description: 'Indicates whether evidence applies for this record.'},
        requiresReceipt: { type: 'bool', required: true, default: false , description: 'Indicates whether receipt applies for this record.'},
        requiresImpactResult: { type: 'bool', required: true, default: false , description: 'Indicates whether impact result applies for this record.'},
        duplicateStrategy: { type: 'string', required: true, enum: ['RETURN_EXISTING', 'FAIL'], default: 'RETURN_EXISTING' , description: 'Selects the duplicate strategy value used to drive validation, filtering, and business behavior.'},
        assetCodeStrategy: { type: 'string', required: true, enum: ['SOURCE_SUBMISSION', 'REQUESTED', 'POLICY_PREFIX'], default: 'SOURCE_SUBMISSION' , description: 'Selects the asset code strategy value used to drive validation, filtering, and business behavior.'},
        assetCodePrefix: { type: 'string', required: false , description: 'Stores the asset code prefix value used by this record.'},
        initialCustodyStatus: { type: 'string', required: true, enum: ['CUSTOMER_HELD', 'DROPPED_AT_COLLECTION_POINT', 'RECEIVED_BY_OPERATOR', 'TRANSFERRED_TO_RECYCLER', 'PROCESSED', 'RECYCLED', 'CERTIFICATE_ISSUED', 'UNKNOWN'], default: 'CUSTOMER_HELD' , description: 'Selects the initial custody status value used to drive validation, filtering, and business behavior.'},
        initialAssetStatus: { type: 'string', required: true, enum: ['OWNED', 'LOCKED', 'PENDING_ASSET_CREATION'], default: 'OWNED' , description: 'Selects the initial asset status value used to drive validation, filtering, and business behavior.'},
        rewardSettlementPolicyCode: { type: 'string', required: false , description: 'Stores the reward settlement policy code used to classify, link, or resolve this record.'},
        carbonSettlementPolicyCode: { type: 'string', required: false , description: 'Stores the carbon settlement policy code used to classify, link, or resolve this record.'},
        settlementReferenceFailureMode: { type: 'string', required: true, enum: ['STOP_CREATION', 'LOCK_ASSET'], default: 'STOP_CREATION' , description: 'Selects the settlement reference failure mode value used to drive validation, filtering, and business behavior.'},
        effectiveFrom: { type: 'date', required: false , description: 'Defines when this record becomes effective for business use.'},
        effectiveTo: { type: 'date', required: false , description: 'Defines when this record stops being effective for business use.'},
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'},
        metadata: { type: 'object', required: false , description: 'Stores additional structured metadata needed by extensions without changing the core schema contract.'}
    } }),
    wasteAssetType: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'},
        name: { type: 'object', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'},
        familyCode: { type: 'string', required: false , description: 'Stores the family code used to classify, link, or resolve this record.'},
        categoryCode: { type: 'string', required: false , description: 'Stores the category code used to classify, link, or resolve this record.'},
        itemTypeCode: { type: 'string', required: false , description: 'Stores the item type code used to classify, link, or resolve this record.'},
        materialTypeCodes: { type: 'array', required: false , description: 'Lists material type codes used to classify, link, or resolve this record.'},
        defaultImpactProfileCode: { type: 'string', required: false , description: 'Stores the default impact profile code used to classify, link, or resolve this record.'},
        defaultTransferPolicyCode: { type: 'string', required: false , description: 'Stores the default transfer policy code used to classify, link, or resolve this record.'},
        defaultMarketplaceEligibilityPolicyCode: { type: 'string', required: false , description: 'Stores the default marketplace eligibility policy code used to classify, link, or resolve this record.'},
        defaultRewardSettlementPolicyCode: { type: 'string', required: false , description: 'Stores the default reward settlement policy code used to classify, link, or resolve this record.'},
        defaultCarbonSettlementPolicyCode: { type: 'string', required: false , description: 'Stores the default carbon settlement policy code used to classify, link, or resolve this record.'},
        defaultCouponRedemptionSettlementPolicyCode: { type: 'string', required: false , description: 'Stores the default coupon redemption settlement policy code used to classify, link, or resolve this record.'},
        certificateAllowed: { type: 'bool', required: true, default: true , description: 'Indicates whether certificate allowed applies for this record.'},
        marketplaceEligibleByDefault: { type: 'bool', required: true, default: false , description: 'Indicates whether marketplace eligible by default applies for this record.'},
        giftableByDefault: { type: 'bool', required: true, default: false , description: 'Indicates whether giftable by default applies for this record.'},
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'},
        metadata: { type: 'object', required: false , description: 'Stores additional structured metadata needed by extensions without changing the core schema contract.'}
    } }),
    wasteAsset: Object.assign({ super: 'base', model: true, backoffice: { mutationMode: 'READ_ONLY', concurrency: { managed: true, field: 'revision' } }, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'},
        assetTypeCode: { type: 'string', required: true , description: 'Stores the asset type code used to classify, link, or resolve this record.'},
        sourceSubmissionCode: { type: 'string', required: true , description: 'Stores the source submission code used to classify, link, or resolve this record.'},
        sourceCategoryCode: { type: 'string', required: false , description: 'Stores the source category code used to classify, link, or resolve this record.'},
        sourceItemTypeCode: { type: 'string', required: false , description: 'Stores the source item type code used to classify, link, or resolve this record.'},
        ownerRef: { type: 'object', required: true , description: 'References the related owner record used by this record.'},
        originalOwnerRef: { type: 'object', required: true , description: 'References the related original owner record used by this record.'},
        physicalOwnerRef: { type: 'object', required: false , description: 'References the related physical owner record used by this record.'},
        digitalOwnerRef: { type: 'object', required: false , description: 'References the related digital owner record used by this record.'},
        verificationRef: { type: 'object', required: true , description: 'References the related verification record used by this record.'},
        receiptRef: { type: 'object', required: false , description: 'References the related receipt record used by this record.'},
        impactRef: { type: 'object', required: false , description: 'References the related impact record used by this record.'},
        evidenceRefs: { type: 'array', required: false , description: 'Lists related evidence records used by this record.'},
        custodyStatus: { type: 'string', required: true, enum: ['CUSTOMER_HELD', 'DROPPED_AT_COLLECTION_POINT', 'RECEIVED_BY_OPERATOR', 'TRANSFERRED_TO_RECYCLER', 'PROCESSED', 'RECYCLED', 'CERTIFICATE_ISSUED', 'UNKNOWN'] , description: 'Selects the custody status value used to drive validation, filtering, and business behavior.'},
        assetStatus: { type: 'string', required: true, enum: ['PENDING_ASSET_CREATION', 'OWNED', 'LISTING_REQUESTED', 'LISTED', 'LISTING_FAILED', 'BID_RECEIVED', 'SALE_PENDING', 'SOLD', 'GIFT_PENDING', 'GIFTED', 'REDEMPTION_PENDING', 'REDEEMED', 'DONATION_PENDING', 'DONATED', 'LOCKED', 'DISPUTED', 'ARCHIVED'] , description: 'Selects the asset status value used to drive validation, filtering, and business behavior.'},
        rewardSettlementRefs: { type: 'array', required: false , description: 'Lists related reward settlement records used by this record.'},
        carbonSettlementRefs: { type: 'array', required: false , description: 'Lists related carbon settlement records used by this record.'},
        marketplaceProjectionRef: { type: 'object', required: false , description: 'References the related marketplace projection record used by this record.'},
        couponEntitlementRefs: { type: 'array', required: false , description: 'Lists related coupon entitlement records used by this record.'},
        lockRef: { type: 'object', required: false , description: 'References the related lock record used by this record.'},
        policyContextRef: { type: 'object', required: false , description: 'References the related policy context record used by this record.'},
        sourceContext: { type: 'object', required: false , description: 'Stores structured source context details used by this record.'},
        createdAt: { type: 'date', required: true , description: 'Records when the created event or value applies.'},
        correlationId: { type: 'string', required: false , description: 'Stores the correlation identifier used to correlate this record.'},
        idempotencyKey: { type: 'string', required: false , description: 'Stores the idempotency key value used by this record.'},
        revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'},
        metadata: { type: 'object', required: false , description: 'Stores additional structured metadata needed by extensions without changing the core schema contract.'}
    }, refSchema: {
        ownerRef: {"enabled":true,"moduleName":"profile","schemaName":"customer","type":"one","propertyName":"code"},
        originalOwnerRef: {"enabled":true,"moduleName":"profile","schemaName":"customer","type":"one","propertyName":"code"},
        physicalOwnerRef: {"enabled":true,"moduleName":"profile","schemaName":"customer","type":"one","propertyName":"code"},
        digitalOwnerRef: {"enabled":true,"moduleName":"profile","schemaName":"customer","type":"one","propertyName":"code"},
        verificationRef: {"enabled":true,"moduleName":"wasteVerification","schemaName":"wasteVerification","type":"one","propertyName":"code"},
        receiptRef: {"enabled":true,"moduleName":"wasteReceipt","schemaName":"wasteReceipt","type":"one","propertyName":"code"},
        impactRef: {"enabled":true,"moduleName":"wasteImpact","schemaName":"wasteImpactResult","type":"one","propertyName":"code"},
        evidenceRefs: {"enabled":true,"moduleName":"wasteSubmission","schemaName":"wasteEvidence","type":"many","propertyName":"code"},
        marketplaceProjectionRef: {"enabled":true,"moduleName":"wasteCore","schemaName":"wasteAssetMarketplaceProjection","type":"one","propertyName":"code"}
    } }),
    wasteAssetMarketplaceProjection: Object.assign({ super: 'base', model: true, backoffice: { concurrency: { managed: true, field: 'revision' } }, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'},
        assetCode: { type: 'string', required: true , description: 'Stores the asset code used to classify, link, or resolve this record.'},
        ownerRef: { type: 'object', required: true , description: 'References the related owner record used by this record.'},
        policyCode: { type: 'string', required: true , description: 'Stores the policy code used to classify, link, or resolve this record.'},
        projectionStatus: { type: 'string', required: true, enum: ['REQUESTED', 'PROJECTED', 'LISTED', 'SALE_PENDING', 'FAILED', 'CANCELLED', 'EXPIRED', 'SOLD', 'REVERSED'] , description: 'Selects the projection status value used to drive validation, filtering, and business behavior.'},
        listingMode: { type: 'string', required: true, enum: ['FIXED_PRICE', 'BIDDING', 'BOTH'] , description: 'Selects the listing mode value used to drive validation, filtering, and business behavior.'},
        visibilityMode: { type: 'string', required: true, enum: ['PRIVATE', 'PUBLIC_MARKETPLACE', 'FRIENDS_ONLY', 'ENTERPRISE_BUYERS', 'RECYCLER_NETWORK'] , description: 'Selects the visibility mode value used to drive validation, filtering, and business behavior.'},
        productProjectionMode: { type: 'string', required: true, enum: ['COMMERCE_PRODUCT', 'COMMERCE_LISTING', 'POLICY_RESOLVED'] , description: 'Selects the product projection mode value used to drive validation, filtering, and business behavior.'},
        commerceProductRef: { type: 'object', required: false , description: 'References the related commerce product record used by this record.'},
        commerceListingRef: { type: 'object', required: false , description: 'References the related commerce listing record used by this record.'},
        commerceOrderRef: { type: 'object', required: false , description: 'References the related commerce order record used by this record.'},
        paymentRef: { type: 'object', required: false , description: 'References the related payment record used by this record.'},
        transferPolicyCode: { type: 'string', required: false , description: 'Stores the transfer policy code used to classify, link, or resolve this record.'},
        rewardSettlementPolicyCode: { type: 'string', required: false , description: 'Stores the reward settlement policy code used to classify, link, or resolve this record.'},
        carbonSettlementPolicyCode: { type: 'string', required: false , description: 'Stores the carbon settlement policy code used to classify, link, or resolve this record.'},
        evidenceRefs: { type: 'array', required: false , description: 'Lists related evidence records used by this record.'},
        listingFacts: { type: 'object', required: false , description: 'Stores structured listing facts details used by this record.'},
        requestedAt: { type: 'date', required: false , description: 'Records when the requested event or value applies.'},
        projectedAt: { type: 'date', required: false , description: 'Records when the projected event or value applies.'},
        closedAt: { type: 'date', required: false , description: 'Records when the closed event or value applies.'},
        correlationId: { type: 'string', required: false , description: 'Stores the correlation identifier used to correlate this record.'},
        idempotencyKey: { type: 'string', required: false , description: 'Stores the idempotency key value used by this record.'},
        revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'},
        metadata: { type: 'object', required: false , description: 'Stores additional structured metadata needed by extensions without changing the core schema contract.'}
    }, refSchema: {
        ownerRef: {"enabled":true,"moduleName":"profile","schemaName":"customer","type":"one","propertyName":"code"},
        commerceProductRef: {"enabled":true,"moduleName":"product","schemaName":"product","type":"one","propertyName":"code"},
        commerceOrderRef: {"enabled":true,"moduleName":"order","schemaName":"commerceOrder","type":"one","propertyName":"code"},
        paymentRef: {"enabled":true,"moduleName":"paymentCore","schemaName":"paymentTransaction","type":"one","propertyName":"code"},
        evidenceRefs: {"enabled":true,"moduleName":"wasteSubmission","schemaName":"wasteEvidence","type":"many","propertyName":"code"}
    } }),
    wasteAssetOwnershipEvent: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'},
        assetCode: { type: 'string', required: true , description: 'Stores the asset code used to classify, link, or resolve this record.'},
        fromOwnerRef: { type: 'object', required: false , description: 'References the related from owner record used by this record.'},
        toOwnerRef: { type: 'object', required: true , description: 'References the related to owner record used by this record.'},
        transferType: { type: 'string', required: true, enum: ['CREATE', 'SELL', 'GIFT', 'DONATE', 'REDEEM', 'ADMIN_OVERRIDE', 'REVERSAL'] , description: 'Classifies this record by transfer type for validation and business handling.'},
        transferStatus: { type: 'string', required: true, enum: ['REQUESTED', 'RESERVED', 'PENDING_ACCEPTANCE', 'COMPLETED', 'FAILED', 'CANCELLED', 'REVERSED', 'EXPIRED'] , description: 'Selects the transfer status value used to drive validation, filtering, and business behavior.'},
        policyCode: { type: 'string', required: false , description: 'Stores the policy code used to classify, link, or resolve this record.'},
        triggerRef: { type: 'object', required: false , description: 'References the related trigger record used by this record.'},
        rewardSettlementRefs: { type: 'array', required: false , description: 'Lists related reward settlement records used by this record.'},
        carbonSettlementRefs: { type: 'array', required: false , description: 'Lists related carbon settlement records used by this record.'},
        commerceProjectionRef: { type: 'object', required: false , description: 'References the related commerce projection record used by this record.'},
        commerceOrderRef: { type: 'object', required: false , description: 'References the related commerce order record used by this record.'},
        paymentRef: { type: 'object', required: false , description: 'References the related payment record used by this record.'},
        couponEntitlementRef: { type: 'object', required: false , description: 'References the related coupon entitlement record used by this record.'},
        movementRef: { type: 'object', required: false , description: 'References the related movement record used by this record.'},
        complianceEvidenceRef: { type: 'object', required: false , description: 'References the related compliance evidence record used by this record.'},
        evidenceRefs: { type: 'array', required: false , description: 'Lists related evidence records used by this record.'},
        occurredAt: { type: 'date', required: true , description: 'Records when the occurred event or value applies.'},
        correlationId: { type: 'string', required: false , description: 'Stores the correlation identifier used to correlate this record.'},
        idempotencyKey: { type: 'string', required: false , description: 'Stores the idempotency key value used by this record.'},
        revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'},
        metadata: { type: 'object', required: false , description: 'Stores additional structured metadata needed by extensions without changing the core schema contract.'}
    }, refSchema: {
        fromOwnerRef: {"enabled":true,"moduleName":"profile","schemaName":"customer","type":"one","propertyName":"code"},
        toOwnerRef: {"enabled":true,"moduleName":"profile","schemaName":"customer","type":"one","propertyName":"code"},
        commerceProjectionRef: {"enabled":true,"moduleName":"wasteCore","schemaName":"wasteAssetMarketplaceProjection","type":"one","propertyName":"code"},
        commerceOrderRef: {"enabled":true,"moduleName":"order","schemaName":"commerceOrder","type":"one","propertyName":"code"},
        paymentRef: {"enabled":true,"moduleName":"paymentCore","schemaName":"paymentTransaction","type":"one","propertyName":"code"},
        movementRef: {"enabled":true,"moduleName":"wasteMovement","schemaName":"wasteMovement","type":"one","propertyName":"code"},
        complianceEvidenceRef: {"enabled":true,"moduleName":"wasteCompliance","schemaName":"wasteComplianceEvidence","type":"one","propertyName":"code"},
        evidenceRefs: {"enabled":true,"moduleName":"wasteSubmission","schemaName":"wasteEvidence","type":"many","propertyName":"code"}
    } }),
    wasteAssetTransferPolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'},
        name: { type: 'object', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'},
        assetTypeCode: { type: 'string', required: false , description: 'Stores the asset type code used to classify, link, or resolve this record.'},
        transferType: { type: 'string', required: true, enum: ['SELL', 'GIFT', 'DONATE', 'REDEEM', 'EXPIRE', 'ADMIN_OVERRIDE'] , description: 'Classifies this record by transfer type for validation and business handling.'},
        ownershipTransferMode: { type: 'string', required: true, enum: ['TRANSFER_TO_COUNTERPARTY', 'RETAIN_CURRENT_OWNER', 'TRANSFER_TO_ENTERPRISE', 'POLICY_RESOLVED'] , description: 'Selects the ownership transfer mode value used to drive validation, filtering, and business behavior.'},
        rewardTransferMode: { type: 'string', required: true, enum: ['RETAIN_ORIGINAL_OWNER', 'TRANSFER_TO_COUNTERPARTY', 'TRANSFER_TO_ENTERPRISE', 'SPLIT', 'CONSUME', 'NONE', 'POLICY_RESOLVED'] , description: 'Selects the reward transfer mode value used to drive validation, filtering, and business behavior.'},
        carbonTransferMode: { type: 'string', required: true, enum: ['TRANSFER_TO_COUNTERPARTY', 'TRANSFER_TO_ISSUER_ENTERPRISE', 'TRANSFER_TO_DEFAULT_ENTERPRISE', 'TRANSFER_TO_FIXED_ENTERPRISE', 'RETAIN_CURRENT_OWNER', 'SPLIT', 'NONE', 'POLICY_RESOLVED'] , description: 'Selects the carbon transfer mode value used to drive validation, filtering, and business behavior.'},
        eligibleAssetStatuses: { type: 'array', required: false , description: 'Lists the eligible asset statuses associated with this record.'},
        allowSelfTransfer: { type: 'bool', required: true, default: false , description: 'Indicates whether self transfer applies for this record.'},
        requiresOwnerApproval: { type: 'bool', required: true, default: true , description: 'Indicates whether owner approval applies for this record.'},
        requiresCounterpartyAcceptance: { type: 'bool', required: true, default: false , description: 'Indicates whether counterparty acceptance applies for this record.'},
        requiresReceiptConfirmation: { type: 'bool', required: true, default: false , description: 'Indicates whether receipt confirmation applies for this record.'},
        requiresComplianceReview: { type: 'bool', required: true, default: false , description: 'Indicates whether compliance review applies for this record.'},
        lockRequired: { type: 'bool', required: true, default: true , description: 'Indicates whether lock is required for this record.'},
        completionAssetStatus: { type: 'string', required: false, enum: ['OWNED', 'LISTED', 'SOLD', 'GIFTED', 'REDEEMED', 'DONATED', 'LOCKED', 'ARCHIVED'] , description: 'Selects the completion asset status value used to drive validation, filtering, and business behavior.'},
        completionCustodyStatus: { type: 'string', required: false, enum: ['CUSTOMER_HELD', 'DROPPED_AT_COLLECTION_POINT', 'RECEIVED_BY_OPERATOR', 'TRANSFERRED_TO_RECYCLER', 'PROCESSED', 'RECYCLED', 'CERTIFICATE_ISSUED', 'UNKNOWN'] , description: 'Selects the completion custody status value used to drive validation, filtering, and business behavior.'},
        cancellationAssetStatus: { type: 'string', required: false, enum: ['OWNED', 'LISTED', 'LOCKED'] , description: 'Selects the cancellation asset status value used to drive validation, filtering, and business behavior.'},
        reversalAssetStatus: { type: 'string', required: false, enum: ['OWNED', 'LISTED', 'LOCKED'] , description: 'Selects the reversal asset status value used to drive validation, filtering, and business behavior.'},
        effectiveFrom: { type: 'date', required: false , description: 'Defines when this record becomes effective for business use.'},
        effectiveTo: { type: 'date', required: false , description: 'Defines when this record stops being effective for business use.'},
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'},
        metadata: { type: 'object', required: false , description: 'Stores additional structured metadata needed by extensions without changing the core schema contract.'}
    } }),
    wasteMarketplaceEligibilityPolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'},
        name: { type: 'object', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'},
        assetTypeCode: { type: 'string', required: false , description: 'Stores the asset type code used to classify, link, or resolve this record.'},
        eligibleAssetStatuses: { type: 'array', required: true , description: 'Lists the eligible asset statuses associated with this record.'},
        eligibleCustodyStatuses: { type: 'array', required: false , description: 'Lists the eligible custody statuses associated with this record.'},
        listingMode: { type: 'string', required: true, enum: ['FIXED_PRICE', 'BIDDING', 'BOTH', 'DISABLED'] , description: 'Selects the listing mode value used to drive validation, filtering, and business behavior.'},
        visibilityMode: { type: 'string', required: true, enum: ['PRIVATE', 'PUBLIC_MARKETPLACE', 'FRIENDS_ONLY', 'ENTERPRISE_BUYERS', 'RECYCLER_NETWORK'] , description: 'Selects the visibility mode value used to drive validation, filtering, and business behavior.'},
        valuationMode: { type: 'string', required: true, enum: ['MANUAL', 'CATEGORY_SUGGESTED', 'MATERIAL_SUGGESTED', 'CARBON_VALUE_SUGGESTED', 'REWARD_VALUE_SUGGESTED', 'EXTERNAL_ADAPTER'] , description: 'Selects the valuation mode value used to drive validation, filtering, and business behavior.'},
        productProjectionMode: { type: 'string', required: true, enum: ['NONE', 'COMMERCE_PRODUCT', 'COMMERCE_LISTING', 'POLICY_RESOLVED'] , description: 'Selects the product projection mode value used to drive validation, filtering, and business behavior.'},
        requiresComplianceReview: { type: 'bool', required: true, default: false , description: 'Indicates whether compliance review applies for this record.'},
        effectiveFrom: { type: 'date', required: false , description: 'Defines when this record becomes effective for business use.'},
        effectiveTo: { type: 'date', required: false , description: 'Defines when this record stops being effective for business use.'},
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'},
        metadata: { type: 'object', required: false , description: 'Stores additional structured metadata needed by extensions without changing the core schema contract.'}
    } }),
    wasteRewardSettlementPolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'},
        name: { type: 'object', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'},
        assetTypeCode: { type: 'string', required: false , description: 'Stores the asset type code used to classify, link, or resolve this record.'},
        triggerType: { type: 'string', required: true, enum: ['APPROVAL', 'RECEIPT', 'SALE', 'GIFT', 'DONATION', 'COUPON_PURCHASE', 'REVERSAL'] , description: 'Classifies this record by trigger type for validation and business handling.'},
        settlementMode: { type: 'string', required: true, enum: ['CREDIT_ORIGINAL_OWNER', 'TRANSFER_TO_COUNTERPARTY', 'TRANSFER_TO_ENTERPRISE', 'RESERVE', 'DEBIT_FIXED', 'DEBIT_PROPORTIONAL', 'DEBIT_FULL_ELIGIBLE', 'SPLIT', 'NONE', 'POLICY_RESOLVED'] , description: 'Selects the settlement mode value used to drive validation, filtering, and business behavior.'},
        walletCurrencyCode: { type: 'string', required: false , description: 'Stores the wallet currency code used to classify, link, or resolve this record.'},
        fixedAmount: { type: 'string', required: false , description: 'Stores the fixed amount used for calculation, reporting, or settlement.'},
        splitRules: { type: 'array', required: false , description: 'Lists the split rules associated with this record.'},
        sponsorRef: { type: 'object', required: false , description: 'References the related sponsor record used by this record.'},
        expiryPolicyCode: { type: 'string', required: false , description: 'Stores the expiry policy code used to classify, link, or resolve this record.'},
        reversalAllowed: { type: 'bool', required: true, default: true , description: 'Indicates whether reversal allowed applies for this record.'},
        effectiveFrom: { type: 'date', required: false , description: 'Defines when this record becomes effective for business use.'},
        effectiveTo: { type: 'date', required: false , description: 'Defines when this record stops being effective for business use.'},
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'},
        metadata: { type: 'object', required: false , description: 'Stores additional structured metadata needed by extensions without changing the core schema contract.'}
    }, refSchema: {
        sponsorRef: {"enabled":true,"moduleName":"profile","schemaName":"enterprise","type":"one","propertyName":"code"}
    } }),
    wasteCarbonSettlementPolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'},
        name: { type: 'object', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'},
        assetTypeCode: { type: 'string', required: false , description: 'Stores the asset type code used to classify, link, or resolve this record.'},
        triggerType: { type: 'string', required: true, enum: ['APPROVAL', 'RECEIPT', 'SALE', 'GIFT', 'DONATION', 'COUPON_PURCHASE', 'REVERSAL'] , description: 'Classifies this record by trigger type for validation and business handling.'},
        settlementMode: { type: 'string', required: true, enum: ['ISSUE_TO_OWNER', 'TRANSFER_TO_COUNTERPARTY', 'TRANSFER_TO_ISSUER_ENTERPRISE', 'TRANSFER_TO_DEFAULT_ENTERPRISE', 'TRANSFER_TO_FIXED_ENTERPRISE', 'RETAIN_CURRENT_OWNER', 'SPLIT', 'NONE', 'POLICY_RESOLVED'] , description: 'Selects the settlement mode value used to drive validation, filtering, and business behavior.'},
        carbonUnitCode: { type: 'string', required: false , description: 'Stores the carbon unit code used to classify, link, or resolve this record.'},
        receiverRef: { type: 'object', required: false , description: 'References the related receiver record used by this record.'},
        splitRules: { type: 'array', required: false , description: 'Lists the split rules associated with this record.'},
        provenanceRequired: { type: 'bool', required: true, default: true , description: 'Indicates whether provenance is required for this record.'},
        complianceReviewRequired: { type: 'bool', required: true, default: false , description: 'Indicates whether compliance review is required for this record.'},
        reversalAllowed: { type: 'bool', required: true, default: true , description: 'Indicates whether reversal allowed applies for this record.'},
        effectiveFrom: { type: 'date', required: false , description: 'Defines when this record becomes effective for business use.'},
        effectiveTo: { type: 'date', required: false , description: 'Defines when this record stops being effective for business use.'},
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'},
        metadata: { type: 'object', required: false , description: 'Stores additional structured metadata needed by extensions without changing the core schema contract.'}
    }, refSchema: {
        receiverRef: {"enabled":true,"moduleName":"profile","schemaName":"enterprise","type":"one","propertyName":"code"}
    } }),
    wasteCouponRedemptionSettlementPolicy: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'},
        name: { type: 'object', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'},
        assetTypeCode: { type: 'string', required: false , description: 'Stores the asset type code used to classify, link, or resolve this record.'},
        couponListingRef: { type: 'object', required: false , description: 'References the related coupon listing record used by this record.'},
        eligibleAssetStatuses: { type: 'array', required: false , description: 'Lists the eligible asset statuses associated with this record.'},
        rewardDebitMode: { type: 'string', required: true, enum: ['FIXED_AMOUNT', 'PROPORTIONAL_AMOUNT', 'FULL_ELIGIBLE_BALANCE', 'POLICY_RESOLVED'] , description: 'Selects the reward debit mode value used to drive validation, filtering, and business behavior.'},
        rewardReserveRequired: { type: 'bool', required: true, default: true , description: 'Indicates whether reward reserve is required for this record.'},
        carbonReceiverMode: { type: 'string', required: true, enum: ['ISSUER_ENTERPRISE', 'DEFAULT_ENTERPRISE', 'FIXED_ENTERPRISE', 'SPLIT_ENTERPRISE', 'NONE', 'POLICY_RESOLVED'] , description: 'Selects the carbon receiver mode value used to drive validation, filtering, and business behavior.'},
        carbonTransferQuantityMode: { type: 'string', required: true, enum: ['FULL_AVAILABLE', 'PROPORTIONAL_TO_REWARD_COST', 'FIXED', 'NONE', 'POLICY_RESOLVED'] , description: 'Selects the carbon transfer quantity mode value used to drive validation, filtering, and business behavior.'},
        defaultCarbonReceiverRef: { type: 'object', required: false , description: 'References the related default carbon receiver record used by this record.'},
        rewardSettlementPolicyCode: { type: 'string', required: false , description: 'Stores the reward settlement policy code used to classify, link, or resolve this record.'},
        carbonSettlementPolicyCode: { type: 'string', required: false , description: 'Stores the carbon settlement policy code used to classify, link, or resolve this record.'},
        entitlementMode: { type: 'string', required: true, enum: ['CUSTOMER_OWNED', 'ISSUER_OWNED', 'POLICY_RESOLVED'] , description: 'Selects the entitlement mode value used to drive validation, filtering, and business behavior.'},
        cancellationPolicyCode: { type: 'string', required: false , description: 'Stores the cancellation policy code used to classify, link, or resolve this record.'},
        expiryPolicyCode: { type: 'string', required: false , description: 'Stores the expiry policy code used to classify, link, or resolve this record.'},
        effectiveFrom: { type: 'date', required: false , description: 'Defines when this record becomes effective for business use.'},
        effectiveTo: { type: 'date', required: false , description: 'Defines when this record stops being effective for business use.'},
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'DEPRECATED', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'},
        metadata: { type: 'object', required: false , description: 'Stores additional structured metadata needed by extensions without changing the core schema contract.'}
    }, refSchema: {
        defaultCarbonReceiverRef: {"enabled":true,"moduleName":"profile","schemaName":"enterprise","type":"one","propertyName":"code"}
    } })
} };
