/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/**
 * @module copilotKnowledge/config/properties
 * @description Defines generated configurable defaults for copilotKnowledge.
 * @layer config
 * @owner generated
 * @override Project, environment, server, node, tenant, or customer layers may override these defaults through Nodics configuration layering.
 */
module.exports = {
  runtimePropertyGovernance: {
    publicMetadataLiterals: [
      {
        path: "copilot.knowledge.sourceRegistry.definitions.*.secretScanPolicy",
        values: ["REQUIRED"],
      },
    ],
  },
  copilot: {
    knowledge: {
      writerRecovery: { enabled: false, minimumPendingAgeMs: 300000 },
      legacyMigration: {
        enabled: false,
        erasureEnabled: false,
        plans: {},
        presentation: {
          eraseReview: "Review permanent removal",
          eraseConfirm: "Permanently remove legacy index",
          eraseInspect: "Inspect original removal",
          eraseImpact:
            "Permanently removes the dedicated retired index. Replacement sources and historical writer revocation must be verified. This cannot be undone by Copilot.",
          eraseDone:
            "The original legacy index removal is acknowledged and its absence is verified.",
          eraseUnknown:
            "Removal is unconfirmed. Do not repeat it. Inspect the original result or contact the index operator.",
          title: "Legacy knowledge indexes",
          review: "Review replacement",
          confirm: "Retire legacy writes",
          inspect: "Inspect original retirement",
          cancel: "Cancel",
          sources: "Verified replacement sources",
          impact:
            "This blocks writes to the entire dedicated legacy index. Existing legacy data is retained; physical cleanup is not complete.",
          done: "Legacy writes were retired after replacement verification. Retirement did not remove data; check the separate removal result for erasure status.",
          unknown:
            "The original retirement is unconfirmed. Do not repeat it. Inspect its original result or contact the index operator.",
          unavailable: "Original operation evidence is unavailable for this access context.",
          notStarted:
            "No original operation is recorded. This does not authorize retrying a previously sent request.",
        },
      },
      eventRefresh: { enabled: false, publishers: [] },
      workflowRefresh: {
        enabled: false,
        manualEnabled: false,
        assignments: [],
        actionAuthority: {
          connectionName: null,
          runtimeRole: null,
          timeoutMs: 10000,
        },
      },
      externalLogs: {
        enabled: false,
        maximumEvents: 100,
        maximumWindowMinutes: 60,
        sources: [],
        fields: [
          "timestamp",
          "severity",
          "message",
          "correlationId",
          "runtimeCode",
          "serviceCode",
          "categoryCode",
          "operation",
          "outcome",
          "revision",
        ],
      },
      groups: { enabled: false, definitions: [], assignments: [] },
      studio: {
        sourceScheduleDraftsEnabled: false,
        manualRefreshPresentation: {
          title: "Recorded source refresh",
          review: "Review refresh",
          confirm: "Confirm source refresh",
          start: "Start refresh",
          inspect: "Inspect original refresh",
          reference: "Process reference",
          definition: "Process definition",
          version: "Published version",
          acknowledged:
            "Refresh start acknowledged. Check execution history and current index readiness for completion.",
          unknown:
            "Refresh outcome is unconfirmed. Inspect the original reference before starting any further work.",
          evidence:
            "Original execution evidence is available in refresh history.",
          unavailable: "Refresh review or inspection is unavailable.",
        },
        maintenancePresentation: {
          title: "Maintenance receipts",
          load: "Load maintenance receipts",
          refresh: "Reload receipts",
          empty: "No maintenance receipts for this source",
          unavailable: "Maintenance receipts unavailable",
          evidence:
            "Authorization is not completion. A missing completion receipt remains unconfirmed; inspect current source readiness before any further action.",
          operation: "Operation",
          actor: "Administrator",
          revision: "Manifest revision",
          previous: "Previous page",
          next: "Next page",
          CLEANUP_AUTHORIZED: "Cleanup authorized",
          CLEANUP_COMPLETED: "Cleanup completion recorded",
          WRITER_RETIREMENT_AUTHORIZED: "Writer retirement authorized",
          WRITER_RETIREMENT_COMPLETED: "Writer retirement completion recorded",
        },
        recoveryPresentation: {
          title: "Pending refresh recovery",
          review: "Review pending refresh",
          confirm: "Retire pending refresh",
          cancel: "Cancel",
          started: "Writer started",
          chunks: "Expected chunks",
          notEligible: "This refresh is too recent to retire.",
          impact:
            "Retirement prevents this refresh from publishing. The last published knowledge is preserved. It does not stop the worker or delete its indexed data.",
          done: "Pending publication retired. Reload the source before any new refresh.",
          unknown:
            "Retirement outcome is unconfirmed. Reload the source and inspect maintenance evidence; do not repeat this command.",
          unavailable: "Pending refresh recovery is unavailable.",
        },
        cleanupPresentation: {
          title: "Obsolete index cleanup",
          review: "Review cleanup",
          confirm: "Confirm cleanup",
          cancel: "Cancel",
          eligible: "Published generations to remove",
          operatorOnly: "Generations requiring operator inspection",
          done: "Reviewed cleanup acknowledged. Reload the inventory for current status.",
          unknown:
            "Cleanup outcome is unconfirmed. Reload the inventory and review again before another attempt.",
          unavailable:
            "Cleanup review unavailable. Reload the inventory or contact the operator.",
        },
        maximumSources: 40,
        historyPresentation: {
          title: "Refresh executions",
          load: "Load execution history",
          refresh: "Reload history",
          empty: "No recorded attempts for this source and process",
          unavailable: "Execution history unavailable",
          definition: "Process definition",
          version: "Published version",
          instance: "Execution",
          started: "Started",
          completed: "Completed",
          currentPolicy: "Current source policy",
          previousPolicy: "Previous source policy",
          previous: "Previous page",
          next: "Next page",
          ready: "Awaiting claim",
          claimed: "In progress",
          done: "Completed",
          failed: "Failed",
          inspection: "Outcome requires inspection",
          recovery: "Process operator review required",
          evidence:
            "Recorded Process attempts across published versions; runs before attempt recording are not included",
        },
        presentation: {
          title: "Knowledge Studio",
          subtitle: "Authorized sources for this enterprise",
          search: "Find a source",
          refresh: "Refresh inventory",
          preview: "Preview ingestion",
          empty: "No sources available",
          source: "Source",
          version: "Configured revision",
          included: "Included paths",
          excluded: "Excluded paths",
          none: "None configured",
          enabled: "Enabled",
          disabled: "Disabled",
          ready: "Indexed",
          stale: "Index needs refresh",
          durableEvidence: "Published generation and index count verified",
          inspectionRequired:
            "A refresh outcome needs operator inspection before another refresh.",
          cleanupPending: "Obsolete generation cleanup is pending.",
          progress: "Acknowledged chunk writes",
          progressIdle: "Waiting for the next write",
          progressWriting: "Write awaiting acknowledgement",
          progressSealed: "Writes complete; publication verification pending",
          failed: "Refresh failed",
          unknown: "Index state not verified",
          prepared: "Preview ready",
          provenance: "Provenance",
          classification: "Classification",
          owner: "Owner",
          repository: "Repository",
          project: "Project",
          module: "Module",
          extensions: "File types",
          limited: "Showing a bounded source window",
          previewFailed: "Preview could not be completed",
          filesRead: "Files inspected",
          filesAccepted: "Files accepted",
          filesRejected: "Files rejected",
          chunksPrepared: "Chunks prepared",
          previewOnly: "Preview only; active index unchanged",
          indexSource: "Refresh source index",
          indexConfirm: "Confirm source refresh",
          indexDone: "Source refresh acknowledged",
          indexUnknown:
            "Refresh outcome unknown. Reload inventory before another attempt.",
          secretScan: "Secret inspection required",
          close: "Close",
          retry: "Retry",
          unavailable: "Knowledge Studio could not be loaded",
          collections: "Collections",
          loadCollections: "Load collections",
          collectionSearch: "Search records",
          queryRecords: "Search",
          liveData: "Live data",
          noRecords: "No matching records",
          previousPage: "Previous page",
          nextPage: "Next page",
          liveFailed: "Live data could not be loaded",
          notSelected: "Excluded",
          hierarchy: "Runtime partition",
          includedCollections: "Included collections",
          excludedCollections: "Excluded collections",
          groups: "Knowledge groups",
          allGroups: "All active groups",
          activeGroup: "Active",
          inactiveGroup: "Inactive",
        },
      },
      discoveryService: "DefaultDiscoveryQueryService",
      maximumEvidenceItems: 20,
      requireCitations: true,
      generationPublication: { enabled: false, incrementalEnabled: false },
      ingestion: {
        enabled: false,
        ingestOnStart: false,
        indexTenant: "default",
        startup: {
          sourceProject: null,
          serviceId: "copilot-knowledge-startup",
          locale: "en",
          environment: { $config: "context", name: "environmentCode" },
          failOnRejectedFiles: false,
          rejectionMessage: null,
          logSummary: false,
        },
        indexConfigurationCode: "copilotKnowledge",
        indexName: "discoveryDocumentProjection",
        maximumFilesPerSource: 5000,
        maximumFileBytes: 1048576,
        maximumSourceBytes: 52428800,
        chunkCharacters: 4000,
        chunkOverlapCharacters: 400,
        allowedExtensions: [
          ".md",
          ".mdx",
          ".txt",
          ".rst",
          ".adoc",
          ".js",
          ".mjs",
          ".cjs",
          ".jsx",
          ".ts",
          ".tsx",
          ".json",
          ".yaml",
          ".yml",
          ".css",
          ".scss",
          ".html",
          ".xml",
          ".sql",
          ".graphql",
          ".gql",
          ".sh",
        ],
        excludedSegments: [
          ".git",
          "node_modules",
          "coverage",
          "dist",
          "build",
          "temp",
          "llm/generated",
          "src/service/gen",
          "src/controller/gen",
          "src/facade/gen",
          "generated",
        ],
        requireSecretScan: true,
      },
      retrieval: {
        enabled: false,
        mode: "LEXICAL",
        indexConfigurationCode: "copilotKnowledge",
        defaultSize: 10,
        maximumSize: 20,
        maximumQueryCharacters: 2000,
        maximumExcerptCharacters: 4000,
        fields: ["payload.title", "payload.content", "payload.keywords"],
      },
      repositoryRoots: {
        framework: { $config: "path", base: "framework", relative: "" },
        project: { $config: "path", base: "project", relative: "" },
      },
      sourceRegistry: {
        templates: {
          employeeReadme: {
            sourceType: "README",
            classification: "INTERNAL",
            paths: ["README.md", "**/README.md"],
            allowedChannels: ["EMPLOYEE"],
            requiredPermissions: ["copilot.knowledge.internal.read"],
            secretScanPolicy: "REQUIRED",
          },
          employeeContracts: {
            sourceType: "AGENTS_CONTRACT",
            classification: "RESTRICTED",
            paths: ["AGENTS.md", "**/AGENTS.md", "**/llm/contracts/*.md"],
            allowedChannels: ["EMPLOYEE"],
            requiredPermissions: ["copilot.knowledge.restricted.read"],
            secretScanPolicy: "REQUIRED",
          },
          customerReadme: {
            sourceType: "CUSTOMER_PROJECT",
            classification: "CUSTOMER",
            paths: ["README.md", "**/README.md", "docs/**/*.md"],
            allowedChannels: ["EMPLOYEE"],
            requiredPermissions: ["copilot.knowledge.customer.read"],
            secretScanPolicy: "REQUIRED",
          },
          customerContracts: {
            sourceType: "CUSTOMER_PROJECT",
            classification: "CUSTOMER",
            paths: ["AGENTS.md", "**/AGENTS.md", "**/llm/contracts/*.md"],
            allowedChannels: ["EMPLOYEE"],
            requiredPermissions: ["copilot.knowledge.customer.read"],
            secretScanPolicy: "REQUIRED",
          },
          employeeSource: {
            sourceType: "SOURCE_CODE",
            classification: "RESTRICTED",
            allowedChannels: ["EMPLOYEE"],
            requiredPermissions: ["copilot.knowledge.restricted.read"],
            secretScanPolicy: "REQUIRED",
          },
        },
        enabled: true,
        failOnInvalidSource: true,
        allowedClassifications: [
          "PUBLIC",
          "CUSTOMER",
          "INTERNAL",
          "RESTRICTED",
        ],
        minimumClassificationByType: {
          PUBLISHED_DOCUMENTATION: "PUBLIC",
          INTERNAL_DOCUMENTATION: "INTERNAL",
          README: "INTERNAL",
          AGENTS_CONTRACT: "RESTRICTED",
          LLM_CONTRACT: "RESTRICTED",
          SOURCE_CODE: "RESTRICTED",
          CUSTOMER_PROJECT: "CUSTOMER",
          CURATED_MEMORY: "RESTRICTED",
          EXTERNAL_LOG: "RESTRICTED",
          DATABASE: "RESTRICTED",
        },
        definitions: [],
      },
    },
  },
};
