/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module promotion/src/interceptors/interceptors @description Separates Staged policy authoring from operational mutations. @layer interceptors @owner promotion */
module.exports = {
  couponSellerProofSave: {
    type: "schema",
    item: "coupon",
    trigger: "preSave",
    active: "true",
    index: -40,
    handler: "DefaultCouponSellerAuthorizationService.protectCoupon",
  },
  couponSellerProofUpdate: {
    type: "schema",
    item: "coupon",
    trigger: "preUpdate",
    active: "true",
    index: -40,
    handler: "DefaultCouponSellerAuthorizationService.protectCoupon",
  },
  couponSellerProofRemove: {
    type: "schema",
    item: "coupon",
    trigger: "preRemove",
    active: "true",
    index: -40,
    handler: "DefaultCouponSellerAuthorizationService.protectCoupon",
  },
  couponSellerConsentSave: {
    type: "schema",
    item: "promotion",
    trigger: "preSave",
    active: "true",
    index: -40,
    handler: "DefaultCouponSellerAuthorizationService.protect",
  },
  couponSellerConsentUpdate: {
    type: "schema",
    item: "promotion",
    trigger: "preUpdate",
    active: "true",
    index: -40,
    handler: "DefaultCouponSellerAuthorizationService.protect",
  },
  couponSellerConsentRemove: {
    type: "schema",
    item: "promotion",
    trigger: "preRemove",
    active: "true",
    index: -40,
    handler: "DefaultCouponSellerAuthorizationService.protectRemove",
  },
  promotionPublicationpreSave: {
    type: "schema",
    item: "promotion",
    trigger: "preSave",
    active: "true",
    index: -30,
    handler: "DefaultPromotionPublicationService.validateSourceAuthoring",
  },
  promotionPublicationpreUpdate: {
    type: "schema",
    item: "promotion",
    trigger: "preUpdate",
    active: "true",
    index: -30,
    handler: "DefaultPromotionPublicationService.validateSourceAuthoring",
  },
  promotionpreSave: {
    type: "schema",
    item: "promotion",
    trigger: "preSave",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.validatePolicyAuthoring",
  },
  promotionpreUpdate: {
    type: "schema",
    item: "promotion",
    trigger: "preUpdate",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.validatePolicyAuthoring",
  },
  couponBatchpreSave: {
    type: "schema",
    item: "couponBatch",
    trigger: "preSave",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  couponBatchpreUpdate: {
    type: "schema",
    item: "couponBatch",
    trigger: "preUpdate",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  couponBatchpreRemove: {
    type: "schema",
    item: "couponBatch",
    trigger: "preRemove",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  couponpreSave: {
    type: "schema",
    item: "coupon",
    trigger: "preSave",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  couponpreUpdate: {
    type: "schema",
    item: "coupon",
    trigger: "preUpdate",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  couponpreRemove: {
    type: "schema",
    item: "coupon",
    trigger: "preRemove",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  promotionBudgetLedgerpreSave: {
    type: "schema",
    item: "promotionBudgetLedger",
    trigger: "preSave",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  promotionBudgetLedgerpreUpdate: {
    type: "schema",
    item: "promotionBudgetLedger",
    trigger: "preUpdate",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  promotionBudgetLedgerpreRemove: {
    type: "schema",
    item: "promotionBudgetLedger",
    trigger: "preRemove",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  promotionRedemptionpreSave: {
    type: "schema",
    item: "promotionRedemption",
    trigger: "preSave",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  promotionRedemptionpreUpdate: {
    type: "schema",
    item: "promotionRedemption",
    trigger: "preUpdate",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  promotionRedemptionpreRemove: {
    type: "schema",
    item: "promotionRedemption",
    trigger: "preRemove",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  discountDecisionpreSave: {
    type: "schema",
    item: "discountDecision",
    trigger: "preSave",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  discountDecisionpreUpdate: {
    type: "schema",
    item: "discountDecision",
    trigger: "preUpdate",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
  discountDecisionpreRemove: {
    type: "schema",
    item: "discountDecision",
    trigger: "preRemove",
    active: "true",
    index: -20,
    handler: "DefaultPromotionOperationService.requireOperationalRuntime",
  },
};
