/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module shoppingList/src/schemas/schemas @description Defines customer-owned wishlist, compare, and save-for-later shopping list records. @layer schema @owner shoppingList */
module.exports = { shoppingList: {
    shoppingList: Object.assign({ super: 'base', model: true, schemaPolicies: ['customerOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, ownerId: { type: 'string', required: true , description: 'Identifies the principal or business owner responsible for this record.'}, listType: { type: 'string', required: true, enum: ['WISHLIST', 'COMPARE', 'SAVE_FOR_LATER'] , description: 'Classifies this record by list type for validation and business handling.'}, storeCode: { type: 'string', required: true , description: 'Stores the store code used to classify, link, or resolve this record.'}, locale: { type: 'string', required: true , description: 'Stores the locale code used for language, formatting, and regional behavior.'}, status: { type: 'string', required: true, enum: ['ACTIVE', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} } }),
    shoppingListEntry: Object.assign({ super: 'base', model: true, schemaPolicies: ['customerOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, ownerId: { type: 'string', required: true , description: 'Identifies the principal or business owner responsible for this record.'}, listCode: { type: 'string', required: true , description: 'Stores the list code used to classify, link, or resolve this record.'}, listType: { type: 'string', required: true, enum: ['WISHLIST', 'COMPARE', 'SAVE_FOR_LATER'] , description: 'Classifies this record by list type for validation and business handling.'}, productCode: { type: 'string', required: true , description: 'Stores the product code used to classify, link, or resolve this record.'}, variantCode: { type: 'string', required: false , description: 'Stores the variant code used to classify, link, or resolve this record.'}, status: { type: 'string', required: true, enum: ['ACTIVE', 'REMOVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} } })
} };
