/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module customerReview/src/schemas/schemas @description Defines review evidence, immutable versions, authenticity, moderation, responses, abuse, appeals, and CRES migration records. @layer schema @owner customerReview @override Later modules may add governed fields without weakening tenant, integrity, disclosure, or audit guarantees. */
const internal = policy => ({ super: 'base', model: true, schemaPolicies: [policy], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } });
module.exports = { customerReview: {
    customerReview: Object.assign(internal('customerOwned'), { definition: {
        tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: true }, targetType: { type: 'string', required: true }, targetCode: { type: 'string', required: true }, orderCode: { type: 'string', required: false }, orderEntryCode: { type: 'string', required: false },
        overallRating: { type: 'number', required: false }, dimensionRatings: { type: 'object', required: false }, title: { type: 'string', required: false }, body: { type: 'string', required: false }, advantages: { type: 'array', required: false }, disadvantages: { type: 'array', required: false }, recommendation: { type: 'bool', required: false }, structuredAnswers: { type: 'object', required: false }, mediaCodes: { type: 'array', required: false },
        site: { type: 'string', required: true }, locale: { type: 'string', required: true }, channel: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['DRAFT', 'SUBMITTED', 'PENDING_MODERATION', 'QUARANTINED', 'APPROVED', 'REJECTED', 'HIDDEN', 'WITHDRAWN', 'ARCHIVED'] }, moderationMode: { type: 'string', required: true, enum: ['PRE', 'POST', 'HYBRID'] },
        revision: { type: 'int', required: true, default: 0 }, submittedAt: { type: 'date', required: false }, withdrawnAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true }
    } }),
    customerReviewVersion: Object.assign(internal('operational'), { definition: {
        tenant: { type: 'string', required: true }, reviewCode: { type: 'string', required: true }, version: { type: 'int', required: true }, title: { type: 'string', required: false }, body: { type: 'string', required: false }, overallRating: { type: 'number', required: false }, dimensionRatings: { type: 'object', required: false }, mediaCodes: { type: 'array', required: false },
        changeReason: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['CURRENT', 'SUPERSEDED', 'WITHDRAWN'] }, contentHash: { type: 'string', required: true }, correlationId: { type: 'string', required: true }, createdAt: { type: 'date', required: true }
    } }),
    customerReviewAuthenticityEvidence: Object.assign(internal('operational'), { definition: {
        tenant: { type: 'string', required: true }, reviewCode: { type: 'string', required: true }, interactionType: { type: 'string', required: true, enum: ['PURCHASE', 'EXPERIENCE', 'GUEST_VERIFICATION', 'IMPORT', 'NONE'] }, verificationStatus: { type: 'string', required: true, enum: ['PENDING', 'VERIFIED', 'UNVERIFIED', 'FAILED'] }, sourceModule: { type: 'string', required: false }, sourceRecordCode: { type: 'string', required: false },
        incentiveType: { type: 'string', required: false }, sentimentConditioned: { type: 'bool', required: true, default: false }, samplingDisclosure: { type: 'string', required: false }, materialRelationship: { type: 'string', required: false }, aiAssistance: { type: 'string', required: false }, provenance: { type: 'object', required: true }, policyVersion: { type: 'string', required: true }, verifiedAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true }
    } }),
    customerReviewModeration: Object.assign(internal('operational'), { definition: {
        tenant: { type: 'string', required: true }, reviewCode: { type: 'string', required: true }, reviewVersion: { type: 'int', required: true }, action: { type: 'string', required: true, enum: ['SUBMIT', 'APPROVE', 'REJECT', 'FLAG', 'QUARANTINE', 'MARK_SPAM', 'HIDE', 'RESTORE', 'ARCHIVE', 'WITHDRAW', 'REQUEST_CORRECTION', 'ESCALATE'] }, fromStatus: { type: 'string', required: true }, toStatus: { type: 'string', required: true },
        reasonCode: { type: 'string', required: false }, policyViolation: { type: 'bool', required: true, default: false }, sentiment: { type: 'string', required: false }, internalNotes: { type: 'string', required: false }, customerReason: { type: 'string', required: false }, escalationType: { type: 'string', required: false }, actorId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, correlationId: { type: 'string', required: true }, occurredAt: { type: 'date', required: true }
    } }),
    customerReviewResponse: Object.assign(internal('operational'), { definition: {
        tenant: { type: 'string', required: true }, reviewCode: { type: 'string', required: true }, version: { type: 'int', required: true }, body: { type: 'string', required: true }, authorId: { type: 'string', required: true }, teamCode: { type: 'string', required: false }, status: { type: 'string', required: true, enum: ['DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'PUBLISHED', 'HIDDEN', 'WITHDRAWN', 'SUPERSEDED'] }, approvedBy: { type: 'string', required: false }, approvedAt: { type: 'date', required: false }, publishedAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true }
    } }),
    customerReviewAbuseReport: Object.assign(internal('customerOwned'), { definition: {
        tenant: { type: 'string', required: true }, reviewCode: { type: 'string', required: true }, reporterId: { type: 'string', required: true }, reasonCode: { type: 'string', required: true }, comment: { type: 'string', required: false }, evidence: { type: 'object', required: false }, status: { type: 'string', required: true, enum: ['OPEN', 'UNDER_INVESTIGATION', 'ACTIONED', 'DISMISSED'] }, resolutionCode: { type: 'string', required: false }, resolvedBy: { type: 'string', required: false }, resolvedAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true }
    } }),
    customerReviewAppeal: Object.assign(internal('customerOwned'), { definition: {
        tenant: { type: 'string', required: true }, reviewCode: { type: 'string', required: true }, ownerId: { type: 'string', required: true }, moderationCode: { type: 'string', required: true }, reason: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['OPEN', 'UNDER_REVIEW', 'UPHELD', 'OVERTURNED', 'CLOSED'] }, decisionReason: { type: 'string', required: false }, decidedBy: { type: 'string', required: false }, decidedAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true }
    } }),
    customerReviewMigration: Object.assign(internal('operational'), { definition: {
        tenant: { type: 'string', required: true }, legacyModule: { type: 'string', required: true }, legacySchema: { type: 'string', required: true }, legacyCode: { type: 'string', required: true }, targetSchema: { type: 'string', required: true }, targetCode: { type: 'string', required: false }, sourceHash: { type: 'string', required: true }, strategy: { type: 'string', required: true, enum: ['CUTOVER', 'DRY_RUN'] }, status: { type: 'string', required: true, enum: ['PLANNED', 'MIGRATED', 'SKIPPED', 'FAILED', 'ROLLED_BACK', 'RECONCILED'] }, mappingVersion: { type: 'string', required: true }, errors: { type: 'array', required: false }, migratedAt: { type: 'date', required: false }, rolledBackAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true }
    } })
    , customerReviewProjection: Object.assign(internal('operational'), { definition: {
        tenant: { type: 'string', required: true }, reviewCode: { type: 'string', required: true }, reviewVersion: { type: 'int', required: true }, targetType: { type: 'string', required: true }, targetCode: { type: 'string', required: true }, variantCode: { type: 'string', required: false }, overallRating: { type: 'number', required: false }, dimensionRatings: { type: 'object', required: false }, title: { type: 'string', required: false }, body: { type: 'string', required: false }, recommendation: { type: 'bool', required: false }, media: { type: 'array', required: false }, businessResponse: { type: 'object', required: false }, authenticity: { type: 'object', required: true }, disclosures: { type: 'array', required: false }, helpfulCount: { type: 'int', required: true, default: 0 }, unhelpfulCount: { type: 'int', required: true, default: 0 }, site: { type: 'string', required: true }, locale: { type: 'string', required: true }, channel: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['PUBLISHED', 'HIDDEN', 'WITHDRAWN', 'ANONYMIZED'] }, publishedAt: { type: 'date', required: false }, hiddenAt: { type: 'date', required: false }, policyVersion: { type: 'string', required: true }, sourceHash: { type: 'string', required: true }, correlationId: { type: 'string', required: true }
    } })
    , customerReviewAggregate: Object.assign(internal('operational'), { definition: {
        tenant: { type: 'string', required: true }, targetType: { type: 'string', required: true }, targetCode: { type: 'string', required: true }, variantCode: { type: 'string', required: false }, site: { type: 'string', required: true }, locale: { type: 'string', required: false }, count: { type: 'int', required: true }, sum: { type: 'number', required: true }, average: { type: 'number', required: true }, distribution: { type: 'object', required: true }, dimensions: { type: 'object', required: true }, verifiedCount: { type: 'int', required: true }, unverifiedCount: { type: 'int', required: true }, policyVersion: { type: 'string', required: true }, calculationVersion: { type: 'string', required: true }, sourceHash: { type: 'string', required: true }, calculatedAt: { type: 'date', required: true }, status: { type: 'string', required: true, enum: ['CURRENT', 'STALE', 'REBUILDING', 'DRIFTED'] }, correlationId: { type: 'string', required: true }
    } })
    , customerReviewHelpfulness: Object.assign(internal('customerOwned'), { definition: {
        tenant: { type: 'string', required: true }, reviewCode: { type: 'string', required: true }, ownerId: { type: 'string', required: true }, helpful: { type: 'bool', required: true }, status: { type: 'string', required: true, enum: ['ACTIVE', 'WITHDRAWN'] }, revision: { type: 'int', required: true, default: 0 }, correlationId: { type: 'string', required: true }
    } })
    , customerReviewRequest: Object.assign(internal('customerOwned'), { definition: {
        tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: true }, eligibilityType: { type: 'string', required: true, enum: ['PURCHASE', 'SERVICE', 'EXPERIENCE'] }, sourceModule: { type: 'string', required: true }, sourceRecordCode: { type: 'string', required: true }, targetCodes: { type: 'array', required: true }, channel: { type: 'string', required: true, enum: ['EMAIL', 'SMS', 'ACCOUNT', 'QR', 'IN_APP'] }, status: { type: 'string', required: true, enum: ['PLANNED', 'OFFERED', 'DELIVERED', 'OPENED', 'STARTED', 'COMPLETED', 'EXPIRED', 'SUPPRESSED', 'FAILED'] }, eligibleAt: { type: 'date', required: true }, offeredAt: { type: 'date', required: false }, expiresAt: { type: 'date', required: true }, reminderCount: { type: 'int', required: true, default: 0 }, nextReminderAt: { type: 'date', required: false }, suppressionReason: { type: 'string', required: false }, policyVersion: { type: 'string', required: true }, idempotencyKey: { type: 'string', required: true }, correlationId: { type: 'string', required: true }
    } })
    , customerReviewSession: Object.assign(internal('customerOwned'), { definition: {
        tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: true }, requestCode: { type: 'string', required: true }, targetCodes: { type: 'array', required: true }, completedTargetCodes: { type: 'array', required: false }, status: { type: 'string', required: true, enum: ['OPEN', 'IN_PROGRESS', 'COMPLETED', 'EXPIRED', 'ABANDONED'] }, startedAt: { type: 'date', required: false }, completedAt: { type: 'date', required: false }, expiresAt: { type: 'date', required: true }, revision: { type: 'int', required: true, default: 0 }, correlationId: { type: 'string', required: true }
    } })
    , customerReviewAcquisitionEvent: Object.assign(internal('operational'), { definition: {
        tenant: { type: 'string', required: true }, requestCode: { type: 'string', required: true }, sessionCode: { type: 'string', required: false }, eventType: { type: 'string', required: true, enum: ['ELIGIBLE', 'OFFERED', 'DELIVERED', 'OPENED', 'STARTED', 'COMPLETED', 'EXPIRED', 'SUPPRESSED', 'FAILED'] }, channel: { type: 'string', required: false }, providerCode: { type: 'string', required: false }, providerReference: { type: 'string', required: false }, occurredAt: { type: 'date', required: true }, evidence: { type: 'object', required: false }, correlationId: { type: 'string', required: true }
    } })
    , customerReviewSyndication: Object.assign(internal('operational'), { definition: {
        tenant: { type: 'string', required: true }, direction: { type: 'string', required: true, enum: ['IMPORT', 'EXPORT'] }, providerCode: { type: 'string', required: true }, externalReviewId: { type: 'string', required: true }, externalTargetId: { type: 'string', required: true }, targetType: { type: 'string', required: true }, targetCode: { type: 'string', required: true }, reviewCode: { type: 'string', required: false }, originUrl: { type: 'string', required: false }, licenseCode: { type: 'string', required: true }, disclosure: { type: 'string', required: true }, sourceHash: { type: 'string', required: true }, mappingVersion: { type: 'string', required: true }, moderationEvidence: { type: 'object', required: true }, status: { type: 'string', required: true, enum: ['RECEIVED', 'VALIDATED', 'QUARANTINED', 'IMPORTED', 'EXPORTED', 'FAILED', 'RECONCILED', 'WITHDRAWN'] }, errors: { type: 'array', required: false }, lastReconciledAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true }
    } })
} };
