/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module contactSubmission/src/schemas/schemas @description Defines internal contact request, correspondence, attempt, resolution, and handoff records. @layer schema @owner contactSubmission @override Later modules may add governed fields while preserving tenant, ownership, audit, and provider boundaries. */
module.exports = { contactSubmission: {
    contactRequest: Object.assign({ super: 'base', model: true, schemaPolicies: ['customerOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, engagementSubmissionCode: { type: 'string', required: true , description: 'Stores the engagement submission code used to classify, link, or resolve this record.'}, ownerId: { type: 'string', required: true , description: 'Identifies the principal or business owner responsible for this record.'},
        type: { type: 'string', required: true , description: 'Stores the type value used by this record.'}, reasonCode: { type: 'string', required: false , description: 'Stores the reason code used to classify, link, or resolve this record.'}, subject: { type: 'string', required: true , description: 'Stores the subject value used by this record.'}, message: { type: 'string', required: true , description: 'Stores the message value used by this record.'},
        contactEmail: { type: 'string', required: true , description: 'Stores the contact email value used by this record.'}, contactPhone: { type: 'string', required: false , description: 'Stores the contact phone value used by this record.'}, preferredChannel: { type: 'string', required: false , description: 'Stores the preferred channel value used by this record.'},
        verificationStatus: { type: 'string', required: true, enum: ['NOT_REQUIRED', 'PENDING', 'VERIFIED', 'FAILED', 'EXPIRED'] , description: 'Selects the verification status value used to drive validation, filtering, and business behavior.'}, status: { type: 'string', required: true, enum: ['SUBMITTED', 'VERIFICATION_PENDING', 'OPEN', 'IN_PROGRESS', 'WAITING_CUSTOMER', 'WAITING_INTERNAL', 'RESOLVED', 'CLOSED', 'REJECTED', 'SPAM', 'DUPLICATE', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        queueCode: { type: 'string', required: true , description: 'Stores the queue code used to classify, link, or resolve this record.'}, teamCode: { type: 'string', required: false , description: 'Stores the team code used to classify, link, or resolve this record.'}, priorityCode: { type: 'string', required: true , description: 'Stores the priority code used to classify, link, or resolve this record.'}, dueAt: { type: 'date', required: false , description: 'Records when the due event or value applies.'},
        processInstanceCode: { type: 'string', required: false , description: 'Stores the process instance code used to classify, link, or resolve this record.'}, revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}, retentionPolicyCode: { type: 'string', required: true , description: 'Stores the retention policy code used to classify, link, or resolve this record.'},
        correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}, submittedAt: { type: 'date', required: true , description: 'Records when the submitted event or value applies.'}, resolvedAt: { type: 'date', required: false , description: 'Records when the resolved event or value applies.'}, closedAt: { type: 'date', required: false , description: 'Records when the closed event or value applies.'}
    } }),
    contactCorrespondence: Object.assign({ super: 'base', model: true, schemaPolicies: ['customerOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, contactRequestCode: { type: 'string', required: true , description: 'Stores the contact request code used to classify, link, or resolve this record.'}, ownerId: { type: 'string', required: true , description: 'Identifies the principal or business owner responsible for this record.'}, direction: { type: 'string', required: true, enum: ['INBOUND', 'OUTBOUND'] , description: 'Selects the direction value used to drive validation, filtering, and business behavior.'},
        visibility: { type: 'string', required: true, enum: ['CUSTOMER', 'INTERNAL'] , description: 'Selects the visibility value used to drive validation, filtering, and business behavior.'}, channel: { type: 'string', required: true , description: 'Stores the channel value used by this record.'}, body: { type: 'string', required: true , description: 'Stores the body value used by this record.'},
        authorId: { type: 'string', required: false , description: 'Stores the author identifier used to correlate this record.'}, deliveryReference: { type: 'string', required: false , description: 'Stores the delivery reference value used by this record.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}, occurredAt: { type: 'date', required: true , description: 'Records when the occurred event or value applies.'}
    } }),
    contactAttempt: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, contactRequestCode: { type: 'string', required: true , description: 'Stores the contact request code used to classify, link, or resolve this record.'}, channel: { type: 'string', required: true , description: 'Stores the channel value used by this record.'}, outcome: { type: 'string', required: true , description: 'Stores the outcome value used by this record.'},
        reasonCode: { type: 'string', required: false , description: 'Stores the reason code used to classify, link, or resolve this record.'}, actorId: { type: 'string', required: false , description: 'Stores the actor identifier used to correlate this record.'}, providerReference: { type: 'string', required: false , description: 'Stores provider-specific reference data needed to resolve this record.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}, attemptedAt: { type: 'date', required: true , description: 'Records when the attempted event or value applies.'}
    } }),
    contactResolution: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, contactRequestCode: { type: 'string', required: true , description: 'Stores the contact request code used to classify, link, or resolve this record.'}, resolutionCode: { type: 'string', required: true , description: 'Stores the resolution code used to classify, link, or resolve this record.'}, summary: { type: 'string', required: true , description: 'Stores the summary value used by this record.'},
        customerVisibleSummary: { type: 'string', required: false , description: 'Summarizes customer visible information for quick review and administration.'}, resolvedBy: { type: 'string', required: true , description: 'Stores the resolved by value used by this record.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}, resolvedAt: { type: 'date', required: true , description: 'Records when the resolved event or value applies.'}
    } }),
    contactHandoff: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, contactRequestCode: { type: 'string', required: true , description: 'Stores the contact request code used to classify, link, or resolve this record.'}, targetType: { type: 'string', required: true, enum: ['PROCESS', 'CRM', 'HELPDESK', 'CALENDAR', 'COMMUNICATION'] , description: 'Classifies this record by target type for validation and business handling.'},
        provider: { type: 'string', required: false , description: 'Stores the provider value used by this record.'}, externalReference: { type: 'string', required: false , description: 'Stores the external reference value used by this record.'}, status: { type: 'string', required: true, enum: ['PENDING', 'IN_PROGRESS', 'SUCCEEDED', 'FAILED', 'RETRY_PENDING', 'DEAD_LETTER', 'RECONCILED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        attempts: { type: 'int', required: true, default: 0 , description: 'Stores the numeric attempts used by this record.'}, revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}, nextRetryAt: { type: 'date', required: false , description: 'Records when the next retry event or value applies.'}, lastAttemptAt: { type: 'date', required: false , description: 'Records when the last attempt event or value applies.'}, completedAt: { type: 'date', required: false , description: 'Records when the completed event or value applies.'},
        leaseOwner: { type: 'string', required: false , description: 'Stores the lease owner value used by this record.'}, leaseExpiresAt: { type: 'date', required: false , description: 'Records when the lease expires event or value applies.'}, lastErrorCode: { type: 'string', required: false , description: 'Stores the last error code used to classify, link, or resolve this record.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}, updatedAt: { type: 'date', required: true , description: 'Records when the updated event or value applies.'}
    } }),
    contactVerification: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, contactRequestCode: { type: 'string', required: true , description: 'Stores the contact request code used to classify, link, or resolve this record.'}, challengeHash: { type: 'string', required: true , description: 'Stores the challenge hash value used by this record.'}, status: { type: 'string', required: true, enum: ['PENDING', 'VERIFIED', 'FAILED', 'EXPIRED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        attempts: { type: 'int', required: true, default: 0 , description: 'Stores the numeric attempts used by this record.'}, expiresAt: { type: 'date', required: true , description: 'Records when the expires event or value applies.'}, verifiedAt: { type: 'date', required: false , description: 'Records when the verified event or value applies.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}
    } })
} };
