/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
'use strict';
/** @module commsSchema/src/schemas/schemas @description Declares provider-neutral Communication source schemas; all generated generic routes remain disabled. @layer schema @owner commsSchema @override Later schema overlays may add compatible fields without moving domain or provider authority. */
module.exports = { commsSchema: {
    commsTemplate: { super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, purpose: { type: 'string', required: true , description: 'Stores the purpose value used by this record.'}, channels: { type: 'array', required: true , description: 'Lists the channels associated with this record.'}, declaredVariables: { type: 'array', required: true , description: 'Lists the declared variables associated with this record.'}, currentVersion: { type: 'int', required: true , description: 'Stores the numeric current version used by this record.'}, status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'RETIRED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'} } },
    commsTemplateVersion: { super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, templateCode: { type: 'string', required: true , description: 'Stores the template code used to classify, link, or resolve this record.'}, version: { type: 'int', required: true , description: 'Stores the numeric version used by this record.'}, locale: { type: 'string', required: true , description: 'Stores the locale code used for language, formatting, and regional behavior.'}, channel: { type: 'string', required: true , description: 'Stores the channel value used by this record.'}, subjectTemplate: { type: 'string', required: false , description: 'Stores the subject template value used by this record.'}, bodyTemplate: { type: 'string', required: true , description: 'Stores the body template value used by this record.'}, checksum: { type: 'string', required: true , description: 'Stores the checksum value used by this record.'}, status: { type: 'string', required: true, enum: ['VALIDATED', 'ACTIVE', 'RETIRED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, validatedAt: { type: 'date', required: true , description: 'Records when the validated event or value applies.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'} } },
    commsIntent: { super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, sourceModule: { type: 'string', required: true , description: 'Stores the source module value used by this record.'}, sourceType: { type: 'string', required: true , description: 'Classifies this record by source type for validation and business handling.'}, sourceCode: { type: 'string', required: true , description: 'Stores the source code used to classify, link, or resolve this record.'}, templateCode: { type: 'string', required: true , description: 'Stores the template code used to classify, link, or resolve this record.'}, templateVersion: { type: 'int', required: true , description: 'Stores the numeric template version used by this record.'}, recipientId: { type: 'string', required: true , description: 'Stores the recipient identifier used to correlate this record.'}, recipientAddressReference: { type: 'string', required: true , description: 'Stores the recipient address reference value used by this record.'}, purpose: { type: 'string', required: true , description: 'Stores the purpose value used by this record.'}, channel: { type: 'string', required: true , description: 'Stores the channel value used by this record.'}, locale: { type: 'string', required: true , description: 'Stores the locale code used for language, formatting, and regional behavior.'}, variablesHash: { type: 'string', required: true , description: 'Stores the variables hash value used by this record.'}, idempotencyKey: { type: 'string', required: true , description: 'Stores the idempotency key value used by this record.'}, status: { type: 'string', required: true, enum: ['ACCEPTED', 'SUPPRESSED', 'QUEUED', 'DELIVERING', 'DELIVERED', 'FAILED', 'CANCELLED', 'RETRY_PENDING', 'UNCERTAIN', 'DEAD_LETTER'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, createdAt: { type: 'date', required: true , description: 'Records when the created event or value applies.'}, expiresAt: { type: 'date', required: false , description: 'Records when the expires event or value applies.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'} } },
    commsDeliveryAttempt: { super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, intentCode: { type: 'string', required: true , description: 'Stores the intent code used to classify, link, or resolve this record.'}, providerCode: { type: 'string', required: true , description: 'Stores the provider code used to classify, link, or resolve this record.'}, channel: { type: 'string', required: true , description: 'Stores the channel value used by this record.'}, attempt: { type: 'int', required: true , description: 'Stores the numeric attempt used by this record.'}, status: { type: 'string', required: true, enum: ['PENDING', 'ACCEPTED', 'DELIVERED', 'FAILED', 'RETRY_PENDING', 'DEAD_LETTER', 'UNCERTAIN', 'SUPPRESSED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, providerReference: { type: 'string', required: false , description: 'Stores provider-specific reference data needed to resolve this record.'}, responseCode: { type: 'string', required: false , description: 'Stores the response code used to classify, link, or resolve this record.'}, nextAttemptAt: { type: 'date', required: false , description: 'Records when the next attempt event or value applies.'}, attemptedAt: { type: 'date', required: true , description: 'Records when the attempted event or value applies.'}, deliveredAt: { type: 'date', required: false , description: 'Records when the delivered event or value applies.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'} } },
    commsSuppression: { super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, recipientId: { type: 'string', required: true , description: 'Stores the recipient identifier used to correlate this record.'}, purpose: { type: 'string', required: true , description: 'Stores the purpose value used by this record.'}, channel: { type: 'string', required: true , description: 'Stores the channel value used by this record.'}, reasonCode: { type: 'string', required: true , description: 'Stores the reason code used to classify, link, or resolve this record.'}, source: { type: 'string', required: true , description: 'Stores the source value used by this record.'}, activeFrom: { type: 'date', required: true , description: 'Records when the active from event or value applies.'}, activeUntil: { type: 'date', required: false , description: 'Records when the active until event or value applies.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'} } },
    commsInboxMessage: { super: 'base', model: true, schemaPolicies: ['customerOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, recipientId: { type: 'string', required: true , description: 'Stores the recipient identifier used to correlate this record.'}, intentCode: { type: 'string', required: true , description: 'Stores the intent code used to classify, link, or resolve this record.'}, title: { type: 'string', required: true , description: 'Stores the title value used by this record.'}, body: { type: 'string', required: true , description: 'Stores the body value used by this record.'}, actionReferences: { type: 'array', required: false , description: 'Lists the action references associated with this record.'}, status: { type: 'string', required: true, enum: ['UNREAD', 'READ', 'ARCHIVED', 'EXPIRED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, createdAt: { type: 'date', required: true , description: 'Records when the created event or value applies.'}, readAt: { type: 'date', required: false , description: 'Records when the read event or value applies.'}, expiresAt: { type: 'date', required: false , description: 'Records when the expires event or value applies.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'} } },
    commsVerificationChallenge: { super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, purpose: { type: 'string', required: true , description: 'Stores the purpose value used by this record.'}, subjectReference: { type: 'string', required: true , description: 'Stores the subject reference value used by this record.'}, channel: { type: 'string', required: true , description: 'Stores the channel value used by this record.'}, destinationHash: { type: 'string', required: true , description: 'Stores the destination hash value used by this record.'}, secretHash: { type: 'string', required: true , description: 'Stores the secret hash value used by this record.'}, attempt: { type: 'int', required: true , description: 'Stores the numeric attempt used by this record.'}, maximumAttempts: { type: 'int', required: true , description: 'Stores the numeric maximum attempts used by this record.'}, status: { type: 'string', required: true, enum: ['PENDING', 'DELIVERED', 'VERIFIED', 'EXPIRED', 'LOCKED', 'CANCELLED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, expiresAt: { type: 'date', required: true , description: 'Records when the expires event or value applies.'}, verifiedAt: { type: 'date', required: false , description: 'Records when the verified event or value applies.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'} } }
} };

// Private retry material and managed compare-and-set claims belong to Communication storage.
Object.assign(module.exports.commsSchema.commsIntent, {backoffice:{enabled:false,concurrency:{managed:true,field:'revision'}}});
Object.assign(module.exports.commsSchema.commsIntent.definition, {
 revision:{type:'int',default:0,required:true,description:'Managed optimistic revision for delivery claims.'},
 reconciliation:{type:'array',description:'Audited explicit operator decisions for uncertain deliveries; a resend requires a separate retry.'},
 commandHash:{type:'string',description:'Immutable command fingerprint that detects idempotency collisions.'},
 renderedContent:{type:'object',description:'Private immutable rendered message used for durable retry.'},
 attempt:{type:'int',default:0,description:'Number of claimed delivery attempts.'},
 leaseExpiresAt:{type:'date',description:'Expiry after which an interrupted external send becomes uncertain.'},
 nextAttemptAt:{type:'date',description:'Earliest permitted time for a known retryable failure.'},
 providerReference:{type:'string',description:'Provider acceptance reference without recipient or message content.'}
});
