/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
'use strict';
/** @module commsSchema/src/schemas/schemas @description Declares provider-neutral Communication source schemas; all generated generic routes remain disabled. @layer schema @owner commsSchema @override Later schema overlays may add compatible fields without moving domain or provider authority. */
module.exports = { commsSchema: {
    commsTemplate: { super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true }, code: { type: 'string', required: true }, purpose: { type: 'string', required: true }, channels: { type: 'array', required: true }, declaredVariables: { type: 'array', required: true }, currentVersion: { type: 'int', required: true }, status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'RETIRED'] }, correlationId: { type: 'string', required: true } } },
    commsTemplateVersion: { super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true }, templateCode: { type: 'string', required: true }, version: { type: 'int', required: true }, locale: { type: 'string', required: true }, channel: { type: 'string', required: true }, subjectTemplate: { type: 'string', required: false }, bodyTemplate: { type: 'string', required: true }, checksum: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['VALIDATED', 'ACTIVE', 'RETIRED'] }, validatedAt: { type: 'date', required: true }, correlationId: { type: 'string', required: true } } },
    commsIntent: { super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true }, sourceModule: { type: 'string', required: true }, sourceType: { type: 'string', required: true }, sourceCode: { type: 'string', required: true }, templateCode: { type: 'string', required: true }, templateVersion: { type: 'int', required: true }, recipientId: { type: 'string', required: true }, recipientAddressReference: { type: 'string', required: true }, purpose: { type: 'string', required: true }, channel: { type: 'string', required: true }, locale: { type: 'string', required: true }, variablesHash: { type: 'string', required: true }, idempotencyKey: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['ACCEPTED', 'SUPPRESSED', 'QUEUED', 'DELIVERED', 'FAILED', 'CANCELLED'] }, createdAt: { type: 'date', required: true }, expiresAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true } } },
    commsDeliveryAttempt: { super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true }, intentCode: { type: 'string', required: true }, providerCode: { type: 'string', required: true }, channel: { type: 'string', required: true }, attempt: { type: 'int', required: true }, status: { type: 'string', required: true, enum: ['PENDING', 'ACCEPTED', 'DELIVERED', 'FAILED', 'RETRY_PENDING', 'DEAD_LETTER'] }, providerReference: { type: 'string', required: false }, responseCode: { type: 'string', required: false }, nextAttemptAt: { type: 'date', required: false }, attemptedAt: { type: 'date', required: true }, deliveredAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true } } },
    commsSuppression: { super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true }, recipientId: { type: 'string', required: true }, purpose: { type: 'string', required: true }, channel: { type: 'string', required: true }, reasonCode: { type: 'string', required: true }, source: { type: 'string', required: true }, activeFrom: { type: 'date', required: true }, activeUntil: { type: 'date', required: false }, correlationId: { type: 'string', required: true } } },
    commsInboxMessage: { super: 'base', model: true, schemaPolicies: ['customerOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true }, recipientId: { type: 'string', required: true }, intentCode: { type: 'string', required: true }, title: { type: 'string', required: true }, body: { type: 'string', required: true }, actionReferences: { type: 'array', required: false }, status: { type: 'string', required: true, enum: ['UNREAD', 'READ', 'ARCHIVED', 'EXPIRED'] }, createdAt: { type: 'date', required: true }, readAt: { type: 'date', required: false }, expiresAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true } } },
    commsVerificationChallenge: { super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false }, definition: { tenant: { type: 'string', required: true }, purpose: { type: 'string', required: true }, subjectReference: { type: 'string', required: true }, channel: { type: 'string', required: true }, destinationHash: { type: 'string', required: true }, secretHash: { type: 'string', required: true }, attempt: { type: 'int', required: true }, maximumAttempts: { type: 'int', required: true }, status: { type: 'string', required: true, enum: ['PENDING', 'DELIVERED', 'VERIFIED', 'EXPIRED', 'LOCKED', 'CANCELLED'] }, expiresAt: { type: 'date', required: true }, verifiedAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true } } }
} };
