/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module copilotProvider/config/properties @description Defines provider-neutral activation, adapter selection, profiles, limits, fallback, and diagnostics policy. @layer config @owner copilotProvider @override Later layers may activate and switch adapters without changing source. */
module.exports = {
    copilot: {
        providers: {
            enabled: false,
            healthPresentation: {
                title: 'Provider connection',
                check: 'Check provider connection',
                UP: 'The configured provider responded and the selected model is available.',
                DEGRADED: 'The provider responded but the selected model is not ready. Check the installed model and configuration.',
                DOWN: 'The provider could not be verified. Check the service, permitted network path and timeout, then run a new check.',
                NOT_CONFIGURED: 'The provider configuration is incomplete or disabled. Review its effective configuration.',
                UNSUPPORTED: 'This adapter does not support a connection-only check.'
            },
            contractVersion: 1,
            default: {
                adapter: 'mock',
                fallbackAdapters: [],
                profile: 'conversation',
                timeoutMs: 30000,
                maximumRetries: 2,
                retryDelayMs: 250,
                maximumRequestBytes: 262144,
                maximumResponseBytes: 1048576,
                maximumMessages: 64,
                maximumToolCalls: 8,
                streaming: true,
                failClosed: true,
            },
            profiles: {
                conversation: {
                    temperature: 0.2,
                    topP: 0.9,
                    maximumOutputTokens: 2048,
                    structuredOutput: false,
                },
                structuredTool: {
                    temperature: 0,
                    topP: 0.9,
                    maximumOutputTokens: 2048,
                    structuredOutput: true,
                },
                evaluation: {
                    temperature: 0,
                    topP: 1,
                    maximumOutputTokens: 1024,
                    structuredOutput: true,
                },
            },
            adapters: {},
            accounting: {
                historyPeriods: 12,
                enabled: false,
                period: 'MONTH',
                timezone: 'UTC',
                tenantLimit: 0,
                enterprises: [],
                warningPercentages: [80, 95],
                maximumEntries: 5000,
                maximumAttempts: 8,
                reconciliation: { enabled: false },
                budgetPresentation: {
                    title: 'Current-period allocations',
                    back: 'Back to usage',
                    refresh: 'Refresh allocations',
                    periodOnly:
                        'Changes apply to this period only. Deployment defaults return at the next reset.',
                    enterprise: 'Enterprise pool',
                    employee: 'Employee',
                    limit: 'Assigned limit',
                    ceiling: 'Maximum permitted',
                    consumed: 'Consumed',
                    reserved: 'Reserved',
                    edit: 'Edit allocation',
                    reason: 'Reason for change',
                    preview: 'Review change',
                    confirm: 'Confirm allocation',
                    cancel: 'Cancel',
                    review: 'Review allocation change',
                    before: 'Current limit',
                    after: 'New limit',
                    committed: 'Consumed and reserved',
                    belowCommitted:
                        'This limit is below current consumption and reservations. Existing usage is retained; further model calls may be blocked.',
                    saveUnknown:
                        'The change could not be confirmed. Refresh allocations and check change history before submitting another change.',
                    previewFailed:
                        'The allocation could not be reviewed. Refresh allocations and check the current limits.',
                    history: 'Allocation history',
                    actor: 'Changed by',
                    changed: 'Changed at',
                    noChanges: 'No allocation changes in this period',
                    historyLimited:
                        'Showing the latest 50 changes for this enterprise',
                    noUsers: 'No eligible employees are configured',
                },
                presentation: {
                    history: 'Accounting period',
                    currentPeriod: 'Current period',
                    previousPeriod: 'Previous period',
                    comparison: 'Period comparison',
                    comparisonNotice: 'Selected period versus the preceding full period; the current period may be incomplete.',
                    noRecordedUsage: 'No recorded calls match this period and these filters.',
                    noComparison: 'No matching usage is recorded for the preceding period.',
                    queue: 'Unresolved calls',
                    allCalls: 'All calls',
                    previousPage: 'Previous page',
                    nextPage: 'Next page',
                    evidenceAvailable: 'Measurement recorded',
                    evidenceMissing: 'No recorded measurement',
                    evidenceDisabled: 'Receipt inspection disabled',
                    title: 'Usage and budgets',
                    allocations: 'Manage allocations',
                    daily: 'Daily usage',
                    breakdown: 'Usage breakdown',
                    details: 'Call details',
                    close: 'Close',
                    adapter: 'Provider adapter',
                    profile: 'Usage profile',
                    callId: 'Call reference',
                    period: 'Accounting period',
                    completed: 'Last settlement',
                    evidence: 'Recorded provider measurement',
                    noEvidence:
                        'No verified measurement is available. The reservation remains held.',
                    reconcile: 'Reconcile usage',
                    reason: 'Reason for reconciliation',
                    review: 'Review reconciliation',
                    confirm: 'Confirm reconciliation',
                    cancel: 'Cancel',
                    reviewNotice:
                        'Apply the recorded provider measurement to this call. This does not repeat the model call or change its business outcome.',
                    uncertain:
                        'The outcome could not be confirmed. Refresh the call before another action.',
                    reviewFailed:
                        'The call could not be reviewed. Refresh and check its current state.',
                    refreshCall: 'Refresh call',
                    reconciled: 'Reconciled by',
                    noBreakdown: 'No usage for these filters',
                    measured: 'Measured',
                    inProgress: 'In progress',
                    reconciliation: 'Pending reconciliation',
                    conversationPurpose: 'Conversation',
                    indexingPurpose: 'Knowledge preparation',
                    evaluationPurpose: 'Evaluation',
                    retryPurpose: 'Retry',
                    planningPurpose: 'Planning',
                    personal: 'Personal',
                    enterprise: 'Enterprise',
                    refresh: 'Refresh usage',
                    consumed: 'Consumed tokens',
                    reserved: 'Reserved tokens',
                    pending: 'Pending reconciliation',
                    calls: 'Model calls',
                    principal: 'Employee',
                    model: 'Model',
                    purpose: 'Purpose',
                    all: 'All',
                    apply: 'Apply filters',
                    recent: 'Recent calls',
                    state: 'Accounting state',
                    created: 'Started',
                    empty: 'No usage in this period',
                    limited: 'Showing a bounded result window',
                    unavailable: 'Accounting unavailable',
                    reset: 'Next reset',
                },
            },
            diagnostics: {
                enabled: true,
                includeAdapter: true,
                includeModel: true,
                includeTenant: true,
                includePrompt: false,
                includeResponse: false,
                includeEndpoint: false,
            },
        },
    },
};
