/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module testimonial/src/schemas/schemas @description Defines provenance-safe testimonial candidates, immutable editorial versions, scoped consent evidence, and sanitized public projections. @layer schema @owner testimonial @override Later modules may add governed fields without weakening evidence, consent, tenant, or withdrawal guarantees. */
module.exports = { testimonial: {
    testimonialCandidate: Object.assign({ super: 'base', model: true, schemaPolicies: ['customerOwned'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, ownerId: { type: 'string', required: true , description: 'Identifies the principal or business owner responsible for this record.'}, sourceType: { type: 'string', required: true, enum: ['DIRECT', 'REVIEW', 'FEEDBACK', 'INTERVIEW', 'IMPORT'] , description: 'Classifies this record by source type for validation and business handling.'},
        sourceModule: { type: 'string', required: false , description: 'Stores the source module value used by this record.'}, sourceRecordType: { type: 'string', required: false , description: 'Classifies this record by source record type for validation and business handling.'}, sourceRecordCode: { type: 'string', required: false , description: 'Stores the source record code used to classify, link, or resolve this record.'}, originalText: { type: 'string', required: true , description: 'Stores the original text value used by this record.'},
        provenance: { type: 'object', required: true , description: 'Stores structured provenance details used by this record.'}, evidenceReferences: { type: 'array', required: false , description: 'Lists the evidence references associated with this record.'}, materialRelationship: { type: 'string', required: false , description: 'Stores the material relationship value used by this record.'}, status: { type: 'string', required: true, enum: ['CANDIDATE', 'EDITING', 'PENDING_CONFIRMATION', 'PENDING_APPROVAL', 'APPROVED', 'SCHEDULED', 'PUBLISHED', 'HIDDEN', 'WITHDRAWN', 'EXPIRED', 'REJECTED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}, capturedAt: { type: 'date', required: true , description: 'Records when the captured event or value applies.'}
    } }),
    testimonialVersion: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, candidateCode: { type: 'string', required: true , description: 'Stores the candidate code used to classify, link, or resolve this record.'}, version: { type: 'int', required: true , description: 'Stores the numeric version used by this record.'}, locale: { type: 'string', required: true , description: 'Stores the locale code used for language, formatting, and regional behavior.'}, variant: { type: 'string', required: true, enum: ['SHORT_QUOTE', 'FULL_STORY', 'CASE_STUDY_TEASER', 'VIDEO'] , description: 'Selects the variant value used to drive validation, filtering, and business behavior.'},
        editorialText: { type: 'string', required: true , description: 'Stores the editorial text value used by this record.'}, sanitizedText: { type: 'string', required: true , description: 'Stores the sanitized text value used by this record.'}, mediaCodes: { type: 'array', required: false , description: 'Lists media codes used to classify, link, or resolve this record.'}, status: { type: 'string', required: true, enum: ['DRAFT', 'PENDING_CUSTOMER_CONFIRMATION', 'CUSTOMER_CONFIRMED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SUPERSEDED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        customerConfirmedAt: { type: 'date', required: false , description: 'Records when the customer confirmed event or value applies.'}, approvedBy: { type: 'string', required: false , description: 'Stores the approved by value used by this record.'}, approvedAt: { type: 'date', required: false , description: 'Records when the approved event or value applies.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}, createdAt: { type: 'date', required: true , description: 'Records when the created event or value applies.'}
    } }),
    testimonialConsent: Object.assign({ super: 'base', model: true, schemaPolicies: ['customerOwned'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, candidateCode: { type: 'string', required: true , description: 'Stores the candidate code used to classify, link, or resolve this record.'}, ownerId: { type: 'string', required: true , description: 'Identifies the principal or business owner responsible for this record.'}, version: { type: 'int', required: true , description: 'Stores the numeric version used by this record.'}, status: { type: 'string', required: true, enum: ['PENDING', 'GRANTED', 'DENIED', 'WITHDRAWN', 'EXPIRED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        attribution: { type: 'object', required: true , description: 'Stores structured attribution details used by this record.'}, channels: { type: 'array', required: true , description: 'Lists the channels associated with this record.'}, regions: { type: 'array', required: true , description: 'Lists the regions associated with this record.'}, likenessAllowed: { type: 'bool', required: true, default: false , description: 'Indicates whether likeness allowed applies for this record.'}, mediaAllowed: { type: 'bool', required: true, default: false , description: 'Indicates whether media allowed applies for this record.'},
        policyVersion: { type: 'string', required: true , description: 'Stores the policy version value used by this record.'}, evidence: { type: 'object', required: true , description: 'Stores structured evidence details used by this record.'}, validFrom: { type: 'date', required: true , description: 'Records when the valid from event or value applies.'}, expiresAt: { type: 'date', required: false , description: 'Records when the expires event or value applies.'}, withdrawnAt: { type: 'date', required: false , description: 'Records when the withdrawn event or value applies.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}
    } }),
    testimonialProjection: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, candidateCode: { type: 'string', required: true , description: 'Stores the candidate code used to classify, link, or resolve this record.'}, versionCode: { type: 'string', required: true , description: 'Stores the version code used to classify, link, or resolve this record.'}, projectionVersion: { type: 'int', required: true , description: 'Stores the numeric projection version used by this record.'}, publicText: { type: 'string', required: true , description: 'Stores the public text value used by this record.'}, attribution: { type: 'object', required: true , description: 'Stores structured attribution details used by this record.'}, disclosures: { type: 'array', required: false , description: 'Lists the disclosures associated with this record.'},
        channel: { type: 'string', required: true , description: 'Stores the channel value used by this record.'}, region: { type: 'string', required: true , description: 'Stores the region value used by this record.'}, locale: { type: 'string', required: true , description: 'Stores the locale code used for language, formatting, and regional behavior.'}, wcmsPlacementCodes: { type: 'array', required: false , description: 'Lists wcms placement codes used to classify, link, or resolve this record.'}, publicationRequestCode: { type: 'string', required: false , description: 'Stores the publication request code used to classify, link, or resolve this record.'}, status: { type: 'string', required: true, enum: ['PREVIEW', 'SCHEDULED', 'PUBLISHED', 'HIDDEN', 'WITHDRAWN', 'EXPIRED', 'FAILED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'},
        scheduledAt: { type: 'date', required: false , description: 'Records when the scheduled event or value applies.'}, publishedAt: { type: 'date', required: false , description: 'Records when the published event or value applies.'}, hiddenAt: { type: 'date', required: false , description: 'Records when the hidden event or value applies.'}, expiresAt: { type: 'date', required: false , description: 'Records when the expires event or value applies.'}, revision: { type: 'int', required: true, default: 0 , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}, lastErrorCode: { type: 'string', required: false , description: 'Stores the last error code used to classify, link, or resolve this record.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}
    } })
} };
