/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module promotion/src/schemas/schemas @description Defines governed Phase 2 promotion persistence and decision evidence. @layer schema @owner promotion */
module.exports = { promotion: {
    promotion: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, name: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['DRAFT', 'SUBMITTED', 'APPROVED', 'SCHEDULED', 'ACTIVE', 'SUSPENDED', 'ARCHIVED'] }, priority: { type: 'int', required: true }, conditions: { type: 'object', required: true }, actions: { type: 'object', required: true }, budget: { type: 'object', required: false }, approval: { type: 'object', required: false }, analytics: { type: 'object', required: false }, validFrom: { type: 'date', required: false }, validTo: { type: 'date', required: false }, revision: { type: 'int', required: true } } }),
    couponBatch: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, promotionCode: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['DRAFT', 'GENERATED', 'RESERVED', 'ACTIVE', 'RELEASED', 'EXPIRED'] }, issuedCount: { type: 'int', required: true }, reservedCount: { type: 'int', required: true }, tokenHashPolicy: { type: 'string', required: true }, sourceReference: { type: 'string', required: false }, revision: { type: 'int', required: true } } }),
    coupon: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, promotionCode: { type: 'string', required: true }, batchCode: { type: 'string', required: false }, tokenHash: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['ACTIVE', 'RESERVED', 'REDEEMED', 'SUSPENDED', 'EXPIRED'] }, maxUses: { type: 'int', required: true }, usedCount: { type: 'int', required: true }, reservedFor: { type: 'string', required: false }, revision: { type: 'int', required: true } } }),
    promotionBudgetLedger: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, promotionCode: { type: 'string', required: true }, mutationType: { type: 'string', required: true, enum: ['COMMIT', 'RELEASE', 'RECONCILE'] }, amount: { type: 'string', required: true }, beforeSpent: { type: 'string', required: true }, afterSpent: { type: 'string', required: true }, targetCode: { type: 'string', required: false }, idempotencyKey: { type: 'string', required: true }, actorId: { type: 'string', required: false }, correlationId: { type: 'string', required: false }, occurredAt: { type: 'date', required: true } } }),
    promotionRedemption: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, promotionCode: { type: 'string', required: true }, couponCode: { type: 'string', required: false }, ownerId: { type: 'string', required: true }, targetType: { type: 'string', required: true, enum: ['CART', 'ENTRY', 'DELIVERY', 'ORDER'] }, targetCode: { type: 'string', required: true }, discountAmount: { type: 'string', required: true }, currency: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['APPLIED', 'REVERSED', 'RECONCILIATION_REQUIRED'] }, decisionCode: { type: 'string', required: false }, idempotencyKey: { type: 'string', required: true }, reversalReasonCode: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, revision: { type: 'int', required: true }, appliedAt: { type: 'date', required: true }, reversedAt: { type: 'date', required: false } } }),
    discountDecision: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, promotionCode: { type: 'string', required: true }, targetType: { type: 'string', required: true, enum: ['CART', 'ENTRY', 'DELIVERY'] }, targetCode: { type: 'string', required: true }, discountAmount: { type: 'string', required: true }, currency: { type: 'string', required: true }, reasonCode: { type: 'string', required: true }, ruleVersion: { type: 'string', required: true }, sourceHash: { type: 'string', required: true }, correlationId: { type: 'string', required: true }, decidedAt: { type: 'date', required: true } } })
} };
module.exports.promotion.promotion.backoffice = { operations: ['search', 'read', 'create', 'update'], description: 'Promotion rule master data.' };
