/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module paymentCore/src/schemas/schemas @description Defines governed Commerce lifecycle evidence. @layer schema @owner paymentCore */
module.exports = { paymentCore: {
    paymentInstrumentReference: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, ownerId: { type: 'string', required: false , description: 'Identifies the principal or business owner responsible for this record.'}, orderCode: { type: 'string', required: false , description: 'Stores the order code used to classify, link, or resolve this record.'}, cartCode: { type: 'string', required: false , description: 'Stores the cart code used to classify, link, or resolve this record.'}, status: { type: 'string', required: true , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}, idempotencyKey: { type: 'string', required: false , description: 'Stores the idempotency key value used by this record.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}, evidence: { type: 'object', required: false , description: 'Stores structured evidence details used by this record.'}, occurredAt: { type: 'date', required: false , description: 'Records when the occurred event or value applies.'} } }),
    paymentTransaction: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, ownerId: { type: 'string', required: false , description: 'Identifies the principal or business owner responsible for this record.'}, orderCode: { type: 'string', required: false , description: 'Stores the order code used to classify, link, or resolve this record.'}, cartCode: { type: 'string', required: false , description: 'Stores the cart code used to classify, link, or resolve this record.'}, status: { type: 'string', required: true , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}, idempotencyKey: { type: 'string', required: false , description: 'Stores the idempotency key value used by this record.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}, evidence: { type: 'object', required: false , description: 'Stores structured evidence details used by this record.'}, occurredAt: { type: 'date', required: false , description: 'Records when the occurred event or value applies.'}, currency: { type: 'string', required: false , description: 'Stores the currency code used for monetary amounts on this record.'}, totalAmount: { type: 'string', required: false , description: 'Stores the total amount used for calculation, reporting, or settlement.'} } }),
    paymentTransactionEntry: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, ownerId: { type: 'string', required: false , description: 'Identifies the principal or business owner responsible for this record.'}, orderCode: { type: 'string', required: false , description: 'Stores the order code used to classify, link, or resolve this record.'}, cartCode: { type: 'string', required: false , description: 'Stores the cart code used to classify, link, or resolve this record.'}, status: { type: 'string', required: true , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}, idempotencyKey: { type: 'string', required: false , description: 'Stores the idempotency key value used by this record.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}, evidence: { type: 'object', required: false , description: 'Stores structured evidence details used by this record.'}, occurredAt: { type: 'date', required: false , description: 'Records when the occurred event or value applies.'}, productCode: { type: 'string', required: false , description: 'Stores the product code used to classify, link, or resolve this record.'}, sku: { type: 'string', required: false , description: 'Stores the SKU used to identify the purchasable product or variant.'}, quantity: { type: 'string', required: false , description: 'Stores the quantity value used by this record.'}, unitAmount: { type: 'string', required: false , description: 'Stores the unit amount used for calculation, reporting, or settlement.'} } }),
    paymentReconciliation: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, ownerId: { type: 'string', required: false , description: 'Identifies the principal or business owner responsible for this record.'}, orderCode: { type: 'string', required: false , description: 'Stores the order code used to classify, link, or resolve this record.'}, cartCode: { type: 'string', required: false , description: 'Stores the cart code used to classify, link, or resolve this record.'}, status: { type: 'string', required: true , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}, idempotencyKey: { type: 'string', required: false , description: 'Stores the idempotency key value used by this record.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'}, evidence: { type: 'object', required: false , description: 'Stores structured evidence details used by this record.'}, occurredAt: { type: 'date', required: false , description: 'Records when the occurred event or value applies.'} } })
} };
module.exports.paymentCore.paymentTransaction.backoffice = { operations: ['search', 'read'], description: 'Payment transaction evidence; provider operations remain Payment-owned.' };
module.exports.paymentCore.paymentReconciliation.backoffice = { operations: ['search', 'read'], description: 'Provider reconciliation evidence.' };
