/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/* Nodics source-available software. See root LICENSE. */
/** @module order/service/DefaultOrderBackofficeCapabilityService @description Publishes Order-owned BackOffice order and reverse-lifecycle workspaces. @layer service @owner order */
module.exports = {
    /** Registers the Order BackOffice capability provider. */
    init:function(){SERVICE.DefaultModuleRegistrationAgentService.registerBackofficeCapabilityProvider('order',this);return Promise.resolve(true);},
    /** Completes provider lifecycle initialization. */
    postInit:function(){return Promise.resolve(true);},
    /** Builds hidden request-code input used by Axis lifecycle action routing. */
    requestCodeInput:function(){return {name:'requestCode',label:'Request code',type:'HIDDEN',required:true,valueFromRecord:'code',maximumLength:128};},
    /** Builds a common operator reason input. */
    reasonInput:function(){return {name:'reason',label:'Reason',type:'MULTILINE',required:false,maximumLength:512};},
    /** Builds the backend operation route for one lifecycle action code. */
    actionRoute:function(actionCode){return '/order-lifecycle/:requestCode/actions/'+actionCode;},
    /** Builds one Order-owned operator action definition. */
    action:function(options){let actionCode=options.actionCode;let model=Object.assign({permission:'commerce.lifecycle.act',ownerModule:'order',handlerAction:actionCode,operationRoute:this.actionRoute(actionCode),inputFields:[this.requestCodeInput(),this.reasonInput()],targetStatuses:['SUBMITTED','APPROVED','RETRY_PENDING','RECONCILING'],featureState:'ACTIVE'},options);delete model.actionCode;return model;},
    /** Returns standard operator lifecycle action definitions. */
    lifecycleActions:function(scope){
        let actions=[
            this.action({id:'approve',label:'Approve',intent:'APPROVE',actionCode:'APPROVE',summary:'Approve the lifecycle request and call downstream owner services when required.',order:10}),
            this.action({id:'reject',label:'Reject',intent:'REJECT',actionCode:'REJECT',summary:'Reject the lifecycle request with an operator-visible reason.',order:20}),
            this.action({id:'retry',label:'Retry',intent:'RETRY',actionCode:'RETRY',summary:'Move the request into retry-pending state for recoverable downstream failures.',order:30}),
            this.action({id:'reconcile',label:'Reconcile',intent:'RECONCILE',actionCode:'RECONCILE',summary:'Mark the request for reconciliation or execute a reconciliation-aware owner action.',order:40})
        ];
        if(scope==='RETURN') actions=actions.concat([
            this.action({id:'mark-received',label:'Mark received',intent:'OTHER',actionCode:'MARK_RECEIVED',summary:'Record returned-goods receipt through Fulfillment-owned services.',order:50,inputFields:[this.requestCodeInput(),{name:'rmaCode',label:'RMA code',type:'TEXT',required:false,valueFromRecord:'evidence.rmaCode',maximumLength:128},{name:'receivedQuantity',label:'Received quantity',type:'TEXT',required:false,defaultValue:'1',maximumLength:16},this.reasonInput()]}),
            this.action({id:'mark-inspected',label:'Mark inspected',intent:'OTHER',actionCode:'MARK_INSPECTED',summary:'Record return inspection through Fulfillment-owned services.',order:60,inputFields:[this.requestCodeInput(),{name:'rmaCode',label:'RMA code',type:'TEXT',required:false,valueFromRecord:'evidence.rmaCode',maximumLength:128},{name:'disposition',label:'Disposition',type:'SELECT',required:true,options:['RESTOCK','REFURBISH','SCRAP','REJECT_RETURN'],defaultValue:'RESTOCK',maximumLength:32},this.reasonInput()]}),
            this.action({id:'record-disposition',label:'Record disposition',intent:'OTHER',actionCode:'DISPOSITION',summary:'Record inventory disposition and refund eligibility after inspection.',order:70,inputFields:[this.requestCodeInput(),{name:'rmaCode',label:'RMA code',type:'TEXT',required:false,valueFromRecord:'evidence.rmaCode',maximumLength:128},{name:'disposition',label:'Disposition',type:'SELECT',required:true,options:['RESTOCK','REFURBISH','SCRAP','REJECT_RETURN'],defaultValue:'RESTOCK',maximumLength:32},this.reasonInput()]})
        ]);
        if(scope==='REFUND'||scope==='CANCELLATION') actions=actions.map(action=>action.id==='approve'||action.id==='reconcile'?Object.assign({},action,{inputFields:[this.requestCodeInput(),{name:'refundAmount',label:'Refund amount',type:'TEXT',required:false,valueFromRecord:'evidence.refundPreview.amount',maximumLength:32},{name:'currency',label:'Currency',type:'TEXT',required:false,valueFromRecord:'evidence.refundPreview.currency',maximumLength:8},this.reasonInput()]}):action);
        return actions;
    },
    /** Returns the Order-owned BackOffice capability contract. */
    getCapability:function(){let d=SERVICE.DefaultBackofficeCapabilityDefinitionService;let common={defaultColumns:['code','orderCode','requestType','reasonCode','status','revision','occurredAt'],hiddenFields:['idempotencyKey','correlationId','evidence']};let item=(options)=>d.workbench(Object.assign({moduleName:'order',permission:'commerce.order.read'},options));return d.capability({capabilityId:'commerce-order',displayName:'Checkout & Orders',category:'commerce',icon:'commerce',navigation:[
            item({id:'orders-and-checkouts',label:'Order and Checkout Workspace',route:'/commerce/checkout',schemaName:'commerceOrder',order:800,summary:'Find cart, checkout, or order; inspect orders requiring attention, cart-to-order trace, placement failures, and cross-domain status summaries.',group:{id:'orders-checkouts',label:'Orders and Checkouts',order:800},presentation:{defaultColumns:['code','orderCode','cartCode','status','currency','totalAmount','revision','occurredAt'],hiddenFields:['idempotencyKey','correlationId','evidence']}}),
            item({id:'checkout-sessions',label:'Checkout Sessions',route:'/commerce/checkout/sessions',schemaName:'commerceOrder',order:820,summary:'Planned active, completed, expired sessions and customer, organisation, store, channel, locale, and currency context.',group:{id:'orders-checkouts',label:'Orders and Checkouts',order:800},presentation:{defaultColumns:['code','orderCode','cartCode','status','currency','totalAmount','revision','occurredAt'],hiddenFields:['idempotencyKey','correlationId','evidence']},featureState:'DISABLED'}),
            item({id:'checkout-validation',label:'Checkout Validation',route:'/commerce/checkout/validation',schemaName:'commerceOrder',order:830,summary:'Planned customer, address, product, price, promotion, tax, availability, delivery, and payment-selection validation workspace.',group:{id:'orders-checkouts',label:'Orders and Checkouts',order:800},presentation:{defaultColumns:['code','orderCode','cartCode','status','currency','totalAmount','revision','occurredAt'],hiddenFields:['idempotencyKey','correlationId','evidence']},featureState:'DISABLED'}),
            item({id:'checkout-placement',label:'Checkout Placement',route:'/commerce/checkout/placement',schemaName:'commerceOrder',order:840,summary:'Planned placement progress, success/failure, checkpoint, duplicate, and idempotency review workspace.',group:{id:'orders-checkouts',label:'Orders and Checkouts',order:800},presentation:{defaultColumns:['code','orderCode','cartCode','status','currency','totalAmount','revision','occurredAt'],hiddenFields:['idempotencyKey','correlationId','evidence']},featureState:'DISABLED'}),
            item({id:'orders',label:'Orders',route:'/commerce/checkout/orders',schemaName:'commerceOrder',order:850,summary:'Inspect all orders, recently placed orders, orders requiring attention, and orders by customer, organisation, store, or channel.',group:{id:'orders-checkouts',label:'Orders and Checkouts',order:800},presentation:{defaultColumns:['code','orderCode','cartCode','status','currency','totalAmount','revision','occurredAt'],hiddenFields:['idempotencyKey','correlationId','evidence']}}),
            item({id:'order-details-evidence',label:'Order Details and Evidence',route:'/commerce/checkout/order-evidence',schemaName:'commerceOrder',order:860,summary:'Inspect order summary, item, customer/address snapshot, price, promotion, discount, tax, payment, fulfillment, shipping, cart, and checkout evidence.',group:{id:'orders-checkouts',label:'Orders and Checkouts',order:800},presentation:{defaultColumns:['code','orderCode','cartCode','status','currency','totalAmount','revision','occurredAt'],hiddenFields:['idempotencyKey','correlationId','evidence']},featureState:'DISABLED'}),
            item({id:'order-placement-exceptions',label:'Order Placement Exceptions',route:'/commerce/checkout/placement-exceptions',schemaName:'commerceOrder',order:870,summary:'Planned order placement exception workspace.',group:{id:'orders-checkouts',label:'Orders and Checkouts',order:800},presentation:{defaultColumns:['code','orderCode','cartCode','status','currency','totalAmount','revision','occurredAt'],hiddenFields:['idempotencyKey','correlationId','evidence']},featureState:'DISABLED'}),
            item({id:'order-checkout-insights',label:'Order and Checkout Insights',route:'/commerce/checkout/insights',schemaName:'commerceOrder',order:880,summary:'Planned order and checkout insights workspace.',group:{id:'orders-checkouts',label:'Orders and Checkouts',order:800},presentation:{defaultColumns:['code','orderCode','cartCode','status','currency','totalAmount','revision','occurredAt'],hiddenFields:['idempotencyKey','correlationId','evidence']},featureState:'DISABLED'}),
            d.workbench({id:'order-lifecycle-operations',label:'Lifecycle Workspace',route:'/commerce/order-lifecycle',moduleName:'order',schemaName:'orderLifecycleRequest',order:900,permission:'commerce.lifecycle.read',summary:'Find order or lifecycle request, review requests requiring attention, pending approvals, delayed or failed processes, and cross-domain progress.',group:{id:'order-lifecycle-operations',label:'Order Lifecycle Operations',order:900},presentation:common}),
            d.workbench({id:'order-cancellations',label:'Cancellations',route:'/commerce/checkout/cancellations',moduleName:'order',schemaName:'orderLifecycleRequest',order:910,permission:'commerce.lifecycle.read',summary:'Operate cancellation requests, eligibility review, approval, rejection, progress, and failures.',group:{id:'order-lifecycle-operations',label:'Order Lifecycle Operations',order:900},presentation:Object.assign({},common,{fixedFilters:[{id:'request-type-cancellation',label:'Cancellation requests',field:'requestType',value:'CANCELLATION',order:10}]}),lifecycleActions:this.lifecycleActions('CANCELLATION')}),
            d.workbench({id:'order-returns',label:'Returns',route:'/commerce/checkout/returns',moduleName:'order',schemaName:'orderLifecycleRequest',order:920,permission:'commerce.lifecycle.read',summary:'Operate return requests, eligibility, authorization, items, quantities, progress, receipt, inspection, disposition, and refund status.',group:{id:'order-lifecycle-operations',label:'Order Lifecycle Operations',order:900},presentation:Object.assign({},common,{fixedFilters:[{id:'request-type-return',label:'Return requests',field:'requestType',value:'RETURN',order:10}]}),lifecycleActions:this.lifecycleActions('RETURN')}),
            d.workbench({id:'order-refunds',label:'Refund Requests',route:'/commerce/checkout/refunds',moduleName:'order',schemaName:'orderLifecycleRequest',order:930,permission:'commerce.lifecycle.read',summary:'Operate refund eligibility, calculation preview, approval, rejection, payment execution, and reconciliation status.',group:{id:'order-lifecycle-operations',label:'Order Lifecycle Operations',order:900},presentation:Object.assign({},common,{fixedFilters:[{id:'request-type-refund',label:'Refund requests',field:'requestType',value:'REFUND',order:10}]}),lifecycleActions:this.lifecycleActions('REFUND')}),
            d.workbench({id:'order-exchanges',label:'Exchanges and Replacements',route:'/commerce/checkout/exchanges',moduleName:'order',schemaName:'orderLifecycleRequest',order:940,permission:'commerce.lifecycle.read',summary:'Operate exchange and replacement requests, eligibility, returned-item progress, replacement order, and price-difference status.',group:{id:'order-lifecycle-operations',label:'Order Lifecycle Operations',order:900},presentation:Object.assign({},common,{fixedFilters:[{id:'request-type-exchange',label:'Exchange requests',field:'requestType',value:'EXCHANGE',order:10},{id:'request-type-replacement',label:'Replacement requests',field:'requestType',value:'REPLACEMENT',order:20}]}),lifecycleActions:this.lifecycleActions('RETURN')}),
            d.workbench({id:'order-appeals',label:'Appeals and Exceptions',route:'/commerce/checkout/appeals',moduleName:'order',schemaName:'orderLifecycleRequest',order:950,permission:'commerce.lifecycle.read',summary:'Operate customer appeal and exception intent for rejected cancellations, returns, refunds or delayed-refund handling.',group:{id:'order-lifecycle-operations',label:'Order Lifecycle Operations',order:900},presentation:Object.assign({},common,{fixedFilters:[{id:'request-type-appeal',label:'Appeal requests',field:'requestType',value:'APPEAL',order:10}]}),lifecycleActions:this.lifecycleActions('CANCELLATION')})
            ,d.workbench({id:'lifecycle-recovery',label:'Lifecycle Recovery',route:'/commerce/order-lifecycle/recovery',moduleName:'order',schemaName:'orderLifecycleRequest',order:960,permission:'commerce.lifecycle.read',summary:'Planned lifecycle recovery workspace.',group:{id:'order-lifecycle-operations',label:'Order Lifecycle Operations',order:900},presentation:common,featureState:'DISABLED'})
            ,d.workbench({id:'lifecycle-history-audit',label:'Lifecycle History and Audit',route:'/commerce/order-lifecycle/history',moduleName:'order',schemaName:'orderLifecycleRequest',order:970,permission:'commerce.lifecycle.read',summary:'Planned lifecycle history and audit workspace.',group:{id:'order-lifecycle-operations',label:'Order Lifecycle Operations',order:900},presentation:common,featureState:'DISABLED'})
        ]});}
};
