/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

'use strict';

/** @module discoveryConfig/service/defaultDiscoveryBackofficeCapabilityService @description Publishes generic Discovery Axis capability metadata. @layer service @owner discoveryConfig */
module.exports = {
    /** Registers Discovery as a BackOffice capability provider. @returns {Promise<boolean>} Registration result. */
    init: function () {
        SERVICE.DefaultModuleRegistrationAgentService.registerBackofficeCapabilityProvider('discoveryConfig', this);
        return Promise.resolve(true);
    },

    /** Completes provider lifecycle. @returns {Promise<boolean>} Post-init result. */
    postInit: function () { return Promise.resolve(true); },

    /** Builds Axis/BackOffice capability metadata for Discovery configuration. @returns {Object} Capability definition. */
    getCapability: function () {
        let d = SERVICE.DefaultBackofficeCapabilityDefinitionService;
        return d.capability({ capabilityId: 'discovery-management', displayName: 'Discovery', category: 'platform', icon: 'search', navigation: [
            d.workbench({ id: 'discovery-management', label: 'Search Workspace', route: '/discovery/config', moduleName: 'discoveryConfig', schemaName: 'discoveryIndexConfiguration', order: 600, permission: 'discovery.config.read', summary: 'Review search overview, readiness, attention states, zero-result alerts, unpublished changes, publication status, recent changes, and store/channel/locale coverage.', group: { id: 'search-discovery', label: 'Search and Discovery', order: 600 }, presentation: { defaultColumns: ['code', 'name', 'ownerType', 'indexType', 'engine', 'indexName', 'status', 'revision'] } }),
            d.workbench({ id: 'search-experiences', label: 'Search Experiences', route: '/discovery/experiences', moduleName: 'discoveryConfig', schemaName: 'discoveryIndexConfiguration', order: 610, permission: 'discovery.config.read', summary: 'Configure product, content, site, store/channel, locale, suggestions, result presentation, and default sort behavior.', group: { id: 'search-discovery', label: 'Search and Discovery', order: 600 }, presentation: { defaultColumns: ['code', 'name', 'ownerType', 'indexType', 'engine', 'indexName', 'status', 'revision'] }, featureState: 'DISABLED' }),
            d.workbench({ id: 'search-sources-indexes', label: 'Search Sources and Indexes', route: '/discovery/sources-indexes', moduleName: 'discoveryConfig', schemaName: 'discoveryIndexConfiguration', order: 620, permission: 'discovery.config.read', summary: 'Manage index configurations, source mixes, field mappings, data sources, projections, coverage, validation, and readiness.', group: { id: 'search-discovery', label: 'Search and Discovery', order: 600 }, presentation: { defaultColumns: ['code', 'name', 'ownerType', 'indexType', 'engine', 'indexName', 'status', 'revision'] } }),
            d.workbench({ id: 'discovery-source-mixes', parentId: 'search-sources-indexes', label: 'Source Mixes', route: '/discovery/source-mixes', moduleName: 'discoveryConfig', schemaName: 'discoverySourceMixConfiguration', order: 621, permission: 'discovery.config.read', summary: 'Configure approved domain source mixes used to build Discovery documents.', presentation: { defaultColumns: ['code', 'ownerType', 'status', 'revision'] } }),
            d.workbench({ id: 'query-result-configuration', label: 'Query and Result Configuration', route: '/discovery/query-profiles', moduleName: 'discoveryConfig', schemaName: 'discoveryQueryProfile', order: 630, permission: 'discovery.config.read', summary: 'Configure query profiles, searchable/filterable fields, sort options, page-size policy, constraints, result fields, locale/analyzer selection, and preview.', group: { id: 'search-discovery', label: 'Search and Discovery', order: 600 }, presentation: { defaultColumns: ['code', 'ownerType', 'defaultSort', 'pageSizeLimit', 'status', 'revision'] } }),
            d.workbench({ id: 'discovery-query-profiles', parentId: 'query-result-configuration', label: 'Query Profiles', route: '/discovery/query-profiles', moduleName: 'discoveryConfig', schemaName: 'discoveryQueryProfile', order: 631, permission: 'discovery.config.read', summary: 'Configure searchable fields, filters, sorts, and page-size policy.', presentation: { defaultColumns: ['code', 'ownerType', 'defaultSort', 'pageSizeLimit', 'status', 'revision'] } }),
            d.workbench({ id: 'facets-filters', label: 'Facets and Filters', route: '/discovery/facet-profiles', moduleName: 'discoveryConfig', schemaName: 'discoveryFacetProfile', order: 640, permission: 'discovery.config.read', summary: 'Configure facet profiles, groups, filters, ordering, multi-select, ranges, categories, price, availability, locale labels, and preview.', group: { id: 'search-discovery', label: 'Search and Discovery', order: 600 }, presentation: { defaultColumns: ['code', 'ownerType', 'status', 'revision'] } }),
            d.workbench({ id: 'discovery-facet-profiles', parentId: 'facets-filters', label: 'Facet Profiles', route: '/discovery/facet-profiles', moduleName: 'discoveryConfig', schemaName: 'discoveryFacetProfile', order: 641, permission: 'discovery.config.read', summary: 'Configure facet groups available to Product and content search experiences.', presentation: { defaultColumns: ['code', 'ownerType', 'status', 'revision'] } }),
            d.workbench({ id: 'search-merchandising-ranking', label: 'Search Merchandising and Ranking', route: '/discovery/ranking-profiles', moduleName: 'discoveryConfig', schemaName: 'discoveryRankingProfile', order: 650, permission: 'discovery.config.read', summary: 'Configure ranking profiles, commerce search rules, boosting, burying, pinning, category/search-term/store/locale rules, priority, conflict resolution, scheduling, preview, and publication.', group: { id: 'search-discovery', label: 'Search and Discovery', order: 600 }, presentation: { defaultColumns: ['code', 'ownerType', 'conflictPolicy', 'status', 'revision'] } }),
            d.workbench({ id: 'discovery-ranking-profiles', parentId: 'search-merchandising-ranking', label: 'Ranking Profiles', route: '/discovery/ranking-profiles', moduleName: 'discoveryConfig', schemaName: 'discoveryRankingProfile', order: 651, permission: 'discovery.config.read', summary: 'Configure generic ranking profile policy; domain modules own domain-specific rules.', presentation: { defaultColumns: ['code', 'ownerType', 'conflictPolicy', 'status', 'revision'] } }),
            d.workbench({ id: 'search-language-relevance', label: 'Search Language and Relevance', route: '/discovery/language-relevance', moduleName: 'discoveryConfig', schemaName: 'discoveryQueryProfile', order: 660, permission: 'discovery.config.read', summary: 'Planned synonyms, stop words, redirects, spelling, stemming, analyzers, phrase matching, tuning, suggestions, and popular queries.', group: { id: 'search-discovery', label: 'Search and Discovery', order: 600 }, presentation: { defaultColumns: ['code', 'ownerType', 'defaultSort', 'pageSizeLimit', 'status', 'revision'] }, featureState: 'DISABLED' }),
            d.workbench({ id: 'search-publication-index-operations', label: 'Search Publication and Index Operations', route: '/discovery/publication-policies', moduleName: 'discoveryConfig', schemaName: 'discoveryPublicationPolicy', order: 670, permission: 'discovery.config.read', summary: 'Configure publication policies, previews, validation, publish, build/rebuild, batch status, alias switch, rollback, history, failed recovery, and projection freshness.', group: { id: 'search-discovery', label: 'Search and Discovery', order: 600 }, presentation: { defaultColumns: ['code', 'ownerType', 'batchSize', 'aliasSwitch', 'rollbackEnabled', 'status', 'revision'] } }),
            d.workbench({ id: 'discovery-publication-policies', parentId: 'search-publication-index-operations', label: 'Publication Policies', route: '/discovery/publication-policies', moduleName: 'discoveryConfig', schemaName: 'discoveryPublicationPolicy', order: 671, permission: 'discovery.config.read', summary: 'Configure batch, alias switch, and rollback behavior for Discovery index publication.', presentation: { defaultColumns: ['code', 'ownerType', 'batchSize', 'aliasSwitch', 'rollbackEnabled', 'status', 'revision'] } }),
            d.workbench({ id: 'search-analytics-optimization', label: 'Search Analytics and Optimization', route: '/discovery/analytics', moduleName: 'discoveryConfig', schemaName: 'discoveryIndexConfiguration', order: 680, permission: 'discovery.config.read', summary: 'Planned analytics for top terms, zero/low-result searches, refinement use, CTR, conversion, abandonment, facet usage, rule performance, trends, and comparisons.', group: { id: 'search-discovery', label: 'Search and Discovery', order: 600 }, presentation: { defaultColumns: ['code', 'name', 'ownerType', 'indexType', 'engine', 'indexName', 'status', 'revision'] }, featureState: 'DISABLED' })
        ] });
    }
};
