/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module store/src/schemas/schemas @description Defines governed Phase 2 store persistence and decision evidence. @layer schema @owner store */


module.exports = { store: {
    store: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, name: { type: 'string', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'}, status: { type: 'string', required: true, enum: ['ACTIVE', 'INACTIVE'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, defaultCurrency: { type: 'string', required: true , description: 'Stores the default currency value used by this record.'}, defaultLocale: { type: 'string', required: true , description: 'Stores the default locale value used by this record.'}, timezone: { type: 'string', required: true , description: 'Stores the timezone value used by this record.'}, enterpriseRef: { type: 'object', required: false , description: 'References the related enterprise record used by this record.'}, primaryLocationRef: { type: 'object', required: false , description: 'References the related primary location record used by this record.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} }, refSchema: { enterpriseRef: {"enabled":true,"moduleName":"profile","schemaName":"enterprise","type":"one","propertyName":"code"}, primaryLocationRef: {"enabled":true,"moduleName":"locationCore","schemaName":"location","type":"one","propertyName":"code"} } }),
    salesChannel: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, storeCode: { type: 'string', required: true , description: 'Stores the store code used to classify, link, or resolve this record.'}, name: { type: 'string', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'}, channelType: { type: 'string', required: true, enum: ['WEB', 'MOBILE', 'MARKETPLACE', 'POS'] , description: 'Classifies this record by channel type for validation and business handling.'}, status: { type: 'string', required: true, enum: ['ACTIVE', 'INACTIVE'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, enterpriseRef: { type: 'object', required: false , description: 'References the related enterprise record used by this record.'}, locationRef: { type: 'object', required: false , description: 'References the related location record used by this record.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} }, refSchema: { enterpriseRef: {"enabled":true,"moduleName":"profile","schemaName":"enterprise","type":"one","propertyName":"code"}, locationRef: {"enabled":true,"moduleName":"locationCore","schemaName":"location","type":"one","propertyName":"code"} } }),
    pointOfService: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, storeCode: { type: 'string', required: true , description: 'Stores the store code used to classify, link, or resolve this record.'}, name: { type: 'string', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'}, status: { type: 'string', required: true, enum: ['ACTIVE', 'INACTIVE'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, timezone: { type: 'string', required: true , description: 'Stores the timezone value used by this record.'}, operatorEnterpriseRef: { type: 'object', required: false , description: 'References the related operator enterprise record used by this record.'}, locationRef: { type: 'object', required: false , description: 'Links a physical point of service to its operating location; online service points do not require a physical place.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} }, refSchema: { operatorEnterpriseRef: {"enabled":true,"moduleName":"profile","schemaName":"enterprise","type":"one","propertyName":"code"}, locationRef: {"enabled":true,"moduleName":"locationCore","schemaName":"location","type":"one","propertyName":"code"} } })
} };
module.exports.store.store.backoffice = { operations: ['search', 'read', 'create', 'update'], description: 'Store master data and selling context defaults.' };
// These master-data counters are owned by generated CRUD, not a domain transition.
Object.values(module.exports.store).forEach(schema => {
    schema.backoffice = Object.assign({}, schema.backoffice, {
        concurrency: { field: 'revision', managed: true }
    });
    schema.definition.revision.default = 1;
    schema.definition.revision.description = 'Framework-managed concurrency counter; callers retain the read value but never calculate the next value.';
});
