/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module product/src/schemas/schemas @description Defines governed Phase 2 product persistence and decision evidence. @layer schema @owner product */
module.exports = { product: {
    product: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, enterpriseCode: { type: 'string', required: false }, productType: { type: 'string', required: false }, fulfillmentStrategy: { type: 'string', required: false }, digitalDeliveryType: { type: 'string', required: false }, name: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'] }, catalogVersion: { type: 'string', required: true }, revision: { type: 'int', required: true } } }),
    productLocalization: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, productCode: { type: 'string', required: true }, locale: { type: 'string', required: true }, name: { type: 'string', required: true }, description: { type: 'string', required: false }, slug: { type: 'string', required: false }, seo: { type: 'object', required: false }, attributes: { type: 'object', required: false }, classificationValues: { type: 'object', required: false }, media: { type: 'object', required: false }, status: { type: 'string', required: true, enum: ['DRAFT', 'READY'] }, revision: { type: 'int', required: true } }, indexes: { composite: { tenant: { enabled: true, name: 'tenant', options: { unique: true } }, productCode: { enabled: true, name: 'productCode', options: { unique: true } }, locale: { enabled: true, name: 'locale', options: { unique: true } } } } }),
    productVariant: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, enterpriseCode: { type: 'string', required: false }, productCode: { type: 'string', required: true }, sku: { type: 'string', required: true }, productType: { type: 'string', required: false }, fulfillmentStrategy: { type: 'string', required: false }, digitalDeliveryType: { type: 'string', required: false }, digitalBinding: { type: 'object', required: false }, attributes: { type: 'object', required: true }, status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'] }, revision: { type: 'int', required: true } } }),
    productVariantLocalization: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, variantCode: { type: 'string', required: true }, productCode: { type: 'string', required: true }, locale: { type: 'string', required: true }, attributes: { type: 'object', required: true }, media: { type: 'object', required: false }, status: { type: 'string', required: true, enum: ['DRAFT', 'READY'] }, revision: { type: 'int', required: true } }, indexes: { composite: { tenant: { enabled: true, name: 'tenant', options: { unique: true } }, variantCode: { enabled: true, name: 'variantCode', options: { unique: true } }, locale: { enabled: true, name: 'locale', options: { unique: true } } } } }),
    category: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, name: { type: 'string', required: true }, parentCode: { type: 'string', required: false }, status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'] }, revision: { type: 'int', required: true } } }),
    categoryLocalization: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, categoryCode: { type: 'string', required: true }, locale: { type: 'string', required: true }, name: { type: 'string', required: true }, description: { type: 'string', required: false }, slug: { type: 'string', required: false }, seo: { type: 'object', required: false }, media: { type: 'object', required: false }, status: { type: 'string', required: true, enum: ['DRAFT', 'READY'] }, revision: { type: 'int', required: true } }, indexes: { composite: { tenant: { enabled: true, name: 'tenant', options: { unique: true } }, categoryCode: { enabled: true, name: 'categoryCode', options: { unique: true } }, locale: { enabled: true, name: 'locale', options: { unique: true } } } } }),
    productPublication: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, productCode: { type: 'string', required: true }, catalogVersion: { type: 'string', required: true }, storeCode: { type: 'string', required: true }, revision: { type: 'int', required: true }, status: { type: 'string', required: true, enum: ['STAGED', 'PUBLISHED', 'SUPERSEDED', 'ROLLED_BACK', 'WITHDRAWN'] }, sourceHash: { type: 'string', required: true }, localizationEvidence: { type: 'object', required: true }, projectionCodes: { type: 'array', required: false }, previousPublicationCode: { type: 'string', required: false }, rollbackOf: { type: 'string', required: false }, stagedAt: { type: 'date', required: true }, publishedAt: { type: 'date', required: false }, correlationId: { type: 'string', required: true } } }),
    productSearchProjection: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { search: { enabled: true, idPropertyName: 'code' }, definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, enterpriseCode: { type: 'string', required: false }, productCode: { type: 'string', required: true }, storeCode: { type: 'string', required: true }, locale: { type: 'string', required: true }, payload: { type: 'object', required: true }, sourceHash: { type: 'string', required: true }, status: { type: 'string', required: true, enum: ['CURRENT', 'STALE', 'WITHDRAWN'] }, projectedAt: { type: 'date', required: true }, requestedLocale: { type: 'string', required: false }, fallbackUsed: { type: 'bool', required: false } } })
} };
module.exports.product.product.backoffice = { operations: ['search', 'read', 'create', 'update'], description: 'Product sellable master data.' };
