/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module product/src/schemas/schemas @description Defines governed Phase 2 product persistence and decision evidence. @layer schema @owner product */
module.exports = { product: {
    product: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, enterpriseCode: { type: 'string', required: false , description: 'Stores the enterprise code used to classify, link, or resolve this record.'}, productType: { type: 'string', required: false , description: 'Classifies this record by product type for validation and business handling.'}, fulfillmentStrategy: { type: 'string', required: false , description: 'Stores the fulfillment strategy value used by this record.'}, digitalDeliveryType: { type: 'string', required: false , description: 'Classifies this record by digital delivery type for validation and business handling.'}, name: { type: 'string', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'}, status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, catalogVersion: { type: 'string', required: true , description: 'Stores the catalog version value used by this record.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} } }),
    productLocalization: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, productCode: { type: 'string', required: true , description: 'Stores the product code used to classify, link, or resolve this record.'}, locale: { type: 'string', required: true , description: 'Stores the locale code used for language, formatting, and regional behavior.'}, name: { type: 'string', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'}, description: { type: 'string', required: false , description: 'Explains the business purpose, usage, or administrative meaning of this record.'}, slug: { type: 'string', required: false , description: 'Stores the slug value used by this record.'}, seo: { type: 'object', required: false , description: 'Stores structured seo details used by this record.'}, attributes: { type: 'object', required: false , description: 'Stores structured attributes details used by this record.'}, classificationValues: { type: 'object', required: false , description: 'Stores structured classification values details used by this record.'}, media: { type: 'object', required: false , description: 'Stores structured media details used by this record.'}, status: { type: 'string', required: true, enum: ['DRAFT', 'READY'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} }, indexes: { composite: { tenant: { enabled: true, name: 'tenant', options: { unique: true } }, productCode: { enabled: true, name: 'productCode', options: { unique: true } }, locale: { enabled: true, name: 'locale', options: { unique: true } } } } }),
    productVariant: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, enterpriseCode: { type: 'string', required: false , description: 'Stores the enterprise code used to classify, link, or resolve this record.'}, productCode: { type: 'string', required: true , description: 'Stores the product code used to classify, link, or resolve this record.'}, sku: { type: 'string', required: true , description: 'Stores the SKU used to identify the purchasable product or variant.'}, productType: { type: 'string', required: false , description: 'Classifies this record by product type for validation and business handling.'}, fulfillmentStrategy: { type: 'string', required: false , description: 'Stores the fulfillment strategy value used by this record.'}, digitalDeliveryType: { type: 'string', required: false , description: 'Classifies this record by digital delivery type for validation and business handling.'}, digitalBinding: { type: 'object', required: false , description: 'Stores structured digital binding details used by this record.'}, attributes: { type: 'object', required: true , description: 'Stores structured attributes details used by this record.'}, status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} } }),
    productVariantLocalization: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, variantCode: { type: 'string', required: true , description: 'Stores the variant code used to classify, link, or resolve this record.'}, productCode: { type: 'string', required: true , description: 'Stores the product code used to classify, link, or resolve this record.'}, locale: { type: 'string', required: true , description: 'Stores the locale code used for language, formatting, and regional behavior.'}, attributes: { type: 'object', required: true , description: 'Stores structured attributes details used by this record.'}, media: { type: 'object', required: false , description: 'Stores structured media details used by this record.'}, status: { type: 'string', required: true, enum: ['DRAFT', 'READY'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} }, indexes: { composite: { tenant: { enabled: true, name: 'tenant', options: { unique: true } }, variantCode: { enabled: true, name: 'variantCode', options: { unique: true } }, locale: { enabled: true, name: 'locale', options: { unique: true } } } } }),
    category: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, name: { type: 'string', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'}, parentCode: { type: 'string', required: false , description: 'Stores the parent code used to classify, link, or resolve this record.'}, status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} } }),
    categoryLocalization: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, categoryCode: { type: 'string', required: true , description: 'Stores the category code used to classify, link, or resolve this record.'}, locale: { type: 'string', required: true , description: 'Stores the locale code used for language, formatting, and regional behavior.'}, name: { type: 'string', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'}, description: { type: 'string', required: false , description: 'Explains the business purpose, usage, or administrative meaning of this record.'}, slug: { type: 'string', required: false , description: 'Stores the slug value used by this record.'}, seo: { type: 'object', required: false , description: 'Stores structured seo details used by this record.'}, media: { type: 'object', required: false , description: 'Stores structured media details used by this record.'}, status: { type: 'string', required: true, enum: ['DRAFT', 'READY'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} }, indexes: { composite: { tenant: { enabled: true, name: 'tenant', options: { unique: true } }, categoryCode: { enabled: true, name: 'categoryCode', options: { unique: true } }, locale: { enabled: true, name: 'locale', options: { unique: true } } } } }),
    productPublication: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, productCode: { type: 'string', required: true , description: 'Stores the product code used to classify, link, or resolve this record.'}, catalogVersion: { type: 'string', required: true , description: 'Stores the catalog version value used by this record.'}, storeCode: { type: 'string', required: true , description: 'Stores the store code used to classify, link, or resolve this record.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}, status: { type: 'string', required: true, enum: ['STAGED', 'PUBLISHED', 'SUPERSEDED', 'ROLLED_BACK', 'WITHDRAWN'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, sourceHash: { type: 'string', required: true , description: 'Stores a fingerprint of the source data used to detect changes or duplicates.'}, localizationEvidence: { type: 'object', required: true , description: 'Stores structured localization evidence details used by this record.'}, projectionCodes: { type: 'array', required: false , description: 'Lists projection codes used to classify, link, or resolve this record.'}, previousPublicationCode: { type: 'string', required: false , description: 'Stores the previous publication code used to classify, link, or resolve this record.'}, rollbackOf: { type: 'string', required: false , description: 'Stores the rollback of value used by this record.'}, stagedAt: { type: 'date', required: true , description: 'Records when the staged event or value applies.'}, publishedAt: { type: 'date', required: false , description: 'Records when the published event or value applies.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'} } }),
    productSearchProjection: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { search: { enabled: true, idPropertyName: 'code' }, definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, enterpriseCode: { type: 'string', required: false , description: 'Stores the enterprise code used to classify, link, or resolve this record.'}, productCode: { type: 'string', required: true , description: 'Stores the product code used to classify, link, or resolve this record.'}, storeCode: { type: 'string', required: true , description: 'Stores the store code used to classify, link, or resolve this record.'}, locale: { type: 'string', required: true , description: 'Stores the locale code used for language, formatting, and regional behavior.'}, payload: { type: 'object', required: true , description: 'Stores structured payload details used by this record.'}, sourceHash: { type: 'string', required: true , description: 'Stores a fingerprint of the source data used to detect changes or duplicates.'}, status: { type: 'string', required: true, enum: ['CURRENT', 'STALE', 'WITHDRAWN'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, projectedAt: { type: 'date', required: true , description: 'Records when the projected event or value applies.'}, requestedLocale: { type: 'string', required: false , description: 'Stores the requested locale value used by this record.'}, fallbackUsed: { type: 'bool', required: false , description: 'Indicates whether fallback used applies for this record.'} } })
} };
module.exports.product.product.backoffice = { operations: ['search', 'read', 'create', 'update'], description: 'Product sellable master data.' };

// Catalogue source records are authored in Staged; publication evidence is not generic CRUD.
for (const name of ['product', 'productLocalization', 'productVariant', 'productVariantLocalization', 'category', 'categoryLocalization']) {
    const schema = module.exports.product[name];
    schema.backoffice = Object.assign({}, schema.backoffice, {
        mutationPolicy: { lifecycle: 'PUBLISHABLE', publishRequired: true },
    });
}
for (const name of ['productPublication', 'productSearchProjection']) {
    module.exports.product[name].backoffice = { mutationMode: 'READ_ONLY', operations: ['search', 'read'] };
}
