/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module checkoutCore/src/schemas/schemas @description Defines Checkout and cross-domain Commerce operational evidence. @layer schema @owner checkoutCore */
const common = { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, enterpriseCode: { type: 'string', required: false , description: 'Stores the enterprise code used for business ownership, visibility, or settlement decisions.'}, status: { type: 'string', required: true , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to trace related requests, jobs, and events.'} };
module.exports = { checkoutCore: {
    checkoutSession: Object.assign({ super: 'base', model: true, schemaPolicies: ['customerOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: Object.assign({}, common, { ownerId: { type: 'string', required: true , description: 'Identifies the principal or business owner responsible for this record.'}, cartCode: { type: 'string', required: true , description: 'Stores the cart code used to classify, link, or resolve this record.'}, expiresAt: { type: 'date', required: true , description: 'Records when the expires event or value applies.'} }) }),
    checkoutCheckpoint: Object.assign({ super: 'base', model: true, schemaPolicies: ['customerOwned'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: Object.assign({}, common, { ownerId: { type: 'string', required: true , description: 'Identifies the principal or business owner responsible for this record.'}, cartCode: { type: 'string', required: false , description: 'Stores the cart code used to classify, link, or resolve this record.'}, orderCode: { type: 'string', required: false , description: 'Stores the order code used to classify, link, or resolve this record.'}, idempotencyKey: { type: 'string', required: true , description: 'Stores the idempotency key used to prevent duplicate processing of the same business request.'}, evidence: { type: 'object', required: true , description: 'Stores structured evidence that explains how this record or decision was produced.'}, occurredAt: { type: 'date', required: false , description: 'Records when the occurred event or value applies.'} }) }),
    commerceCapacityEvidence: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: Object.assign({}, common, { workload: { type: 'string', required: true , description: 'Stores the workload value used by this record.'}, sampleSize: { type: 'int', required: true , description: 'Stores the sample size used for validation, calculation, or operational decisions.'}, concurrency: { type: 'int', required: true , description: 'Stores the concurrency value used by this record.'}, durationMs: { type: 'int', required: true , description: 'Stores the duration ms value used by this record.'}, throughputPerSecond: { type: 'string', required: true , description: 'Stores the throughput per second value used by this record.'}, p95Ms: { type: 'int', required: true , description: 'Stores the p95 ms value used by this record.'}, errorCount: { type: 'int', required: true , description: 'Stores the error count used for validation, calculation, or operational decisions.'}, budgetVersion: { type: 'string', required: true , description: 'Stores the budget version value used by this record.'}, environment: { type: 'string', required: true , description: 'Stores the environment value used by this record.'}, measuredAt: { type: 'date', required: true , description: 'Records when the measured event or value applies.'}, evidence: { type: 'object', required: true , description: 'Stores structured evidence that explains how this record or decision was produced.'} }) }),
    commerceRecoveryCheckpoint: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: Object.assign({}, common, { workload: { type: 'string', required: true , description: 'Stores the workload value used by this record.'}, partitionKey: { type: 'string', required: true , description: 'Stores the partition key value used by this record.'}, cursor: { type: 'string', required: false , description: 'Stores the cursor value used by this record.'}, processedCount: { type: 'int', required: true , description: 'Stores the processed count used for validation, calculation, or operational decisions.'}, failedCount: { type: 'int', required: true , description: 'Stores the failed count used for validation, calculation, or operational decisions.'}, sourceHash: { type: 'string', required: true , description: 'Stores a fingerprint of the source data used to detect changes or duplicates.'}, checkpointedAt: { type: 'date', required: true , description: 'Records when the checkpointed event or value applies.'} }) }),
    commerceCompatibilityRecord: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: Object.assign({}, common, { contractType: { type: 'string', required: true , description: 'Classifies this record by contract type for validation and business handling.'}, contractCode: { type: 'string', required: true , description: 'Stores the contract code used to classify, link, or resolve this record.'}, version: { type: 'string', required: true , description: 'Stores the version value used by this record.'}, compatibility: { type: 'string', required: true, enum: ['COMPATIBLE', 'DEPRECATED', 'BREAKING'] , description: 'Selects the compatibility value used to drive validation, filtering, and business behavior.'}, successorVersion: { type: 'string', required: false , description: 'Stores the successor version value used by this record.'}, deprecatedAt: { type: 'date', required: false , description: 'Records when the deprecated event or value applies.'}, sunsetAt: { type: 'date', required: false , description: 'Records when the sunset event or value applies.'}, evidence: { type: 'object', required: true , description: 'Stores structured evidence that explains how this record or decision was produced.'} }) }),
    commerceMigrationRecord: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: Object.assign({}, common, { sourceModule: { type: 'string', required: true , description: 'Stores the source module value used by this record.'}, sourceSchema: { type: 'string', required: true , description: 'Stores the source schema value used by this record.'}, sourceCode: { type: 'string', required: true , description: 'Stores the source code used to classify, link, or resolve this record.'}, targetModule: { type: 'string', required: true , description: 'Stores the target module value used by this record.'}, targetSchema: { type: 'string', required: true , description: 'Stores the target schema value used by this record.'}, targetCode: { type: 'string', required: false , description: 'Stores the target code used to classify, link, or resolve this record.'}, sourceHash: { type: 'string', required: true , description: 'Stores a fingerprint of the source data used to detect changes or duplicates.'}, mappingVersion: { type: 'string', required: true , description: 'Stores the mapping version value used by this record.'}, strategy: { type: 'string', required: true, enum: ['DRY_RUN', 'CUTOVER', 'ROLLBACK'] , description: 'Selects the strategy value used to drive validation, filtering, and business behavior.'}, errors: { type: 'array', required: false , description: 'Stores the errors value used by this record.'}, migratedAt: { type: 'date', required: false , description: 'Records when the migrated event or value applies.'} }) })
} };
