/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
'use strict';
/** @module engagementApi/src/router/routers @description Declares secured Engagement API route families without exposing schema CRUD. @layer router @owner engagementApi @override Later modules may add domain routes; anonymous access requires an explicit allow-list and route override. */
module.exports = { engagementApi: {
    publicForms: {
        getActiveForm: { secured: false, accessGroups: ['userGroup'], permission: 'engagement.form.read', apiExposure: 'engagementPublic', key: '/public/forms/:definitionCode', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'getActiveForm' },
        submitContact: { secured: false, accessGroups: ['userGroup'], permission: 'engagement.contact.submit', apiExposure: 'engagementPublic', key: '/public/contact-submissions', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'submitContact' },
        listTestimonials: { secured: false, accessGroups: ['userGroup'], permission: 'engagement.testimonial.public.read', apiExposure: 'engagementPublic', key: '/public/testimonials', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'listTestimonials' },
        submitTestimonialCandidate: { secured: false, accessGroups: ['userGroup'], permission: 'engagement.testimonial.submit', apiExposure: 'engagementPublic', key: '/public/testimonial-candidates', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'submitTestimonialCandidate' }
        , listReviews: { secured: false, accessGroups: ['userGroup'], permission: 'engagement.review.public.read', apiExposure: 'engagementPublic', key: '/public/reviews', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'listReviews' }
        , getReviewAggregate: { secured: false, accessGroups: ['userGroup'], permission: 'engagement.review.public.read', apiExposure: 'engagementPublic', key: '/public/review-aggregates/:targetType/:targetCode', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'getReviewAggregate' }
        , submitFeedback: { secured: false, accessGroups: ['userGroup'], permission: 'engagement.feedback.submit', apiExposure: 'engagementPublic', key: '/public/feedback', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'submitFeedback' }
    },
    customer: {
        listOwnSubmissions: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.customer.read', apiExposure: 'engagementCustomer', key: '/customer/submissions', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'listOwnSubmissions' },
        getOwnSubmission: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.customer.read', apiExposure: 'engagementCustomer', key: '/customer/submissions/:submissionCode', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'getOwnSubmission' },
        getOwnTestimonialConsent: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.testimonial.customer.read', apiExposure: 'engagementCustomer', key: '/customer/testimonial-consents/:consentCode', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'getOwnTestimonialConsent' },
        withdrawOwnTestimonialConsent: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.testimonial.customer.withdraw', apiExposure: 'engagementCustomer', key: '/customer/testimonial-consents/:consentCode/withdraw', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'withdrawOwnTestimonialConsent' }
        , submitReview: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.review.submit', apiExposure: 'engagementCustomer', key: '/customer/reviews', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'submitReview' }
        , listOwnReviews: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.review.customer.read', apiExposure: 'engagementCustomer', key: '/customer/reviews', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'listOwnReviews' }
        , getOwnReview: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.review.customer.read', apiExposure: 'engagementCustomer', key: '/customer/reviews/:reviewCode', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'getOwnReview' }
        , withdrawOwnReview: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.review.withdraw', apiExposure: 'engagementCustomer', key: '/customer/reviews/:reviewCode/withdraw', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'withdrawOwnReview' }
        , reportReviewAbuse: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.review.abuse.report', apiExposure: 'engagementCustomer', key: '/customer/reviews/:reviewCode/abuse-reports', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'reportReviewAbuse' }
        , voteReviewHelpfulness: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.review.helpfulness.vote', apiExposure: 'engagementCustomer', key: '/customer/reviews/:reviewCode/helpfulness', method: 'PUT', controller: 'DefaultEngagementApiController', operation: 'voteReviewHelpfulness' }
        , getOwnReviewRequest: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.review.request.read', apiExposure: 'engagementCustomer', key: '/customer/review-requests/:requestCode', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'getOwnReviewRequest' }
        , startReviewSession: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.review.session.start', apiExposure: 'engagementCustomer', key: '/customer/review-requests/:requestCode/sessions', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'startReviewSession' }
        , listOwnFeedback: { secured: true, authTokenTypes: ['access'], accessGroups: ['customerUserGroup'], permission: 'engagement.feedback.customer.read', apiExposure: 'engagementCustomer', key: '/customer/feedback', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'listOwnFeedback' }
    },
    operator: {
        listSubmissions: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.operator.read', apiExposure: 'engagementManagement', key: '/operator/submissions', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'listSubmissions' },
        getSubmission: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.operator.read', apiExposure: 'engagementManagement', key: '/operator/submissions/:submissionCode', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'getSubmission' },
        actOnContact: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.operator.act', apiExposure: 'engagementManagement', key: '/operator/contact-submissions/:submissionCode/actions/:actionCode', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'actOnContact' },
        runHandoffRecovery: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.handoff.recover', apiExposure: 'engagementManagement', key: '/operator/handoffs/recovery/run', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'runHandoffRecovery' },
        retryHandoff: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.handoff.recover', apiExposure: 'engagementManagement', key: '/operator/handoffs/:handoffCode/retry', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'retryHandoff' },
        reconcileHandoff: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.handoff.reconcile', apiExposure: 'engagementManagement', key: '/operator/handoffs/:handoffCode/reconcile', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'reconcileHandoff' },
        actOnTestimonial: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.testimonial.act', apiExposure: 'engagementManagement', key: '/operator/testimonials/:testimonialCode/actions/:actionCode', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'actOnTestimonial' }
        , moderateReview: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.review.moderate', apiExposure: 'engagementManagement', key: '/operator/reviews/:reviewCode/actions/:actionCode', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'moderateReview' }
        , previewCresMigration: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.review.migrate', apiExposure: 'engagementManagement', key: '/operator/reviews/migrations/cres/preview', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'previewCresMigration' }
        , listFeedback: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.feedback.read', apiExposure: 'engagementManagement', key: '/operator/feedback', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'listFeedback' }
        , actOnFeedback: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.feedback.act', apiExposure: 'engagementManagement', key: '/operator/feedback/:feedbackCode/actions/:actionCode', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'actOnFeedback' }
        , classifyFeedback: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.feedback.classify', apiExposure: 'engagementManagement', key: '/operator/feedback/:feedbackCode/classifications', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'classifyFeedback' }
        , deriveFeedbackInsight: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.feedback.insight', apiExposure: 'engagementManagement', key: '/operator/feedback-insights', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'deriveFeedbackInsight' }
        , listUnifiedQueue: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.operations.read', apiExposure: 'engagementManagement', key: '/operator/operations/queue', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'listUnifiedQueue' }
        , getEngagementDashboard: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.operations.read', apiExposure: 'engagementManagement', key: '/operator/operations/dashboards/:dashboardCode', method: 'GET', controller: 'DefaultEngagementApiController', operation: 'getEngagementDashboard' }
        , previewEngagementBatch: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.operations.batch', apiExposure: 'engagementManagement', key: '/operator/operations/batches/preview', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'previewEngagementBatch' }
        , previewEngagementExport: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.operations.export', apiExposure: 'engagementManagement', key: '/operator/operations/exports/preview', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'previewEngagementExport' }
        , previewEngagementRepair: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.operations.repair', apiExposure: 'engagementManagement', key: '/operator/operations/repairs/:itemCode/preview', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'previewEngagementRepair' }
        , executeEngagementBatch: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.operations.batch.execute', apiExposure: 'engagementManagement', key: '/operator/operations/batches/execute', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'executeEngagementBatch' }
        , executeEngagementExport: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.operations.export.execute', apiExposure: 'engagementManagement', key: '/operator/operations/exports/execute', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'executeEngagementExport' }
        , executeEngagementRepair: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.operations.repair.execute', apiExposure: 'engagementManagement', key: '/operator/operations/repairs/:itemCode/execute', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'executeEngagementRepair' }
        , executeEngagementPrivacy: { secured: true, authTokenTypes: ['access'], accessGroups: ['employeeUserGroup'], permission: 'engagement.privacy.execute', apiExposure: 'engagementManagement', key: '/operator/privacy/:domainType/:domainCode/actions/:privacyAction', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'executeEngagementPrivacy' }
    },
    integration: {
        receiveCallback: { secured: true, authTokenTypes: ['service'], accessGroups: ['serviceAccountUserGroup'], permission: 'engagement.integration.callback', apiExposure: 'engagementIntegration', key: '/integrations/:providerCode/callback', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'receiveCallback' },
        createReviewRequest: { secured: true, authTokenTypes: ['service'], accessGroups: ['serviceAccountUserGroup'], permission: 'engagement.review.request.create', apiExposure: 'engagementIntegration', key: '/integrations/review-requests', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'createReviewRequest' },
        importSyndicatedReview: { secured: true, authTokenTypes: ['service'], accessGroups: ['serviceAccountUserGroup'], permission: 'engagement.review.syndication.import', apiExposure: 'engagementIntegration', key: '/integrations/:providerCode/reviews', method: 'POST', controller: 'DefaultEngagementApiController', operation: 'importSyndicatedReview' }
    }
} };
