/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module order/src/schemas/schemas @description Defines governed Commerce lifecycle evidence. @layer schema @owner order */
const internal = policy => ({ super: 'base', model: true, schemaPolicies: [policy], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } });
module.exports = { order: {
    commerceOrder: Object.assign(internal('operational'), { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false }, currency: { type: 'string', required: false }, totalAmount: { type: 'string', required: false } } }),
    commerceOrderEntry: Object.assign(internal('operational'), { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false }, productCode: { type: 'string', required: false }, sku: { type: 'string', required: false }, quantity: { type: 'string', required: false }, unitAmount: { type: 'string', required: false } } }),
    orderHistory: Object.assign(internal('operational'), { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false } } }),
    orderLifecycleRequest: Object.assign(internal('operational'), { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false }, requestType: { type: 'string', required: false }, reasonCode: { type: 'string', required: false } } }),
    orderLifecycleVersion: Object.assign(internal('operational'), { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false }, requestType: { type: 'string', required: false }, reasonCode: { type: 'string', required: false } } }),
    orderReversalCalculation: Object.assign(internal('operational'), { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false } } }),
    orderLifecycleCheckpoint: Object.assign(internal('operational'), { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false }, requestType: { type: 'string', required: false }, reasonCode: { type: 'string', required: false } } })
} };
module.exports.order.commerceOrder.backoffice = { operations: ['search', 'read'], description: 'Immutable order projection.' };
module.exports.order.orderLifecycleRequest.backoffice = { operations: ['search', 'read'], description: 'Order-owned cancellation, return, and refund workflow evidence.' };
