/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module inventory/src/schemas/schemas @description Defines governed Phase 2 inventory persistence and decision evidence. @layer schema @owner inventory */
module.exports = { inventory: {
    warehouse: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { backoffice: { operations: ['search', 'read', 'create', 'update'], description: 'Warehouse master data and sourcing priority.' }, definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, enterpriseCode: { type: 'string', required: false , description: 'Stores the enterprise code used to classify, link, or resolve this record.'}, name: { type: 'string', required: true , description: 'Stores the business display name shown to administrators and related user journeys.'}, status: { type: 'string', required: true, enum: ['ACTIVE', 'INACTIVE'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, priority: { type: 'int', required: true , description: 'Stores the numeric priority used by this record.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} } }),
    inventoryBalance: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { backoffice: { operations: ['search', 'read'], description: 'Derived stock balance by warehouse and SKU. Mutations require Inventory-owned operations.' }, definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, enterpriseCode: { type: 'string', required: false , description: 'Stores the enterprise code used to classify, link, or resolve this record.'}, warehouseCode: { type: 'string', required: true , description: 'Stores the warehouse code used to classify, link, or resolve this record.'}, sku: { type: 'string', required: true , description: 'Stores the SKU used to identify the purchasable product or variant.'}, inventoryStrategy: { type: 'string', required: false , description: 'Stores the inventory strategy value used by this record.'}, digitalDeliveryType: { type: 'string', required: false , description: 'Classifies this record by digital delivery type for validation and business handling.'}, couponBatchCode: { type: 'string', required: false , description: 'Stores the coupon batch code used to classify, link, or resolve this record.'}, promotionCode: { type: 'string', required: false , description: 'Stores the promotion code used to classify, link, or resolve this record.'}, onHand: { type: 'string', required: true , description: 'Stores the on hand value used by this record.'}, reserved: { type: 'string', required: true , description: 'Stores the reserved value used by this record.'}, allocated: { type: 'string', required: true , description: 'Stores the allocated value used by this record.'}, available: { type: 'string', required: true , description: 'Stores the available value used by this record.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'} } }),
    inventoryReservation: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { backoffice: { operations: ['search', 'read'], description: 'Reservation evidence owned by Inventory lifecycle services.' }, definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, enterpriseCode: { type: 'string', required: false , description: 'Stores the enterprise code used to classify, link, or resolve this record.'}, warehouseCode: { type: 'string', required: true , description: 'Stores the warehouse code used to classify, link, or resolve this record.'}, sku: { type: 'string', required: true , description: 'Stores the SKU used to identify the purchasable product or variant.'}, ownerType: { type: 'string', required: true, enum: ['CART', 'ORDER'] , description: 'Classifies the type of owner responsible for this record.'}, ownerCode: { type: 'string', required: true , description: 'Stores the owner code used to classify, link, or resolve this record.'}, quantity: { type: 'string', required: true , description: 'Stores the quantity value used by this record.'}, status: { type: 'string', required: true, enum: ['ACTIVE', 'CONSUMED', 'RELEASED', 'EXPIRED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, expiresAt: { type: 'date', required: false , description: 'Records when the expires event or value applies.'}, idempotencyKey: { type: 'string', required: true , description: 'Stores the idempotency key value used by this record.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'} } }),
    inventoryMovement: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { backoffice: { operations: ['search', 'read'], description: 'Append-only stock movement evidence.' }, definition: { code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, warehouseCode: { type: 'string', required: true , description: 'Stores the warehouse code used to classify, link, or resolve this record.'}, sku: { type: 'string', required: true , description: 'Stores the SKU used to identify the purchasable product or variant.'}, quantity: { type: 'string', required: true , description: 'Stores the quantity value used by this record.'}, movementType: { type: 'string', required: true, enum: ['RECEIPT', 'RESERVE', 'RELEASE', 'ALLOCATE', 'SHIP', 'RETURN', 'ADJUST'] , description: 'Classifies this record by movement type for validation and business handling.'}, referenceCode: { type: 'string', required: true , description: 'Stores the reference code used to classify, link, or resolve this record.'}, balanceRevision: { type: 'int', required: true , description: 'Stores the numeric balance revision used by this record.'}, occurredAt: { type: 'date', required: true , description: 'Records when the occurred event or value applies.'}, correlationId: { type: 'string', required: true , description: 'Stores the correlation identifier used to correlate this record.'} } })
} };
