/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/* Nodics source-available software. See root LICENSE. */
/** @module inventory/service/DefaultInventoryBackofficeCapabilityService @description Publishes Inventory-owned BackOffice balance, warehouse, reservation, and movement workspaces. @layer service @owner inventory */
module.exports={init:function(){SERVICE.DefaultModuleRegistrationAgentService.registerBackofficeCapabilityProvider('inventory',this);return Promise.resolve(true);},postInit:function(){return Promise.resolve(true);},getCapability:function(){let d=SERVICE.DefaultBackofficeCapabilityDefinitionService;let entry=(id,parentId,label,route,schemaName,order,summary,presentation)=>d.workbench({id:id,parentId:parentId,label:label,route:route,moduleName:'inventory',schemaName:schemaName,order:order,permission:'commerce.inventory.read',summary:summary,presentation:presentation,group:id==='inventory-operations'?{id:'commerce',label:'Commerce',order:300}:undefined});return d.capability({capabilityId:'commerce-inventory',displayName:'Inventory Operations',category:'commerce',icon:'commerce',navigation:[entry('inventory-operations',undefined,'Inventory Operations','/commerce/inventory','inventoryBalance',200,'Review current stock availability and move through the complete Inventory operating journey.',{defaultColumns:['code','warehouseCode','sku','onHand','reserved','allocated','available','revision']}),entry('inventory-warehouses','inventory-operations','Warehouses','/commerce/inventory/warehouses','warehouse',210,'Review active warehouse locations and their sourcing priority.',{defaultColumns:['code','name','status','priority','revision']}),entry('inventory-balances','inventory-operations','Stock Balances','/commerce/inventory/balances','inventoryBalance',220,'Inspect on-hand, reserved, allocated, and available stock.',{defaultColumns:['code','warehouseCode','sku','onHand','reserved','allocated','available','revision']}),entry('inventory-reservations','inventory-operations','Reservations','/commerce/inventory/reservations','inventoryReservation',230,'Diagnose cart and order reservations, expiry, and idempotency evidence.',{defaultColumns:['code','warehouseCode','sku','ownerType','ownerCode','quantity','status','expiresAt'],hiddenFields:['idempotencyKey','correlationId']}),entry('inventory-movements','inventory-operations','Stock Movements','/commerce/inventory/movements','inventoryMovement',240,'Trace receipts, reservations, releases, allocations, shipments, returns, and adjustments.',{defaultColumns:['code','movementType','warehouseCode','sku','quantity','referenceCode','balanceRevision','occurredAt'],hiddenFields:['correlationId']})]});}};
