/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module wasteVerification/config/properties @description Provides Waste Verification schema policy defaults. @layer config @owner wasteVerification @override Partner modules may tune review policy. */
module.exports = {
    waste: { reviewWorkspace: {
        descriptorOptions: require('../../wasteMaterial/src/utils/descriptorDefinitions'),
        defaultPageSize: 25, maximumPageSize: 100, maximumPage: 10000, maximumQueryLength: 120,
        dashboardLabels: { title: 'Waste operations', subtitle: 'From submitted item to reviewed asset. Understand activity, prioritize the queue and make informed decisions.', total: 'Total submissions', pending: 'Awaiting review', approved: 'Approved', rejected: 'Rejected', trend: 'Submission activity', distribution: 'Review outcomes', filters: 'Refine your view', dateFrom: 'Submitted from', dateTo: 'Submitted until', family: 'Waste family', area: 'Area / city', channel: 'Channel', size: 'Handling size', all: 'All', apply: 'Apply filters', reset: 'Clear filters', review: 'Review workspace', detail: 'Item evidence and properties', materials: 'Materials and components', environment: 'Environmental observations', physical: 'Physical properties', customerFacts: 'Customer-confirmed details', correction: 'Review and correct properties', unknown: 'Not established', centre: 'Collection centre', weightEstimate: 'Approximate weight (kg)', length: 'Length (cm)', width: 'Width (cm)', height: 'Height (cm)', min: 'From', max: 'To', recyclability: 'Recyclability', contamination: 'Visible contamination', recoveryPotential: 'Material recovery potential', hazards: 'Hazard observations', dateBasis: 'Submission dates use UTC.', noActivity: 'No activity for this period.', noSelection: 'Choose a submission to review its evidence and properties.', original: 'Original confirmed facts', proposed: 'Your proposed changes', confirmation: 'Check these changes before saving. The original submission remains in the audit record.' },
        fields: [{key:'description',label:'Verified description',type:'text'},{key:'categoryCode',label:'Verified category',type:'string'},{key:'itemTypeCode',label:'Verified item type',type:'string'},{key:'quantity',label:'Verified quantity',type:'number'},{key:'conditionGrade',label:'Verified condition',type:'string'},{key:'brand',label:'Verified brand',type:'string'},{key:'model',label:'Verified model',type:'string'},{key:'weight',label:'Measured weight (kg)',type:'string'},{key:'sizeClass',label:'Handling size',type:'string'}],
        statuses: [{code:'OPEN',label:'Pending and under review'},{code:'SUBMITTED',label:'Pending'},{code:'UNDER_REVIEW',label:'Under review'},{code:'APPROVED',label:'Approved'},{code:'REJECTED',label:'Rejected'},{code:'ALL',label:'All submissions'}],
        labels: { readOnlyMode: 'Read-only preview', assignmentRequired: 'Assign this submission to yourself to edit its properties and record your review.', assignedToYou: 'Assigned to you', assignmentOwned: 'You are responsible for this review. Your permissions determine which actions are available.', assignmentElsewhere: 'This submission is read-only while another employee is reviewing it.', assigning: 'Assigning…', releasing: 'Returning to queue…', assignmentSaved: 'Assigned to you. Review actions are now available according to your permissions.', releaseSaved: 'Returned to the review queue. These details are now read-only.', assignmentFailed: 'Assignment could not be updated. Please try again.', releaseDirty: 'Save or discard your changes before returning this review to the queue.', reviewComplete: 'Review completed', completedReadOnly: 'The reviewed item properties are read-only.', resultsUnavailable: 'Results unavailable. Adjust the search or retry.', advancedSearch: 'Advanced search', clearAll: 'Clear all', details: 'Submission details', close: 'Close details', openDetails: 'Open details', expandSummary: 'Expand summary', collapseSummary: 'Collapse summary', summary: 'Summary', noDescription: 'No description provided.', customer: 'Customer', quantity: 'Quantity', condition: 'Condition', reference: 'Reference', itemName: 'Item name', itemType: 'Item type', submittedAt: 'Submitted at', feedback: 'Review feedback', export: 'Export', exporting: 'Exporting…', exportChanged: 'Submissions changed during export. Please retry.', loading: 'Loading submissions…', submissions: 'submissions', page: 'page', status: 'Submission status', search: 'Search submissions', centre: 'Collection centre code', previous: 'Previous', next: 'Next', assign: 'Assign to me', release: 'Return to review queue', assignedTo: 'Assigned reviewer', queued: 'Review queue', outcome: 'Customer feedback', noResults: 'No submissions match these filters.', searchAction: 'Search', verifiedFacts: 'Verified item details' }
    } }, schemaPolicies: { wasteVerification: { operational: { accessGroups: { adminGroup: 10, serviceAccountUserGroup: 10, employeeUserGroup: 10 } } } } };
