/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/**
 * @module apparelProduct/src/schemas/schemas
 * @description Schema definition registry for this boundary.
 * @layer definition
 * @owner generated
 * @override Later active modules may extend or replace this registry through Nodics layering.
 */
module.exports = { apparelProduct: {
    apparelStyle: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, productCode: { type: 'string', required: true , description: 'Stores the product code used to classify, link, or resolve this record.'}, brandCode: { type: 'string', required: false , description: 'Stores the brand code used to classify, link, or resolve this record.'},
        collectionCodes: { type: 'array', required: false , description: 'Lists collection codes used to classify, link, or resolve this record.'}, seasonCode: { type: 'string', required: false , description: 'Stores the season code used to classify, link, or resolve this record.'}, genderAudience: { type: 'array', required: false , description: 'Lists the gender audience associated with this record.'}, ageGroup: { type: 'string', required: false , description: 'Stores the age group value used by this record.'},
        fitProfileCode: { type: 'string', required: false , description: 'Stores the fit profile code used to classify, link, or resolve this record.'}, sizeSystemCode: { type: 'string', required: true , description: 'Stores the size system code used to classify, link, or resolve this record.'}, materialComposition: { type: 'array', required: false , description: 'Lists the material composition associated with this record.'}, careInstructions: { type: 'array', required: false , description: 'Lists the care instructions associated with this record.'},
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}
    }, indexes: { composite: { tenant: { enabled: true, name: 'tenant', options: { unique: true } }, productCode: { enabled: true, name: 'productCode', options: { unique: true } } } } }),
    apparelVariantProfile: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, productCode: { type: 'string', required: true , description: 'Stores the product code used to classify, link, or resolve this record.'}, variantCode: { type: 'string', required: true , description: 'Stores the variant code used to classify, link, or resolve this record.'},
        colourCode: { type: 'string', required: true , description: 'Stores the colour code used to classify, link, or resolve this record.'}, colourFamily: { type: 'string', required: false , description: 'Stores the colour family value used by this record.'}, swatchMediaCode: { type: 'string', required: false , description: 'Stores the swatch media code used to classify, link, or resolve this record.'}, sizeCode: { type: 'string', required: true , description: 'Stores the size code used to classify, link, or resolve this record.'},
        sizeSystemCode: { type: 'string', required: true , description: 'Stores the size system code used to classify, link, or resolve this record.'}, fitCode: { type: 'string', required: false , description: 'Stores the fit code used to classify, link, or resolve this record.'}, status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}
    }, indexes: { composite: { tenant: { enabled: true, name: 'tenant', options: { unique: true } }, variantCode: { enabled: true, name: 'variantCode', options: { unique: true } } } } }),
    apparelSizeSystem: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, systemType: { type: 'string', required: true, enum: ['ALPHA', 'EU', 'UK', 'US', 'AGE', 'ONE_SIZE'] , description: 'Classifies this record by system type for validation and business handling.'},
        sizeCodes: { type: 'array', required: true , description: 'Lists size codes used to classify, link, or resolve this record.'}, measurements: { type: 'object', required: false , description: 'Stores structured measurements details used by this record.'}, localeLabels: { type: 'object', required: false , description: 'Stores structured locale labels details used by this record.'}, status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}
    } }),
    apparelFitProfile: Object.assign({ super: 'base', model: true, schemaPolicies: ['tenantOwned'], service: { enabled: true }, router: { groups: { schemaOperations: true }, enabled: true }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: {
        code: { type: 'string', required: true , description: 'Uniquely identifies this record for references, APIs, imports, and business administration.'}, tenant: { type: 'string', required: true , description: 'Identifies the runtime tenant partition that scopes this record.'}, fitType: { type: 'string', required: true , description: 'Classifies this record by fit type for validation and business handling.'}, guidance: { type: 'object', required: false , description: 'Stores structured guidance details used by this record.'},
        status: { type: 'string', required: true, enum: ['DRAFT', 'ACTIVE', 'ARCHIVED'] , description: 'Tracks the lifecycle state that controls whether this record can be used in business processes.'}, revision: { type: 'int', required: true , description: 'Tracks the business revision used for governance, review, and optimistic update checks.'}
    } })
} };
