/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
const crypto = require('crypto');
/** @module engagementCore/src/service/defaultEngagementUnifiedOperationsService @description Builds read-only cross-domain operational projections, guarded batch previews, repair cases, dashboards, and export evidence. @layer service @owner engagementCore @override Projects may replace search/export adapters while domain commands remain routed to owning modules. */
module.exports = {
    /** Builds one rebuildable queue projection from a domain-owned safe projection. */ project: function (domainType, record, options) { options = options || {}; let summary = options.summary || {}; let sourceHash = crypto.createHash('sha256').update(JSON.stringify({ domainType: domainType, code: record.code, revision: record.revision, status: record.status, summary: summary })).digest('hex'); return { tenant: record.tenant, domainType: domainType, domainCode: record.code, sourceRevision: Number(record.revision || 0), sourceHash: sourceHash, status: record.status, queueCode: record.queueCode, assigneeId: record.assigneeId, priority: record.priority || record.priorityCode, dueAt: record.dueAt, summary: summary, relatedRecords: options.relatedRecords || [], consentFlags: options.consentFlags || {}, integrationStatus: options.integrationStatus, projectedAt: options.now || new Date(), correlationId: record.correlationId }; },
    /** Rebuilds projections and identifies drift without mutating domain records. */ rebuild: function (sources, existing, projector) { let built = (sources || []).map(source => projector(source)); let prior = new Map((existing || []).map(item => [item.domainType + ':' + item.domainCode, item])); let drift = built.filter(item => { let found = prior.get(item.domainType + ':' + item.domainCode); return !found || found.sourceHash !== item.sourceHash; }); return { items: built, drift: drift, removed: (existing || []).filter(item => !built.some(next => next.domainType === item.domainType && next.domainCode === item.domainCode)) }; },
    /** Produces a non-executable batch command preview for domain gateways. */ batchPreview: function (selection, command, policy) { policy = policy || {}; if (!(selection || []).length || selection.length > Number(policy.maximumBatchSize || 100)) throw new Error('batch selection is empty or exceeds policy'); if (!command.reason) throw new Error('batch reason is required'); return { preview: true, count: selection.length, commands: selection.map(item => ({ domainType: item.domainType, domainCode: item.domainCode, action: command.action, expectedRevision: item.sourceRevision, reason: command.reason })), requiresApproval: true, directMutation: false }; },
    /** Builds dashboard metrics from queue projections. */ dashboard: function (tenant, code, items, options) { options = options || {}; let metrics = (items || []).reduce((result, item) => { result.total += 1; result.byDomain[item.domainType] = Number(result.byDomain[item.domainType] || 0) + 1; result.byStatus[item.status] = Number(result.byStatus[item.status] || 0) + 1; if (item.dueAt && new Date(item.dueAt) < (options.now || new Date())) result.overdue += 1; return result; }, { total: 0, overdue: 0, byDomain: {}, byStatus: {} }); return { tenant: tenant, dashboardCode: code, filters: options.filters, metrics: metrics, sourceHashes: Object.fromEntries((items || []).map(item => [item.domainType + ':' + item.domainCode, item.sourceHash])), policyVersion: options.policyVersion || '1', calculatedAt: options.now || new Date(), status: 'CURRENT', correlationId: options.correlationId }; },
    /** Creates audited, masked, bounded export evidence instead of exporting directly. */ exportPreview: function (tenant, items, command, policy) { policy = policy || {}; let fields = (command.fields || []).filter(field => (policy.allowedExportFields || []).includes(field)); let limit = Number(policy.maximumExportRecords || 10000); if (!command.purpose || fields.length === 0) throw new Error('export purpose and allowed fields are required'); return { tenant: tenant, purpose: command.purpose, requestedBy: command.actorId, filters: command.filters || {}, fields: fields, maskingPolicy: policy.maskingPolicy, recordCount: Math.min((items || []).length, limit), maximumRecords: limit, status: 'PREVIEWED', correlationId: command.correlationId }; },
    /** Creates a governed repair case that invokes the domain owner only after approval. */ repair: function (item, command) { return { tenant: item.tenant, domainType: item.domainType, domainCode: item.domainCode, repairType: command.repairType, expectedSourceHash: command.expectedSourceHash, observedSourceHash: item.sourceHash, status: 'PREVIEWED', reason: command.reason, requestedBy: command.actorId, correlationId: command.correlationId || item.correlationId }; }
};
