/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
'use strict';
const crypto = require('crypto');
/** @module engagementCore/src/service/defaultEngagementResilienceService @description Defines bounded pagination, residency, signed delivery, backpressure, retry, recovery checkpoint, and compatibility evidence for enterprise Engagement workloads. @layer service @owner engagementCore @override Providers and projects may replace transport/storage adapters while preserving these safety invariants. */
module.exports = {
    /** Enforces bounded cursor pagination. */ page: function (query, policy) { let limit = Math.max(1, Math.min(Number(query && query.limit || 25), Number(policy.maximumPageSize || 100))); return { limit: limit, cursor: query && query.cursor, sort: query && query.sort || 'createdAt:asc,code:asc' }; },
    /** Validates that a workload remains in an allowed residency region. */ assertRegion: function (region, policy) { region = region || policy.defaultRegion; if (!(policy.allowedRegions || []).includes(region)) throw new Error('engagement region is not allowed by residency policy'); return region; },
    /** Produces a provider-neutral HMAC signature without exposing the secret. */ sign: function (body, timestamp, secret, policy) { if (!secret) throw new Error('webhook signing secret is required'); let payload = String(timestamp) + '.' + JSON.stringify(body); return crypto.createHmac((policy.webhook || {}).signatureAlgorithm || 'sha256', secret).update(payload).digest('hex'); },
    /** Verifies signature and replay window for inbound or outbound webhook evidence. */ verify: function (body, timestamp, signature, secret, now, policy) { let age = Math.abs(Number(now || Date.now()) - Number(timestamp)); if (age > Number((policy.webhook || {}).replayWindowSeconds || 300) * 1000) return false; let expected = this.sign(body, timestamp, secret, policy); let supplied = Buffer.from(String(signature)); let calculated = Buffer.from(expected); return supplied.length === calculated.length && crypto.timingSafeEqual(supplied, calculated); },
    /** Returns exponential retry evidence with bounded jitter-free scheduling for deterministic tests. */ retry: function (attempt, now, policy) { let maximum = Number(policy.maximumDeliveryAttempts || 5); let nextAttempt = Number(attempt || 0) + 1; if (nextAttempt >= maximum) return { attempt: nextAttempt, maximumAttempts: maximum, status: 'DEAD_LETTER' }; let delay = Math.min(Number(policy.maximumRetryMilliseconds || 300000), Number(policy.baseRetryMilliseconds || 1000) * Math.pow(2, Math.max(0, nextAttempt - 1))); return { attempt: nextAttempt, maximumAttempts: maximum, status: 'RETRY_PENDING', nextAttemptAt: new Date(Number(now || Date.now()) + delay) }; },
    /** Applies a hard in-flight limit for provider backpressure. */ capacity: function (inFlight, policy) { let maximum = Number(policy.maximumInFlightDeliveries || 25); return { accepted: Number(inFlight || 0) < maximum, inFlight: Number(inFlight || 0), maximumInFlight: maximum, status: Number(inFlight || 0) < maximum ? 'AVAILABLE' : 'BACKPRESSURE' }; },
    /** Creates restart-safe recovery evidence without copying domain payloads. */ checkpoint: function (command, policy) { let region = this.assertRegion(command.region, policy); return { tenant: command.tenant, workloadCode: command.workloadCode, partitionKey: command.partitionKey, region: region, cursor: command.cursor, sourceHash: command.sourceHash, processedCount: Number(command.processedCount || 0), failedCount: Number(command.failedCount || 0), status: command.status || 'CURRENT', startedAt: command.startedAt, checkpointedAt: command.now || new Date(), correlationId: command.correlationId }; },
    /** Evaluates a version against supported majors and minimum deprecation notice. */ compatibility: function (command, policy) { let major = Number(String(command.version).split('.')[0]); let supported = (policy.compatibility || {}).supportedMajorVersions || []; let compatibility = supported.includes(major) ? 'CURRENT' : 'BREAKING'; if (command.deprecatedAt && command.sunsetAt) { let days = (new Date(command.sunsetAt) - new Date(command.deprecatedAt)) / 86400000; if (days < Number((policy.compatibility || {}).minimumDeprecationDays || 180)) throw new Error('deprecation window is below compatibility policy'); compatibility = 'DEPRECATED'; } return Object.assign({}, command, { compatibility: compatibility, evaluatedAt: command.now || new Date() }); }
};
