/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
'use strict';
const crypto = require('crypto');
/** @module engagementCore/src/service/defaultEngagementAutomationGovernanceService @description Governs optional AI and deterministic automation proposals, evaluation evidence, human review, override, and safe fallback. @layer service @owner engagementCore @override Projects may replace adapters while preserving evidence, evaluation, fallback, and no-direct-action rules. */
module.exports = {
    /** Rejects protected inputs and returns stable source evidence. */ evidence: function (record, policy) { let prohibited = (policy || {}).prohibitedInputFields || []; let leaked = prohibited.filter(field => Object.prototype.hasOwnProperty.call(record || {}, field)); if (leaked.length) throw new Error('automation input contains prohibited fields'); return { sourceRevision: Number(record.revision || 0), sourceHash: crypto.createHash('sha256').update(JSON.stringify(record)).digest('hex') }; },
    /** Creates an advisory proposal from a replaceable adapter or deterministic fallback. */ propose: async function (capability, record, context, adapter, fallback, policy) { policy = policy || {}; let evidence = this.evidence(record, policy); let source = adapter && policy.aiEnabled ? 'AI' : 'RULE'; let result; try { result = source === 'AI' ? await adapter.propose(capability, record, context) : await fallback(capability, record, context); } catch (error) { if (!policy.deterministicFallbackRequired) throw error; source = 'RULE'; result = await fallback(capability, record, Object.assign({}, context, { fallbackReason: error.code || error.message })); } let confidence = Math.max(0, Math.min(1, Number(result.confidence || 0))); let reviewRequired = (policy.humanReviewCapabilities || []).includes(capability) || confidence < Number(policy.minimumConfidence || 0.75); return { tenant: context.tenant, capability: capability, domainType: context.domainType, domainCode: record.code, sourceRevision: evidence.sourceRevision, sourceHash: evidence.sourceHash, output: result.output || {}, confidence: confidence, source: source, providerCode: source === 'AI' ? result.providerCode : undefined, modelReference: source === 'AI' ? result.modelReference : undefined, promptVersion: source === 'AI' ? result.promptVersion : undefined, policyVersion: policy.policyVersion || '1', status: reviewRequired ? 'REVIEW_REQUIRED' : 'PROPOSED', explanation: result.explanation, decidedAt: context.now || new Date(), correlationId: context.correlationId, directActionAllowed: false }; },
    /** Applies an explicit human disposition without executing a domain action. */ review: function (decision, command) { if (!command.actorId || !command.reason || !['ACCEPTED', 'OVERRIDDEN', 'REJECTED'].includes(command.status)) throw new Error('valid human review actor, reason, and status are required'); return Object.assign({}, decision, { output: command.status === 'OVERRIDDEN' ? command.output : decision.output, status: command.status, reviewedBy: command.actorId, reviewReason: command.reason, reviewedAt: command.now || new Date(), directActionAllowed: false }); },
    /** Evaluates one versioned automation capability against governed thresholds. */ evaluate: function (command, policy) { let evaluation = (policy || {}).evaluation || {}; if (Number(command.sampleSize || 0) < Number(evaluation.minimumSampleSize || 1)) throw new Error('evaluation sample is below policy minimum'); let metrics = command.metrics || {}; (evaluation.requiredMetrics || []).forEach(metric => { if (!Number.isFinite(Number(metrics[metric]))) throw new Error('required evaluation metric missing: ' + metric); }); let passed = Number(metrics.errorRate || 0) <= Number(evaluation.maximumErrorRate || 0.1) && (evaluation.requiredMetrics || []).every(metric => Number(metrics[metric]) >= Number((command.thresholds || {})[metric] || 0)); return Object.assign({}, command, { policyVersion: (policy || {}).policyVersion || '1', passed: passed, evaluatedAt: command.now || new Date() }); },
    /** Declares operational posture without making AI a runtime dependency. */ availability: function (adapter, policy) { return { aiConfigured: Boolean(adapter), aiEnabled: Boolean(adapter && policy && policy.aiEnabled), deterministicFallback: Boolean(policy && policy.deterministicFallbackRequired), directActionAllowed: false }; }
};
