/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module engagementCore/src/service/defaultEngagementOperationsApiService @description Provides secured read, preview, repair, and export operations over rebuildable Engagement projections. @layer service @owner engagementCore @override Storage/search/export adapters may replace retrieval while domain mutations remain domain-owned. */
module.exports = {
    /** Returns the unified-operations policy. */ policy: function () { return (CONFIG.get('engagementCore') || {}).unifiedOperations || {}; },
    /** Removes transport controls before applying domain filters. */ filters: function (query) { let value = Object.assign({}, query || {}); ['limit', 'offset', 'page', 'pageSize', 'sort'].forEach(key => delete value[key]); return value; },
    /** Lists a bounded tenant-scoped unified queue. */ listQueue: function (request) { return SERVICE.DefaultEngagementUnifiedQueueItemService.get({ tenant: request.tenant, authData: request.authData, query: Object.assign({ tenant: request.tenant }, this.filters(request.query)), searchOptions: { limit: Math.min(Number(request.query && request.query.limit || 25), 100) } }).then(response => response.result || []); },
    /** Calculates a rebuildable dashboard from the authorized queue page. */ dashboard: async function (request) { let items = await this.listQueue(request); return SERVICE.DefaultEngagementUnifiedOperationsService.dashboard(request.tenant, request.dashboardCode || 'operations', items, { filters: request.query, policyVersion: this.policy().policyVersion, correlationId: request.correlationId || request.requestId }); },
    /** Previews a bounded batch of domain-owned commands without executing them. */ batchPreview: async function (request) { let itemCodes = request.payload.itemCodes || []; let items = await this.listQueue(Object.assign({}, request, { query: { limit: this.policy().maximumBatchSize } })); items = items.filter(item => itemCodes.includes(item.code)); return SERVICE.DefaultEngagementUnifiedOperationsService.batchPreview(items, request.payload, this.policy()); },
    /** Previews a masked export and returns auditable evidence. */ exportPreview: async function (request) { let items = await this.listQueue(request); return SERVICE.DefaultEngagementUnifiedOperationsService.exportPreview(request.tenant, items, Object.assign({}, request.payload, { actorId: request.authData && (request.authData.principalId || request.authData.code), correlationId: request.correlationId || request.requestId }), this.policy()); },
    /** Creates a repair preview against one projection; domain execution requires a later approval action. */ repairPreview: async function (request) { let values = await this.listQueue(Object.assign({}, request, { query: { code: request.itemCode, limit: 1 } })); if (!values[0]) throw new Error('unified queue item not found'); return SERVICE.DefaultEngagementUnifiedOperationsService.repair(values[0], Object.assign({}, request.payload, { actorId: request.authData && (request.authData.principalId || request.authData.code), correlationId: request.correlationId || request.requestId })); }
    , executionPorts: function (request) { let domain = SERVICE.DefaultEngagementOperationsDomainCommandService; let evidence = SERVICE.DefaultEngagementOperationsEvidenceRepositoryService; return { dispatch: command => domain.dispatch(command, request), findReceipt: (tenant, key) => evidence.findBatch(tenant, key), saveReceipt: value => evidence.saveBatch(value), saveExport: value => evidence.saveExport(value), saveRepair: value => evidence.saveRepair(value) }; }
    /** Executes a previously reviewed batch through domain-owned command services. */
    , executeBatch: async function (request) { let preview = await this.batchPreview(request); return SERVICE.DefaultEngagementOperationsExecutionService.executeBatch(preview, Object.assign({}, request.payload, { tenant: request.tenant, actorId: request.authData && (request.authData.principalId || request.authData.code), idempotencyKey: request.idempotencyKey, correlationId: request.correlationId || request.requestId }), this.executionPorts(request)); }
    /** Generates a bounded masked export with checksum evidence. */
    , executeExport: async function (request) { let preview = await this.exportPreview(request); let items = await this.listQueue(request); return SERVICE.DefaultEngagementOperationsExecutionService.executeExport(preview, items, Object.assign({}, request.payload, { tenant: request.tenant, actorId: request.authData && (request.authData.principalId || request.authData.code), idempotencyKey: request.idempotencyKey, correlationId: request.correlationId || request.requestId }), this.executionPorts(request)); }
    /** Executes one approved repair through its domain owner. */
    , executeRepair: async function (request) { let preview = await this.repairPreview(request); return SERVICE.DefaultEngagementOperationsExecutionService.executeRepair(preview, Object.assign({}, request.payload, { tenant: request.tenant, actorId: request.authData && (request.authData.principalId || request.authData.code), idempotencyKey: request.idempotencyKey, correlationId: request.correlationId || request.requestId }), this.executionPorts(request)); }
};
