/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/**
 * @module nAuth/config/Properties
 * @description Defines layered authentication security, identity governance, permission catalog, migration, and auth-cache defaults.
 * @layer config
 * @owner nAuth
 * @override Project, environment, server, and node modules may merge stricter identity policies and additional governed permissions without weakening framework security contracts.
 */

module.exports = {
  authSecurity: {
    jwt: {
      secret: null,
      minimumSecretLength: 32,
      issuer: "nodics",
      audience: "nodics-services",
      algorithms: ["HS256"],
      requireJti: true,
      accessTokenExpiresIn: "3h",
      serviceTokenExpiresIn: "15m",
      serviceTokenRefreshIntervalMs: 600000,
    },
    refreshToken: {
      expiresInSeconds: 2592000,
      rotateOnUse: true,
      requireDistributedCache: true,
    },
    browserAccess: {
      enabled: false,
      accessTokenExpiresIn: "5m",
      audiencePrefix: "nodics-module:",
      moduleAudiences: {},
      moduleNamePattern: "^[A-Za-z][A-Za-z0-9_.-]{0,127}$",
      rejectServiceAndCronCredentials: true,
    },
    apiKey: {
      defaultLifetimeSeconds: 7776000,
      requireScopes: true,
      allowLegacyHumanPrincipals: false,
      allowLegacyPlaintextLookup: false,
      pepper: null,
      minimumPepperLength: 32,
    },
    audit: {
      enabled: true,
      publisherService: null,
      failClosed: false,
    },
    securityStamp: {
      enabled: true,
      failClosed: true,
      allowMissingStamp: false,
    },
    internalToken: {
      routePermission: "auth.internal.token.read",
      crossTenantPermissions: ["auth.internal.token.read.anyTenant"],
      crossTenantGroups: [],
      maxDeclaredModules: 512,
      moduleNamePattern: "^[A-Za-z][A-Za-z0-9_.-]{0,127}$",
    },
    compatibility: {
      allowInsecureDevelopmentSecret: false,
      allowLocalBootstrapIdentity: false,
      allowNonExpiringTokens: false,
      allowPasswordHeaders: false,
    },
    bootstrapIdentity: {
      required: true,
      allowedSources: [
        "environment",
        "externalProperty",
        "secretManager",
        "runtimeSecret",
      ],
      localSources: ["localSample", "test"],
      minimumPasswordLength: 16,
      minimumApiKeyLength: 32,
    },
  },
  cache: {
    profile: {
      channels: {
        auth: {
          ttl: 3600,
          enabled: true,
          fallback: true,
          engine: "local",
          events: {
            expired:
              "DefaultAuthTokenInvalidationService.publishTokenExpiredEvent",
            del: "DefaultAuthTokenInvalidationService.publishTokenDeletedEvent",
            flushed:
              "DefaultAuthTokenInvalidationService.publishTokenFlushedEvent",
          },
        },
      },
    },
  },
  identityGovernance: {
    administrativeGroups: [
      "adminGroup",
      "runtimeConfigAdminUserGroup",
      "serviceAccountUserGroup",
    ],
    systemAccessGroups: ["serviceAccountUserGroup"],
    groupValidationPageSize: 10000,
    principalPolicy: {
      allowedTypes: ["human", "service", "customer"],
      serviceType: "service",
      serviceGroup: "serviceAccountUserGroup",
      minimumServiceApiKeyLength: 32,
    },
    customerRegistration: {
      group: "customerUserGroup",
      principalType: "customer",
      active: true,
    },
    permissionCatalog: [
      "identity.migration.preview",
      "identity.migration.apply",
      "identity.migration.rollback",
      "identity.credential.rotate",
      "auth.internal.token.read",
      "auth.internal.token.read.anyTenant",
      "runtime.config.history.view",
      "runtime.config.summary.view",
      "runtime.config.request.view",
      "runtime.config.preview",
      "runtime.config.request.create",
      "runtime.config.request.approve",
      "runtime.config.request.reject",
      "runtime.config.request.activate",
      "runtime.config.rollback",
      "runtime.config.cleanup.preview",
      "runtime.config.cleanup.execute",
      "backoffice.registry.view",
      "backoffice.registry.admin.view",
      "backoffice.registry.refresh",
      "backoffice.functionalModule.register",
      "backoffice.functionalModule.activate",
      "backoffice.functionalModule.deactivate",
      "backoffice.functionalModule.deregister",
      "backoffice.bootstrap.view",
      "backoffice.axis.policy.view",
      "backoffice.axis.policy.update",
      "backoffice.axis.initialization.view",
      "backoffice.axis.initialization.initiate",
      "backoffice.application.initialization.view",
      "backoffice.application.initialization.initiate",
      "backoffice.application.initialization.rollback",
      "backoffice.application.initialization.retire",
      "backoffice.localReset.view",
      "backoffice.localReset.execute",
      "backoffice.registry.diagnostics.view",
      "backoffice.contract.view",
      "backoffice.contract.approve",
      "backoffice.contract.reject",
      "backoffice.contract.rollback",
      "profile.backoffice.view",
      "profile.enterprise.search",
      "profile.enterprise.create",
      "cms.backoffice.view",
      "cms.backoffice.manage",
      "cms.delivery.authenticated.read",
      "cms.migration.preview",
      "cms.migration.apply",
      "cms.migration.rollback",
      "publish.lifecycle.create",
      "publish.lifecycle.view",
      "publish.lifecycle.validate",
      "publish.lifecycle.requestApproval",
      "publish.lifecycle.approve",
      "publish.lifecycle.reject",
      "publish.lifecycle.activate",
      "publish.lifecycle.retry",
      "publish.lifecycle.rollback",
      "publish.lifecycle.withdraw",
      "publish.operations.view",
      "publish.operations.reconcile",
      "publish.operations.recover",
      "editorial.backoffice.read",
      "editorial.backoffice.manage",
      "editorial.workflow.submit",
      "editorial.workflow.read",
      "editorial.publish.execute",
      "editorial.publish.schedule",
      "editorial.publish.withdraw",
      "cronjob.backoffice.view",
      "cronjob.lifecycle.manage",
      "process.backoffice.view",
      "process.definition.read",
      "process.definition.create",
      "process.definition.update",
      "process.definition.validate",
      "process.definition.publish",
      "process.definition.delete",
      "process.instance.start",
      "process.instance.cancel",
      "process.instance.retry",
      "process.instance.compensate",
      "process.incident.read",
      "process.task.claim",
      "process.task.assign",
      "process.task.complete",
      "process.task.cancel",
      "process.trigger.manage",
      "process.trigger.execute",
      "engagement.backoffice.view",
      "engagement.form.read",
      "engagement.contact.submit",
      "engagement.customer.read",
      "engagement.operator.read",
      "engagement.operator.act",
      "engagement.handoff.recover",
      "engagement.handoff.reconcile",
      "engagement.integration.callback",
      "engagement.testimonial.public.read",
      "engagement.testimonial.customer.read",
      "engagement.testimonial.customer.withdraw",
      "engagement.testimonial.read",
      "engagement.testimonial.edit",
      "engagement.testimonial.approve",
      "engagement.testimonial.publish",
      "engagement.testimonial.act",
      "engagement.review.submit",
      "engagement.review.customer.read",
      "engagement.review.withdraw",
      "engagement.review.abuse.report",
      "engagement.review.read",
      "engagement.review.moderate",
      "engagement.review.respond",
      "engagement.review.abuse.resolve",
      "engagement.review.appeal.resolve",
      "engagement.review.migrate",
      "engagement.review.helpfulness.vote",
      "engagement.review.request.read",
      "engagement.review.request.create",
      "engagement.review.session.start",
      "engagement.review.syndication.import",
      "engagement.feedback.read",
      "engagement.feedback.customer.read",
      "engagement.feedback.act",
      "engagement.feedback.classify",
      "engagement.feedback.insight",
      "engagement.operations.read",
      "engagement.operations.batch",
      "engagement.operations.export",
      "engagement.operations.repair",
      "engagement.automation.review",
      "engagement.automation.evaluate",
      "engagement.resilience.read",
      "engagement.compatibility.read",
      "communication.customer.read",
      "communication.delivery.retry",
      "communication.callback.receive",
      "commerce.backoffice.view",
      "commerce.store.read",
      "commerce.product.read",
      "commerce.catalog.read",
      "commerce.pricing.read",
      "commerce.tax.read",
      "commerce.promotion.read",
      "commerce.inventory.read",
      "commerce.cart.read",
      "commerce.cart.own",
      "commerce.checkout.place",
      "commerce.order.read",
      "commerce.order.own.read",
      "commerce.lifecycle.read",
      "commerce.lifecycle.act",
      "commerce.lifecycle.own.create",
      "commerce.payment.read",
      "commerce.payment.reconcile",
      "commerce.payment.callback.receive",
      "commerce.fulfillment.read",
      "commerce.fulfillment.return",
      "storefront.backoffice.read",
      "storefront.backoffice.manage",
      "storefront.operations.read",
      "ai.knowledge.read",
      "ai.knowledge.manage",
      "ai.assistant.use",
      "ai.assistant.read",
      "ai.assistant.cancel",
      "ai.assistant.operations.read",
      "ai.ledger.read",
      "ai.usage.readOwn",
      "ai.ledger.manage",
      "ai.ledger.repair.approve",
      "cache.flush",
      "cache.configuration.router.update",
      "cache.configuration.item.update",
      "system.health.readiness.view",
      "system.contract.openapi.view",
      "system.contract.swagger.view",
      "media.context.view",
      "media.storage.policy.view",
      "media.folder.policy.manage",
      "media.format.policy.manage",
      "media.set.manage",
      "media.storage.location.resolve",
      "media.upload.create",
      "media.content.read",
      "media.content.download",
      "system.log.level.update",
      "system.schema.index.rebuild",
      "system.schema.validator.rebuild",
      "system.schema.workbench.view",
      "system.schema.workbench.manage",
      "system.test.unit.run",
      "system.test.nodics.run",
      "import.init.run",
      "import.core.run",
      "import.sample.run",
      "import.local.run",
      "import.media.run",
      "import.contentPack.view",
      "import.contentPack.run",
      "import.release.view",
      "import.release.validate",
      "import.history.view",
      "import.history.detail.view",
      "export.run",
      "dynamo.class.view",
      "dynamo.class.snapshot.view",
      "dynamo.class.update",
      "dynamo.class.execute",
    ],
    migration: {
      version: 3,
      reconcileMissingGroupsOnStartup: true,
      servicePrincipalCodes: ["apiAdmin"],
      servicePrincipalScopes: {
        apiAdmin: [
          "auth.internal.token.read",
          "auth.internal.token.read.anyTenant",
        ],
      },
      administratorCodes: ["admin"],
      serviceGroup: "serviceAccountUserGroup",
      administratorGroups: ["adminGroup", "runtimeConfigAdminUserGroup"],
      humanDefaultGroup: "employeeUserGroup",
      customerGroup: "customerUserGroup",
      groupTargets: {
        userGroup: { parentGroups: [] },
        adminGroup: {
          parentGroups: ["userGroup"],
          permissions: [
            "backoffice.registry.view",
            "backoffice.registry.admin.view",
            "backoffice.registry.refresh",
            "backoffice.bootstrap.view",
            "backoffice.contract.view",
            "backoffice.axis.policy.view",
            "backoffice.axis.initialization.view",
            "backoffice.application.initialization.view",
            "backoffice.localReset.view",
            "system.schema.workbench.view",
            "media.context.view",
          ],
        },
        employeeUserGroup: {
          parentGroups: ["userGroup"],
          permissions: ["cms.delivery.authenticated.read"],
        },
        contentUserGroup: {
          parentGroups: ["employeeUserGroup"],
          permissions: [
            "cms.backoffice.view",
            "cms.delivery.authenticated.read",
          ],
        },
        runtimeConfigViewerUserGroup: {
          parentGroups: ["employeeUserGroup"],
          permissions: [
            "runtime.config.history.view",
            "runtime.config.summary.view",
            "runtime.config.request.view",
            "backoffice.registry.view",
            "backoffice.bootstrap.view",
            "backoffice.axis.policy.view",
            "backoffice.contract.view",
            "system.health.readiness.view",
            "system.contract.openapi.view",
            "system.contract.swagger.view",
            "system.schema.workbench.view",
          ],
        },
        runtimeConfigRequesterUserGroup: {
          parentGroups: ["runtimeConfigViewerUserGroup"],
          permissions: [
            "runtime.config.preview",
            "runtime.config.request.create",
          ],
        },
        runtimeConfigApproverUserGroup: {
          parentGroups: ["runtimeConfigViewerUserGroup"],
          permissions: [
            "runtime.config.request.approve",
            "runtime.config.request.reject",
          ],
        },
        runtimeConfigOperatorUserGroup: {
          parentGroups: ["runtimeConfigRequesterUserGroup"],
          permissions: [
            "runtime.config.request.activate",
            "runtime.config.rollback",
            "runtime.config.cleanup.preview",
          ],
        },
        runtimeConfigAdminUserGroup: {
          parentGroups: [
            "runtimeConfigOperatorUserGroup",
            "runtimeConfigApproverUserGroup",
          ],
          permissions: [
            "runtime.config.cleanup.execute",
            "backoffice.registry.diagnostics.view",
            "backoffice.contract.approve",
            "backoffice.contract.reject",
            "backoffice.contract.rollback",
            "backoffice.axis.policy.update",
            "backoffice.axis.initialization.initiate",
            "backoffice.application.initialization.initiate",
            "backoffice.application.initialization.rollback",
            "backoffice.application.initialization.retire",
            "backoffice.localReset.execute",
            "backoffice.functionalModule.register",
            "backoffice.functionalModule.activate",
            "backoffice.functionalModule.deactivate",
            "backoffice.functionalModule.deregister",
            "profile.backoffice.view",
            "profile.enterprise.search",
            "cms.backoffice.view",
            "cms.backoffice.manage",
            "cms.delivery.authenticated.read",
            "publish.lifecycle.create",
            "publish.lifecycle.view",
            "publish.lifecycle.validate",
            "publish.lifecycle.requestApproval",
            "publish.lifecycle.retry",
            "publish.lifecycle.rollback",
            "publish.lifecycle.withdraw",
            "publish.operations.view",
            "publish.operations.reconcile",
            "publish.operations.recover",
            "editorial.backoffice.read",
            "editorial.backoffice.manage",
            "editorial.workflow.submit",
            "editorial.workflow.read",
            "editorial.publish.execute",
            "editorial.publish.schedule",
            "editorial.publish.withdraw",
            "cronjob.backoffice.view",
            "cronjob.lifecycle.manage",
            "process.backoffice.view",
            "process.definition.read",
            "process.definition.create",
            "process.definition.update",
            "process.definition.validate",
            "process.definition.publish",
            "process.definition.delete",
            "process.instance.start",
            "process.instance.cancel",
            "process.instance.retry",
            "process.instance.compensate",
            "process.incident.read",
            "process.task.claim",
            "process.task.assign",
            "process.task.complete",
            "process.task.cancel",
            "process.trigger.manage",
            "process.trigger.execute",
            "storefront.backoffice.read",
            "storefront.backoffice.manage",
            "ai.knowledge.read",
            "ai.knowledge.manage",
            "ai.assistant.use",
            "ai.assistant.read",
            "ai.assistant.cancel",
            "ai.assistant.operations.read",
            "ai.ledger.read",
            "ai.usage.readOwn",
            "ai.ledger.manage",
            "ai.ledger.repair.approve",
            "identity.migration.preview",
            "identity.migration.apply",
            "identity.migration.rollback",
            "identity.credential.rotate",
            "cms.migration.preview",
            "cms.migration.apply",
            "cms.migration.rollback",
            "cache.flush",
            "cache.configuration.router.update",
            "cache.configuration.item.update",
            "system.health.readiness.view",
            "system.contract.swagger.view",
            "media.context.view",
            "media.storage.policy.view",
            "media.folder.policy.manage",
            "media.format.policy.manage",
            "media.set.manage",
            "media.storage.location.resolve",
            "media.upload.create",
            "media.content.read",
            "media.content.download",
            "system.log.level.update",
            "system.schema.index.rebuild",
            "system.schema.validator.rebuild",
            "system.test.unit.run",
            "system.test.nodics.run",
            "import.init.run",
            "import.core.run",
            "import.sample.run",
            "import.local.run",
            "import.media.run",
            "import.contentPack.view",
            "import.contentPack.run",
            "import.release.view",
            "import.release.validate",
            "import.history.view",
            "import.history.detail.view",
            "export.run",
            "dynamo.class.view",
            "dynamo.class.snapshot.view",
            "dynamo.class.update",
            "dynamo.class.execute",
          ],
        },
        serviceAccountUserGroup: {
          parentGroups: ["userGroup"],
          permissions: [
            "auth.internal.token.read",
            "auth.internal.token.read.anyTenant",
          ],
        },
      },
    },
    separationOfDuties: {
      requireActor: true,
      preventSelfDecision: true,
      preventRequesterActivation: true,
      preventApproverActivation: true,
    },
  },
};
