/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/** @module fulfillmentCore/src/schemas/schemas @description Defines governed Commerce lifecycle evidence. @layer schema @owner fulfillmentCore */
module.exports = { fulfillmentCore: {
    consignment: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false }, currency: { type: 'string', required: false }, totalAmount: { type: 'string', required: false } } }),
    shipment: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false }, currency: { type: 'string', required: false }, totalAmount: { type: 'string', required: false } } }),
    trackingEvent: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false } } }),
    warehouseTask: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false } } }),
    fulfillmentReturn: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false }, requestType: { type: 'string', required: false }, reasonCode: { type: 'string', required: false } } }),
    returnReceipt: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false } } }),
    returnInspection: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false }, requestType: { type: 'string', required: false }, reasonCode: { type: 'string', required: false } } }),
    fulfillmentException: Object.assign({ super: 'base', model: true, schemaPolicies: ['operational'], service: { enabled: true }, router: { enabled: false }, cache: { enabled: false }, event: { enabled: false }, search: { enabled: false } }, { definition: { code: { type: 'string', required: true }, tenant: { type: 'string', required: true }, ownerId: { type: 'string', required: false }, orderCode: { type: 'string', required: false }, cartCode: { type: 'string', required: false }, status: { type: 'string', required: true }, revision: { type: 'int', required: true }, idempotencyKey: { type: 'string', required: false }, correlationId: { type: 'string', required: true }, evidence: { type: 'object', required: false }, occurredAt: { type: 'date', required: false } } })
} };
module.exports.fulfillmentCore.consignment.backoffice = { operations: ['search', 'read'], description: 'Fulfillment consignment evidence.' };
module.exports.fulfillmentCore.shipment.backoffice = { operations: ['search', 'read'], description: 'Shipment and tracking evidence.' };
module.exports.fulfillmentCore.returnInspection.backoffice = { operations: ['search', 'read'], description: 'Returned-goods receipt and inspection evidence.' };
