/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module customerReview/src/service/defaultCustomerReviewSolicitationService @description Governs sentiment-neutral review eligibility, requests, reminders, sessions, and funnel evidence. @layer service @owner customerReview @override Projects may replace eligibility timing or delivery adapters but cannot select recipients by predicted sentiment. */
module.exports = {
    /** Rejects sentiment-conditioned acquisition policy and returns eligibility timing. */
    eligible: function (interaction, policy, now) { policy = policy || {}; now = now || new Date(); if (interaction.predictedSentiment !== undefined || interaction.predictedRating !== undefined || interaction.sentimentSegment !== undefined) { let error = new Error('review solicitation cannot select by sentiment or predicted rating'); error.code = 'ERR_REVIEW_00015'; throw error; } if (!interaction.fulfilledAt && !interaction.completedAt) return { eligible: false, reason: 'INTERACTION_NOT_COMPLETED' }; if (interaction.reviewOptOut === true || interaction.suppressed === true) return { eligible: false, reason: 'CUSTOMER_SUPPRESSED' }; let completed = new Date(interaction.fulfilledAt || interaction.completedAt); let eligibleAt = new Date(completed.getTime() + Number(policy.delayAfterFulfillmentHours || 24) * 3600000); return { eligible: eligibleAt <= now, eligibleAt: eligibleAt, reason: eligibleAt <= now ? 'ELIGIBLE' : 'WAITING_PERIOD' }; },
    /** Creates one channel-neutral and idempotent request record. */
    request: function (interaction, command, policy) { policy = policy || {}; let outcome = this.eligible(interaction, policy, command.now); if (!outcome.eligible) { let error = new Error(outcome.reason); error.code = 'ERR_REVIEW_00016'; throw error; } if (!(policy.allowedChannels || []).includes(command.channel)) { let error = new Error('review request channel is not allowed'); error.code = 'ERR_REVIEW_00017'; throw error; } let expiresAt = new Date((command.now || new Date()).getTime() + Number(policy.requestExpiryDays || 30) * 86400000); return { tenant: command.tenant, ownerId: interaction.ownerId, eligibilityType: interaction.type || 'PURCHASE', sourceModule: interaction.sourceModule, sourceRecordCode: interaction.code, targetCodes: command.targetCodes, channel: command.channel, status: 'PLANNED', eligibleAt: outcome.eligibleAt, expiresAt: expiresAt, reminderCount: 0, policyVersion: policy.policyVersion || '1', idempotencyKey: command.idempotencyKey, correlationId: command.correlationId }; },
    /** Decides whether a reminder is allowed without inspecting review sentiment. */
    reminder: function (request, policy, now) { policy = policy || {}; now = now || new Date(); if (['COMPLETED', 'EXPIRED', 'SUPPRESSED'].includes(request.status)) return { allowed: false, reason: 'TERMINAL' }; if (Number(request.reminderCount || 0) >= Number(policy.maximumReminders || 1)) return { allowed: false, reason: 'LIMIT_REACHED' }; let hour = now.getUTCHours(); let start = Number(policy.quietPeriodStartHour || 21); let end = Number(policy.quietPeriodEndHour || 8); if (hour >= start || hour < end) return { allowed: false, reason: 'QUIET_PERIOD' }; return { allowed: true, next: Object.assign({}, request, { reminderCount: Number(request.reminderCount || 0) + 1, nextReminderAt: new Date(now.getTime() + Number(policy.reminderDelayHours || 168) * 3600000) }) }; },
    /** Creates one multi-target submission session. */
    session: function (request, now) { if (!request || !['OFFERED', 'DELIVERED', 'OPENED', 'STARTED'].includes(request.status)) { let error = new Error('review request is unavailable'); error.code = 'ERR_REVIEW_00018'; throw error; } now = now || new Date(); if (new Date(request.expiresAt) <= now) { let error = new Error('review request expired'); error.code = 'ERR_REVIEW_00018'; throw error; } return { tenant: request.tenant, ownerId: request.ownerId, requestCode: request.code, targetCodes: request.targetCodes, completedTargetCodes: [], status: 'OPEN', startedAt: now, expiresAt: request.expiresAt, revision: 0, correlationId: request.correlationId }; },
    /** Aggregates acquisition funnel counts from content-free events. */
    funnel: function (events) { return (events || []).reduce((result, event) => { result[event.eventType] = Number(result[event.eventType] || 0) + 1; return result; }, { ELIGIBLE: 0, OFFERED: 0, DELIVERED: 0, OPENED: 0, STARTED: 0, COMPLETED: 0, EXPIRED: 0, SUPPRESSED: 0, FAILED: 0 }); }
};
