/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module customerReview/src/service/defaultCustomerReviewProjectionService @description Creates sanitized public review and Schema.org projections from approved evidence. @layer service @owner customerReview @override Later modules may add allow-listed presentation fields without exposing owner or moderation evidence. */
module.exports = {
    /** Creates a public projection only when the review is approved. */
    publish: function (review, version, authenticity, response, options) { options = options || {}; if (!review || review.status !== 'APPROVED') { let error = new Error('only approved reviews can be published'); error.code = 'ERR_REVIEW_00013'; throw error; } let verified = authenticity && authenticity.verificationStatus === 'VERIFIED'; return { tenant: review.tenant, reviewCode: review.code, reviewVersion: version.version, targetType: review.targetType, targetCode: review.targetCode, variantCode: review.variantCode, overallRating: version.overallRating, dimensionRatings: version.dimensionRatings || {}, title: version.title, body: version.body, recommendation: review.recommendation, media: (options.media || []).slice(0, Number(options.maximumGalleryItems || 12)).map(item => ({ code: item.code, alt: item.alt, type: item.type })), businessResponse: response && response.status === 'PUBLISHED' ? { body: response.body, publishedAt: response.publishedAt } : undefined, authenticity: { verified: verified, type: authenticity ? authenticity.interactionType : 'NONE' }, disclosures: [authenticity && authenticity.incentiveType, authenticity && authenticity.samplingDisclosure, authenticity && authenticity.materialRelationship].filter(Boolean), helpfulCount: 0, unhelpfulCount: 0, site: review.site, locale: review.locale, channel: review.channel, status: 'PUBLISHED', publishedAt: options.now || new Date(), policyVersion: options.policyVersion || '1', sourceHash: version.contentHash, correlationId: review.correlationId }; },
    /** Removes a projection from public visibility while retaining audit evidence. */
    hide: function (projection, status, now) { return Object.assign({}, projection, { status: status || 'HIDDEN', hiddenAt: now || new Date() }); },
    /** Returns a bounded, filtered and sorted page of published projections. */
    page: function (projections, query, policy) { query = query || {}; policy = policy || {}; let values = (projections || []).filter(item => item.status === 'PUBLISHED'); ['targetType', 'targetCode', 'variantCode', 'site', 'locale'].forEach(field => { if (query[field]) values = values.filter(item => item[field] === query[field]); }); if (query.rating) values = values.filter(item => Number(item.overallRating) === Number(query.rating)); if (query.verified === true || query.verified === 'true') values = values.filter(item => item.authenticity && item.authenticity.verified === true); let sort = query.sort || 'RECENT'; values.sort((a, b) => sort === 'HELPFUL' ? Number(b.helpfulCount || 0) - Number(a.helpfulCount || 0) : sort === 'RATING_HIGH' ? Number(b.overallRating) - Number(a.overallRating) : sort === 'RATING_LOW' ? Number(a.overallRating) - Number(b.overallRating) : new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()); let limit = Math.min(Math.max(Number(query.limit || policy.pageSize || 20), 1), Number(policy.maximumPageSize || 100)); let offset = Math.max(Number(query.offset || 0), 0); return { items: values.slice(offset, offset + limit), total: values.length, offset: offset, limit: limit, appliedFilters: { targetType: query.targetType, targetCode: query.targetCode, variantCode: query.variantCode, rating: query.rating, verified: query.verified }, sort: sort }; },
    /** Builds an eligible Schema.org projection without emitting executable markup. */
    schemaOrg: function (aggregate, projections) { let reviews = (projections || []).filter(item => item.status === 'PUBLISHED' && item.body).map(item => ({ '@type': 'Review', reviewBody: item.body, reviewRating: { '@type': 'Rating', ratingValue: item.overallRating, bestRating: 5, worstRating: 1 } })); return { eligible: Boolean(aggregate && aggregate.count > 0), diagnostics: aggregate && aggregate.count > 0 ? [] : ['NO_PUBLISHED_RATINGS'], value: aggregate && aggregate.count > 0 ? { '@context': 'https://schema.org', '@type': 'AggregateRating', ratingValue: aggregate.average, reviewCount: aggregate.count, bestRating: 5, worstRating: 1, reviews: reviews } : undefined }; }
};
