/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module customerReview/src/service/defaultCustomerReviewApiService @description Implements bounded customer and operator review use cases without exposing generated schema CRUD. @layer service @owner customerReview @override Later modules may extend actions through secured API contracts. */
module.exports = {
    /** Verifies that the review capability is explicitly enabled. */
    assertEnabled: function () { let engagement = CONFIG.get('engagement') || {}; if (!(engagement.capabilities && engagement.capabilities.customerReview === true)) throw SERVICE.DefaultCustomerReviewGovernanceService.error('ERR_REVIEW_00012', 'customer review is disabled'); },
    /** Resolves the authenticated principal. */
    principal: function (request) { let auth = request.authData || {}; return request.principalId || auth.principalId || auth.code || auth.loginId; },
    /** Submits one customer-owned review and immutable first version. */
    submit: async function (request) { this.assertEnabled(); let repository = SERVICE.DefaultCustomerReviewRepositoryService; let input = Object.assign({}, request.payload, { tenant: request.tenant, ownerId: this.principal(request), status: 'DRAFT', correlationId: request.correlationId || request.requestId }); let review = SERVICE.DefaultCustomerReviewGovernanceService.validate(input); review = (await repository.save('customerReview', request.tenant, review, request.authData)); review = Array.isArray(review) ? review[0] : review; let version = SERVICE.DefaultCustomerReviewLifecycleService.version(review, [], 'INITIAL_SUBMISSION'); await repository.save('customerReviewVersion', request.tenant, version); let command = { action: 'SUBMIT', expectedRevision: review.revision, reviewVersion: 1, actorId: this.principal(request), correlationId: review.correlationId }; let result = SERVICE.DefaultCustomerReviewLifecycleService.moderate(review, command, CONFIG.get('customerReview') || {}); await repository.save('customerReviewModeration', request.tenant, result.moderation); return repository.save('customerReview', request.tenant, result.review, request.authData); },
    /** Lists reviews owned by the authenticated customer. */
    /** Removes transport pagination controls before persistence filtering. */ filters: function (query) { let value = Object.assign({}, query || {}); ['limit', 'offset', 'page', 'pageSize', 'sort'].forEach(key => delete value[key]); return value; },
    /** Lists reviews owned by the authenticated customer with transport controls removed from persistence filters. */
    listOwn: function (request) { this.assertEnabled(); return SERVICE.DefaultCustomerReviewRepositoryService.list('customerReview', request.tenant, Object.assign(this.filters(request.query), { ownerId: this.principal(request) }), request.authData, request.query && request.query.limit); },
    /** Gets one customer-owned review. */
    getOwn: async function (request) { this.assertEnabled(); let review = await SERVICE.DefaultCustomerReviewRepositoryService.get('customerReview', request.tenant, request.reviewCode, request.authData); return review && review.ownerId === this.principal(request) ? review : undefined; },
    /** Withdraws one customer-owned review. */
    withdrawOwn: async function (request) { let review = await this.getOwn(request); if (!review) throw SERVICE.DefaultCustomerReviewGovernanceService.error('ERR_REVIEW_00001', 'review not found'); let result = SERVICE.DefaultCustomerReviewLifecycleService.moderate(review, { action: 'WITHDRAW', expectedRevision: request.payload.expectedRevision, actorId: this.principal(request), correlationId: review.correlationId }, CONFIG.get('customerReview') || {}); await SERVICE.DefaultCustomerReviewRepositoryService.save('customerReviewModeration', request.tenant, result.moderation); let saved = await SERVICE.DefaultCustomerReviewRepositoryService.save('customerReview', request.tenant, result.review, request.authData); saved = Array.isArray(saved) ? saved[0] : saved; await SERVICE.DefaultCustomerReviewPublicExperienceService.reconcile(saved); return saved; },
    /** Reports abuse against one review with duplicate-open-report protection. */
    reportAbuse: async function (request) { this.assertEnabled(); let repository = SERVICE.DefaultCustomerReviewRepositoryService; let review = await repository.get('customerReview', request.tenant, request.reviewCode); if (!review) throw SERVICE.DefaultCustomerReviewGovernanceService.error('ERR_REVIEW_00001', 'review not found'); let existing = await repository.list('customerReviewAbuseReport', request.tenant, { reviewCode: review.code, reporterId: this.principal(request) }, request.authData, 100); let report = SERVICE.DefaultCustomerReviewLifecycleService.abuseReport(review, existing, Object.assign({}, request.payload, { reporterId: this.principal(request) })); return repository.save('customerReviewAbuseReport', request.tenant, report, request.authData); },
    /** Executes one governed operator moderation action. */
    moderate: async function (request) { this.assertEnabled(); let repository = SERVICE.DefaultCustomerReviewRepositoryService; let review = await repository.get('customerReview', request.tenant, request.reviewCode, request.authData); if (!review) throw SERVICE.DefaultCustomerReviewGovernanceService.error('ERR_REVIEW_00001', 'review not found'); let command = Object.assign({}, request.payload, { action: request.actionCode, actorId: this.principal(request), correlationId: review.correlationId }); let result = SERVICE.DefaultCustomerReviewLifecycleService.moderate(review, command, CONFIG.get('customerReview') || {}); await repository.save('customerReviewModeration', request.tenant, result.moderation, request.authData); let saved = await repository.save('customerReview', request.tenant, result.review, request.authData); saved = Array.isArray(saved) ? saved[0] : saved; await SERVICE.DefaultCustomerReviewPublicExperienceService.reconcile(saved); return saved; },
    /** Maps one supplied legacy CRES record in dry-run mode for operator review. */
    previewMigration: function (request) { this.assertEnabled(); return Promise.resolve(SERVICE.DefaultCresMigrationService.mapReview(request.payload.legacyRecord, { tenant: request.tenant, dryRun: true, targetCode: request.payload.targetCode, correlationId: request.correlationId || request.requestId, configuration: CONFIG.get('customerReview') || {} })); }
    , /** Lists sanitized published projections through bounded review policy. */
    listPublished: async function (request) { this.assertEnabled(); let policy = (CONFIG.get('customerReview') || {}).publicExperience || {}; let records = await SERVICE.DefaultCustomerReviewRepositoryService.list('customerReviewProjection', request.tenant, { status: 'PUBLISHED' }, undefined, policy.maximumPageSize || 100); return SERVICE.DefaultCustomerReviewProjectionService.page(records, request.query, policy); }
    , /** Gets one tenant and target-scoped aggregate. */
    getAggregate: async function (request) { this.assertEnabled(); let query = { targetType: request.targetType, targetCode: request.targetCode, status: 'CURRENT' }; if (request.query && request.query.variantCode) query.variantCode = request.query.variantCode; if (request.query && request.query.site) query.site = request.query.site; let values = await SERVICE.DefaultCustomerReviewRepositoryService.list('customerReviewAggregate', request.tenant, query, undefined, 1); return values[0]; }
    , /** Creates or replaces one customer-owned helpfulness vote. */
    voteHelpfulness: async function (request) { this.assertEnabled(); let repository = SERVICE.DefaultCustomerReviewRepositoryService; let projection = await repository.list('customerReviewProjection', request.tenant, { reviewCode: request.reviewCode, status: 'PUBLISHED' }, undefined, 1); if (!projection[0]) throw SERVICE.DefaultCustomerReviewGovernanceService.error('ERR_REVIEW_00001', 'published review not found'); let ownerId = this.principal(request); let existing = await repository.list('customerReviewHelpfulness', request.tenant, { reviewCode: request.reviewCode, ownerId: ownerId }, request.authData, 1); let current = existing[0]; let vote = { tenant: request.tenant, reviewCode: request.reviewCode, ownerId: ownerId, helpful: request.payload.helpful === true, status: 'ACTIVE', revision: current ? Number(current.revision || 0) + 1 : 0, correlationId: request.correlationId || request.requestId }; if (current) vote.code = current.code; return repository.save('customerReviewHelpfulness', request.tenant, vote, request.authData); }
    , /** Creates one idempotent request from a service-authenticated completed interaction. */
    createRequest: async function (request) { this.assertEnabled(); let policy = (CONFIG.get('customerReview') || {}).solicitation || {}; if (policy.enabled !== true) throw SERVICE.DefaultCustomerReviewGovernanceService.error('ERR_REVIEW_00012', 'review solicitation is disabled'); let repository = SERVICE.DefaultCustomerReviewRepositoryService; let existing = await repository.list('customerReviewRequest', request.tenant, { idempotencyKey: request.idempotencyKey }, undefined, 1); if (existing[0]) return existing[0]; let value = SERVICE.DefaultCustomerReviewSolicitationService.request(request.payload.interaction, Object.assign({}, request.payload, { tenant: request.tenant, idempotencyKey: request.idempotencyKey, correlationId: request.correlationId || request.requestId }), policy); return repository.save('customerReviewRequest', request.tenant, value); }
    , /** Gets one solicitation request owned by the authenticated customer. */
    getOwnRequest: async function (request) { this.assertEnabled(); let value = await SERVICE.DefaultCustomerReviewRepositoryService.get('customerReviewRequest', request.tenant, request.requestCode, request.authData); return value && value.ownerId === this.principal(request) ? value : undefined; }
    , /** Starts one bounded customer-owned multi-target session. */
    startSession: async function (request) { let value = await this.getOwnRequest(request); if (!value) throw SERVICE.DefaultCustomerReviewGovernanceService.error('ERR_REVIEW_00001', 'review request not found'); let session = SERVICE.DefaultCustomerReviewSolicitationService.session(value); return SERVICE.DefaultCustomerReviewRepositoryService.save('customerReviewSession', request.tenant, session, request.authData); }
    , /** Receives one licensed provider review into quarantine without affecting public aggregates. */
    importSyndicated: async function (request) { this.assertEnabled(); let policy = (CONFIG.get('customerReview') || {}).syndication || {}; if (policy.enabled !== true) throw SERVICE.DefaultCustomerReviewGovernanceService.error('ERR_REVIEW_00012', 'review syndication is disabled'); let incoming = SERVICE.DefaultCustomerReviewSyndicationService.receive(request.payload.review, { tenant: request.tenant, providerCode: request.providerCode, targetType: request.payload.targetType, targetCode: request.payload.targetCode, correlationId: request.correlationId || request.requestId }, policy); let repository = SERVICE.DefaultCustomerReviewRepositoryService; let existing = await repository.list('customerReviewSyndication', request.tenant, { providerCode: request.providerCode, externalReviewId: incoming.externalReviewId }, undefined, 1); let replay = SERVICE.DefaultCustomerReviewSyndicationService.replay(existing[0], incoming); if (replay.action === 'SKIP') return replay.record; if (existing[0]) incoming.code = existing[0].code; return repository.save('customerReviewSyndication', request.tenant, incoming); }
    , /** Executes a purpose-bound privacy operation on one review. */ privacy: async function (request) { let repository = SERVICE.DefaultCustomerReviewRepositoryService; let record = await repository.get('customerReview', request.tenant, request.domainCode, request.authData); if (!record) throw SERVICE.DefaultCustomerReviewGovernanceService.error('ERR_REVIEW_00001', 'review not found'); let command = Object.assign({}, request.payload, { actorId: request.authData && (request.authData.principalId || request.authData.code), domainType: 'REVIEW', correlationId: request.correlationId }); if (request.payload.operation === 'EXPORT') return { record: record, result: SERVICE.DefaultEngagementPrivacyService.exportRecord(record, command, ['code', 'targetType', 'targetCode', 'overallRating', 'title', 'body', 'advantages', 'disadvantages', 'recommendation', 'status', 'submittedAt', 'withdrawnAt']) }; let result = SERVICE.DefaultEngagementPrivacyService.anonymize(record, command, { redactFields: ['title', 'body'], clearArrayFields: ['advantages', 'disadvantages', 'mediaCodes'], removeFields: ['structuredAnswers'] }); if (result.changed) result.record = await repository.save('customerReview', request.tenant, result.record, request.authData); return { record: record, result: result }; }
};
