/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
'use strict';
const crypto = require('crypto');
/** @module commsCore/src/service/defaultCommunicationCoreService @description Validates and renders declared templates, creates idempotent communication intents, applies suppression, and records immutable provider-neutral outcomes. @layer service @owner commsCore @override Projects may replace repositories and transports while preserving policy and evidence. */
module.exports = {
    /** Produces a stable content hash without storing variables in events. */ hash: value => crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex'),
    /** Renders only declared variables and rejects executable template constructs. */ render: function (template, variables, policy) { variables = variables || {}; let declared = template.declaredVariables || []; let keys = Object.keys(variables); if (keys.length > Number(policy.rendering.maximumVariables || 50)) throw new Error('communication variable limit exceeded'); if (policy.rendering.rejectUnknownVariables && keys.some(key => !declared.includes(key))) throw new Error('communication variable is not declared'); let replace = value => String(value || '').replace(/{{\s*([A-Za-z0-9_.-]+)\s*}}/g, (all, key) => Object.prototype.hasOwnProperty.call(variables, key) ? String(variables[key]) : ''); if (/<%|{{{?|javascript:/i.test(String(template.bodyTemplate).replace(/{{\s*[A-Za-z0-9_.-]+\s*}}/g, ''))) throw new Error('executable template syntax is prohibited'); let rendered = { subject: replace(template.subjectTemplate), body: replace(template.bodyTemplate) }; if (Buffer.byteLength(JSON.stringify(rendered)) > Number(policy.rendering.maximumRenderedBytes || 65536)) throw new Error('rendered communication is too large'); return rendered; },
    /** Creates one provider-neutral intent and returns existing evidence for replay. */ intent: function (command, template, suppressions, existing, policy) { if (existing) return { duplicate: true, intent: existing }; if (!(policy.allowedChannels || []).includes(command.channel)) throw new Error('communication channel is not allowed'); let suppressed = (suppressions || []).some(item => item.recipientId === command.recipientId && item.purpose === command.purpose && item.channel === command.channel && (!item.activeUntil || new Date(item.activeUntil) > (command.now || new Date()))); return { duplicate: false, intent: { tenant: command.tenant, sourceModule: command.sourceModule, sourceType: command.sourceType, sourceCode: command.sourceCode, templateCode: template.templateCode || template.code, templateVersion: template.version, recipientId: command.recipientId, recipientAddressReference: command.recipientAddressReference, purpose: command.purpose, channel: command.channel, locale: command.locale, variablesHash: this.hash(command.variables || {}), idempotencyKey: command.idempotencyKey, status: suppressed ? 'SUPPRESSED' : 'ACCEPTED', createdAt: command.now || new Date(), expiresAt: command.expiresAt, correlationId: command.correlationId }, suppressed: suppressed }; },
    /** Converts transport response into content-free immutable evidence. */ outcome: function (intentCode, providerCode, channel, attempt, response, context) { return { tenant: context.tenant, intentCode: intentCode, providerCode: providerCode, channel: channel, attempt: attempt, status: response.status, providerReference: response.providerReference, responseCode: response.responseCode, attemptedAt: context.now || new Date(), deliveredAt: response.status === 'DELIVERED' ? context.now || new Date() : undefined, correlationId: context.correlationId }; },
    /** Schedules bounded retry or dead letter. */ retry: function (attempt, now, policy) { let next = Number(attempt || 0) + 1; if (next >= Number(policy.maximumAttempts || 5)) return { attempt: next, status: 'DEAD_LETTER' }; let delay = Math.min(Number(policy.maximumRetryMilliseconds || 300000), Number(policy.baseRetryMilliseconds || 1000) * Math.pow(2, next - 1)); return { attempt: next, status: 'RETRY_PENDING', nextAttemptAt: new Date(Number(now || Date.now()) + delay) }; },
    /** Produces content-free event data. */ event: function (intent, outcome) { return { tenant: intent.tenant, intentCode: intent.code, sourceModule: intent.sourceModule, sourceType: intent.sourceType, sourceCode: intent.sourceCode, purpose: intent.purpose, channel: intent.channel, status: outcome.status, attempt: outcome.attempt, correlationId: intent.correlationId }; }
};
