/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */

/**
 * @module nodics.wcms/media/src/schemas/schemas
 * @description Defines provider-neutral media lifecycle schemas.
 * @layer schemas
 * @owner media
 * @override Later active modules may extend media metadata or references while preserving media ownership of binary lifecycle.
 */
module.exports = {
    media: {
        mediaFolder: {
            super: 'base',
            model: true,
            service: { enabled: true },
            event: { enabled: true, type: 'SYNC' },
            router: { enabled: true },
            definition: {
                code: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Unique folder code used by callers, for example importSources or cmsAssets',
                },
                name: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'User-facing folder name',
                },
                storagePrefix: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Provider-relative prefix controlled by backend configuration',
                },
                access: {
                    enum: ['PRIVATE', 'PUBLIC', 'SIGNED'],
                    required: true,
                    description: 'Default access mode for media stored in this folder',
                },
                businessPurpose: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Purpose bound to the media lifecycle, such as kycDocuments',
                },
                ownerType: {
                    type: 'string',
                    required: false,
                    description: 'Bounded owner reference type; domain data remains with the owner capability',
                },
                enterpriseCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Enterprise scope supplied by the owning capability',
                },
                ownerReference: {
                    type: 'string',
                    required: false,
                    description: 'Bounded owning subject or aggregate reference',
                },
                reusable: {
                    type: 'bool',
                    required: true,
                    default: false,
                    description: 'Whether purpose-bound reuse is permitted by policy',
                },
                retentionUntil: {
                    type: 'date',
                    required: false,
                    description: 'media-owned retention boundary coordinated with the business owner',
                },
                legalHold: {
                    type: 'bool',
                    required: true,
                    default: false,
                    description: 'Prevents deletion while an authorized legal hold is active',
                },
                allowedExtensions: {
                    type: 'object',
                    required: false,
                    description: 'Allowed file extensions for this folder',
                },
                allowedMimeTypes: {
                    type: 'object',
                    required: false,
                    description: 'Allowed MIME types for this folder',
                },
                maximumFileSizeBytes: {
                    type: 'int',
                    required: false,
                    description: 'Folder-specific upload size limit',
                },
                retentionDays: {
                    type: 'int',
                    required: false,
                    description: 'Optional retention window for cleanup',
                },
                status: {
                    enum: ['ACTIVE', 'INACTIVE'],
                    required: true,
                    default: 'ACTIVE',
                    searchOptions: { enabled: true },
                    description: 'Folder policy lifecycle status. Inactive folders are not eligible for new uploads.',
                },
            },
        },
        mediaFormat: {
            super: 'base',
            model: true,
            service: { enabled: true },
            event: { enabled: true, type: 'SYNC' },
            router: { enabled: true },
            definition: {
                code: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Unique media format code such as original, thumbnail, desktop, mobile, or importFile',
                },
                name: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'User-facing media format name',
                },
                description: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Purpose of this format',
                },
                width: {
                    type: 'int',
                    required: false,
                    description: 'Optional expected width in pixels',
                },
                height: {
                    type: 'int',
                    required: false,
                    description: 'Optional expected height in pixels',
                },
                purpose: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Business purpose or rendering purpose for this format',
                },
                formatFamily: {
                    enum: ['ORIGINAL', 'RESPONSIVE', 'PREVIEW', 'IMPORT', 'EXPORT', 'DOCUMENT', 'CUSTOM'],
                    required: true,
                    default: 'CUSTOM',
                    searchOptions: { enabled: true },
                    description: 'Reusable format family used for filtering and customer extensions',
                },
                status: {
                    enum: ['ACTIVE', 'INACTIVE'],
                    required: true,
                    default: 'ACTIVE',
                    searchOptions: { enabled: true },
                    description: 'Format lifecycle status. Inactive formats are not eligible for new uploads or variants.',
                },
            },
        },
        media: {
            super: 'base',
            model: true,
            service: { enabled: true },
            event: { enabled: true, type: 'SYNC' },
            router: { enabled: true },
            backoffice: {
                excludedFields: ['storageKey', 'storedFileName', 'relativePath', 'fullPath', 'url', 'accessUrl'],
            },
            definition: {
                code: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Unique media item code',
                },
                name: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'User-facing media name',
                },
                description: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Media description for business users',
                },
                folderCode: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'media folder policy code',
                },
                formatCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'media format code',
                },
                providerCode: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Storage provider used for this media item',
                },
                storageKey: {
                    type: 'string',
                    required: true,
                    description: 'Provider-relative storage key generated by media',
                },
                originalFileName: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Original filename supplied by the uploader',
                },
                storedFileName: {
                    type: 'string',
                    required: false,
                    description: 'Sanitized generated filename stored by the provider',
                },
                relativePath: {
                    type: 'string',
                    required: false,
                    description: 'Provider-relative readable path for this media; usually the same value as storageKey',
                },
                fullPath: {
                    type: 'string',
                    required: false,
                    description: 'Backend-resolved full storage path or provider locator retained for governed processing',
                },
                url: {
                    type: 'string',
                    required: false,
                    description: 'Public, signed, or API-delivery URL resolved by the provider policy',
                },
                accessUrl: {
                    type: 'string',
                    required: false,
                    description: 'Readable alias for the effective media access URL when the provider can resolve one',
                },
                mimeType: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Validated MIME type',
                },
                extension: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Validated file extension',
                },
                sizeBytes: {
                    type: 'int',
                    required: false,
                    description: 'File size in bytes',
                },
                checksum: {
                    type: 'string',
                    required: false,
                    description: 'Checksum calculated by backend',
                },
                checksumAlgorithm: {
                    type: 'string',
                    required: false,
                    description: 'Checksum algorithm used by backend',
                },
                access: {
                    enum: ['PRIVATE', 'PUBLIC', 'SIGNED'],
                    required: true,
                    description: 'Effective access mode',
                },
                businessPurpose: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Purpose asserted by the owning capability and enforced by media',
                },
                ownerType: {
                    type: 'string',
                    required: false,
                    description: 'Owning aggregate or subject type',
                },
                enterpriseCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Enterprise scope supplied by the owning capability',
                },
                ownerReference: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Bounded owner reference used for purpose validation',
                },
                reusable: {
                    type: 'bool',
                    required: true,
                    default: false,
                    description: 'Whether another owner reference may reuse this item',
                },
                retentionUntil: {
                    type: 'date',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Deletion boundary coordinated with the owning capability',
                },
                legalHold: {
                    type: 'bool',
                    required: true,
                    default: false,
                    searchOptions: { enabled: true },
                    description: 'Deletion is forbidden while legal hold is active',
                },
                status: {
                    enum: ['UPLOADED', 'READY', 'CONSUMED', 'RETIRED', 'EXPIRED', 'DELETED', 'FAILED'],
                    required: true,
                    default: 'UPLOADED',
                    description: 'Media lifecycle status',
                },
            },
        },
        mediaSet: {
            super: 'base',
            model: true,
            service: { enabled: true },
            event: { enabled: true, type: 'SYNC' },
            router: { enabled: true },
            definition: {
                code: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Unique media set code for one logical asset',
                },
                name: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'User-facing media set name',
                },
                description: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Media set purpose',
                },
                mediaType: {
                    enum: ['IMAGE', 'VIDEO', 'DOCUMENT', 'FILE', 'MIXED'],
                    required: true,
                    default: 'IMAGE',
                    description: 'Type of logical asset represented by this media set',
                },
                businessPurpose: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Reusable purpose such as product-gallery, cms-asset, import-source, or documentation-asset',
                },
                status: {
                    enum: ['ACTIVE', 'INACTIVE', 'RETIRED'],
                    required: true,
                    default: 'ACTIVE',
                    description: 'Media set lifecycle status',
                },
            },
        },
        mediaSetEntry: {
            super: 'base',
            model: true,
            service: { enabled: true },
            event: { enabled: true, type: 'SYNC' },
            router: { enabled: true },
            definition: {
                code: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Unique media set entry code',
                },
                mediaSetCode: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Owning media set code',
                },
                mediaCode: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Referenced media item code',
                },
                formatCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Format represented by this entry, such as thumbnail, mobile, desktop, zoom, or original',
                },
                variantRole: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Reusable variant role inside the set without product-specific meaning',
                },
                localeCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Optional locale for localized media',
                },
                channelCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Optional channel qualifier such as web, app, marketplace, or kiosk',
                },
                deviceCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Optional device qualifier such as desktop, mobile, tablet, or tv',
                },
                breakpointCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Optional responsive breakpoint qualifier such as sm, md, lg, or xl',
                },
                fallbackEntryCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Optional fallback media set entry code used when this entry is not applicable',
                },
                primary: {
                    type: 'bool',
                    required: false,
                    default: false,
                    searchOptions: { enabled: true },
                    description: 'Marks the default entry inside one media set for generic selection.',
                },
                width: {
                    type: 'int',
                    required: false,
                    description: 'Concrete media width in pixels when known',
                },
                height: {
                    type: 'int',
                    required: false,
                    description: 'Concrete media height in pixels when known',
                },
                position: {
                    type: 'int',
                    required: false,
                    description: 'Display or fallback order within the media set',
                },
                status: {
                    enum: ['ACTIVE', 'INACTIVE'],
                    required: true,
                    default: 'ACTIVE',
                    description: 'Entry lifecycle status',
                },
            },
        },
        mediaPlacement: {
            super: 'base',
            model: true,
            service: { enabled: true },
            event: { enabled: true, type: 'SYNC' },
            router: { enabled: true },
            backoffice: {
                excludedFields: ['storageKey', 'relativePath', 'fullPath', 'url', 'accessUrl'],
            },
            definition: {
                code: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Stable media placement identity for one logical media item in one target topology role',
                },
                mediaCode: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Logical media code represented by this physical placement',
                },
                mediaChecksum: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Checksum of the physical artifact stored at this placement',
                },
                checksumAlgorithm: {
                    type: 'string',
                    required: false,
                    description: 'Checksum algorithm used for mediaChecksum',
                },
                targetRole: {
                    enum: ['STAGED', 'ONLINE', 'ACTIVE_PROD_MEDIA_LOCATION', 'REPLICATION_PROD_MEDIA_LOCATION', 'DR_ACTIVE_MEDIA_LOCATION', 'DR_REPLICATION_MEDIA_LOCATION'],
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Role of this physical placement in the runtime topology',
                },
                providerCode: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Provider that owns the physical artifact for this placement',
                },
                storageKey: {
                    type: 'string',
                    required: true,
                    description: 'Provider-relative storage key for backend governed operations',
                },
                relativePath: {
                    type: 'string',
                    required: false,
                    description: 'Provider-relative readable path when available',
                },
                fullPath: {
                    type: 'string',
                    required: false,
                    description: 'Backend/provider locator retained only for governed backend processing',
                },
                url: {
                    type: 'string',
                    required: false,
                    description: 'Provider-resolved delivery URL when configured',
                },
                accessUrl: {
                    type: 'string',
                    required: false,
                    description: 'Readable alias for the effective media access URL',
                },
                publicationCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Owning publication identity when placement was created by publication',
                },
                manifestCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Immutable manifest that created or last verified this placement',
                },
                topologyCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Production topology code when configured',
                },
                status: {
                    enum: ['ACTIVE', 'REPLICATION_PENDING', 'REPLICATION_FAILED', 'REPLICATION_SYNCHRONIZED', 'RETIRED', 'DELETED'],
                    required: true,
                    default: 'ACTIVE',
                    searchOptions: { enabled: true },
                    description: 'Physical placement lifecycle state',
                },
                evidence: {
                    type: 'object',
                    required: false,
                    description: 'Target-specific publication, transfer, verification, and failover evidence',
                },
            },
        },
        mediaReplicationQueue: {
            super: 'base',
            model: true,
            service: { enabled: true },
            event: { enabled: true, type: 'SYNC' },
            router: { enabled: true },
            backoffice: {
                excludedFields: ['sourceStorageKey', 'targetStorageKey'],
            },
            definition: {
                code: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Stable replication queue identity for one media artifact and publication package',
                },
                mediaCode: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Logical media code awaiting replication',
                },
                mediaChecksum: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Checksum of the approved artifact to replicate',
                },
                checksumAlgorithm: {
                    type: 'string',
                    required: false,
                    description: 'Checksum algorithm used for mediaChecksum',
                },
                ownerModule: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Module that owns the business object or publication source for this media obligation',
                },
                ownerType: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Business owner type for this media obligation',
                },
                ownerReference: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Business owner reference for this media obligation',
                },
                publicationType: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Publication family that created this obligation, such as CMS, PRODUCT, CONTENT, IMPORT, EXPORT, or CUSTOM',
                },
                publicationCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Source publication identity that created this replication obligation',
                },
                manifestCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Immutable manifest/package to replay for replication',
                },
                activeLocationRole: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Active serving media location role when failure was recorded',
                },
                replicationLocationRole: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Target replication media location role that must catch up',
                },
                activeProviderCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Active provider at the time the obligation was recorded',
                },
                replicationProviderCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Intended replication provider',
                },
                sourceStorageKey: {
                    type: 'string',
                    required: false,
                    description: 'Provider-relative source locator retained for backend-only replay checks',
                },
                targetStorageKey: {
                    type: 'string',
                    required: false,
                    description: 'Provider-relative target locator once replication succeeds',
                },
                failureCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Last failure code recorded by the replication workflow',
                },
                failureMessage: {
                    type: 'string',
                    required: false,
                    description: 'Redacted operator-safe failure message',
                },
                retryCount: {
                    type: 'int',
                    required: true,
                    default: 0,
                    searchOptions: { enabled: true },
                    description: 'Number of governed retry attempts already made',
                },
                nextRetryAt: {
                    type: 'date',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Earliest time a scheduled retry may run',
                },
                status: {
                    enum: ['REPLICATION_PENDING', 'REPLICATION_FAILED', 'REPLICATION_RETRY_SCHEDULED', 'REPLICATION_IN_PROGRESS', 'REPLICATION_SYNCHRONIZED', 'REPLICATION_ESCALATED', 'REPLICATION_CANCELLED'],
                    required: true,
                    default: 'REPLICATION_PENDING',
                    searchOptions: { enabled: true },
                    description: 'Replication obligation lifecycle state',
                },
                evidence: {
                    type: 'object',
                    required: false,
                    description: 'Retry, topology, checksum, and audit evidence for governed DR reconciliation',
                },
            },
        },
        mediaPhysicalArtifact: {
            super: 'base',
            model: true,
            service: { enabled: true },
            event: { enabled: true, type: 'SYNC' },
            router: { enabled: true },
            backoffice: { excludedFields: ['sourceStorageKey', 'targetStorageKey', 'physicalLocator', 'signedUrl'] },
            definition: {
                code: { type: 'string', required: true, searchOptions: { enabled: true }, description: 'Stable physical artifact identity owned by Media' },
                mediaCode: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Logical media identity when this artifact belongs to a media record' },
                artifactClass: { enum: ['CMS_ASSET', 'PRODUCT_ASSET', 'DOCUMENTATION_ASSET', 'IMPORT_FILE', 'EXPORT_FILE', 'GENERATED_FILE', 'CUSTOMER_UPLOAD', 'AUDIT_FILE', 'OPERATIONAL_FILE', 'CUSTOM'], required: true, default: 'CUSTOM', searchOptions: { enabled: true }, description: 'Generic physical artifact class' },
                ownerModule: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Owning module for the business record that references this artifact' },
                ownerSchema: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Owning schema for the business record that references this artifact' },
                ownerReference: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Owning business record reference' },
                providerCode: { type: 'string', required: true, searchOptions: { enabled: true }, description: 'Provider that stores the artifact' },
                sourceStorageKey: { type: 'string', required: false, description: 'Backend-only provider-relative source key' },
                targetStorageKey: { type: 'string', required: false, description: 'Backend-only provider-relative target key' },
                physicalLocator: { type: 'string', required: false, description: 'Backend-only raw provider locator' },
                checksum: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Artifact checksum' },
                checksumAlgorithm: { type: 'string', required: false, description: 'Checksum algorithm' },
                sizeBytes: { type: 'int', required: false, description: 'Artifact size in bytes' },
                lifecycleState: { enum: ['STAGED', 'ONLINE', 'REPLICATED', 'PASSIVE', 'PURGED', 'FAILED'], required: true, default: 'STAGED', searchOptions: { enabled: true }, description: 'Physical artifact lifecycle state' },
                publishable: { type: 'bool', required: true, default: true, searchOptions: { enabled: true }, description: 'Whether the artifact is allowed to move through Staged to Online publishing' },
                evidence: { type: 'object', required: false, description: 'Physical artifact audit evidence' },
            },
        },
        mediaTransferManifest: {
            super: 'base',
            model: true,
            service: { enabled: true },
            event: { enabled: true, type: 'SYNC' },
            router: { enabled: true },
            definition: {
                code: { type: 'string', required: true, searchOptions: { enabled: true }, description: 'Stable transfer manifest identity' },
                publicationCode: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Publication identity that owns this transfer manifest' },
                manifestCode: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Immutable data-pack manifest identity' },
                sourceRuntimeRole: { type: 'string', required: true, searchOptions: { enabled: true }, description: 'Source runtime role such as STAGED or ACTIVE_PROD_MEDIA_LOCATION' },
                targetRuntimeRole: { type: 'string', required: true, searchOptions: { enabled: true }, description: 'Target runtime role such as ONLINE or REPLICATION_PROD_MEDIA_LOCATION' },
                transportStrategy: { enum: ['PROVIDER_COPY', 'STREAMING_TRANSFER', 'INLINE_BASE64', 'PUBLICATION_PACKAGE'], required: true, default: 'PROVIDER_COPY', searchOptions: { enabled: true }, description: 'Selected physical transfer strategy' },
                artifactCount: { type: 'int', required: true, default: 0, searchOptions: { enabled: true }, description: 'Number of artifacts in this manifest' },
                totalBytes: { type: 'int', required: false, description: 'Total artifact bytes when known' },
                status: { enum: ['DRAFT', 'READY', 'TRANSFERRING', 'TRANSFERRED', 'PARTIAL', 'FAILED', 'CANCELLED'], required: true, default: 'DRAFT', searchOptions: { enabled: true }, description: 'Transfer manifest state' },
                artifacts: { type: 'object', required: false, description: 'Path-free artifact descriptors carried by this manifest' },
                evidence: { type: 'object', required: false, description: 'Transfer strategy, dependency, checksum, and policy evidence' },
            },
        },
        mediaPublicationReceipt: {
            super: 'base',
            model: true,
            service: { enabled: true },
            event: { enabled: true, type: 'SYNC' },
            router: { enabled: true },
            definition: {
                code: { type: 'string', required: true, searchOptions: { enabled: true }, description: 'Stable publication receipt identity for physical artifacts' },
                publicationCode: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Source publication identity' },
                manifestCode: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Immutable manifest identity' },
                mediaCode: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Logical media identity when receipt is for one media item' },
                artifactCode: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Physical artifact identity when known' },
                targetRuntimeRole: { type: 'string', required: true, searchOptions: { enabled: true }, description: 'Target role that accepted or rejected the artifact' },
                receiptType: { enum: ['IMPORT_RECEIPT', 'PUBLICATION_AUDIT', 'REPLICATION_RECEIPT', 'CLEANUP_RECEIPT'], required: true, default: 'IMPORT_RECEIPT', searchOptions: { enabled: true }, description: 'Receipt family' },
                status: { enum: ['ACCEPTED', 'REJECTED', 'PARTIAL', 'FAILED', 'ROLLED_BACK'], required: true, default: 'ACCEPTED', searchOptions: { enabled: true }, description: 'Receipt outcome' },
                checksum: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Accepted artifact checksum' },
                receivedAt: { type: 'date', required: true, searchOptions: { enabled: true }, description: 'Target receipt timestamp' },
                evidence: { type: 'object', required: false, description: 'Target import, audit, rollback, or cleanup evidence' },
            },
        },
        mediaCleanupCandidate: {
            super: 'base',
            model: true,
            service: { enabled: true },
            event: { enabled: true, type: 'SYNC' },
            router: { enabled: true },
            definition: {
                code: { type: 'string', required: true, searchOptions: { enabled: true }, description: 'Stable cleanup candidate identity for one media artifact and cleanup reason' },
                mediaCode: { type: 'string', required: true, searchOptions: { enabled: true }, description: 'Logical media item being considered for passive marking or cleanup' },
                mediaChecksum: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Checksum of the physical artifact at scan time' },
                folderCode: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Media folder policy that contributed retention or classification context' },
                providerCode: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Provider that currently stores the active artifact' },
                ownerModule: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Owning module when known from media metadata or reference evidence' },
                ownerType: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Owning business artifact type for generic cleanup governance' },
                ownerReference: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Owning business artifact reference for operator review' },
                artifactClass: {
                    enum: ['CMS_ASSET', 'PRODUCT_ASSET', 'DOCUMENTATION_ASSET', 'IMPORT_FILE', 'EXPORT_FILE', 'GENERATED_FILE', 'CUSTOMER_UPLOAD', 'OPERATIONAL_FILE', 'CUSTOM'],
                    required: true,
                    default: 'CUSTOM',
                    searchOptions: { enabled: true },
                    description: 'Generic media artifact class independent of CMS/product ownership',
                },
                reasonCode: { type: 'string', required: true, searchOptions: { enabled: true }, description: 'Governed cleanup reason such as RETENTION_EXPIRED, RETIRED_MEDIA, or EXPIRED_MEDIA' },
                reasonMessage: { type: 'string', required: false, description: 'Operator-safe cleanup explanation without exposing storage paths' },
                detectedAt: { type: 'date', required: true, searchOptions: { enabled: true }, description: 'Timestamp when the candidate was detected by scan or preview' },
                passiveMarkedAt: { type: 'date', required: false, searchOptions: { enabled: true }, description: 'Timestamp when an operator or job marked the candidate passive' },
                purgeEligibleAt: { type: 'date', required: false, searchOptions: { enabled: true }, description: 'Earliest timestamp when retention cleanup may physically remove approved artifacts' },
                approvalCode: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'External approval/workflow identity authorizing physical deletion' },
                approvedBy: { type: 'string', required: false, searchOptions: { enabled: true }, description: 'Operator, workflow, or service principal that approved cleanup' },
                approvedAt: { type: 'date', required: false, searchOptions: { enabled: true }, description: 'Approval timestamp for production physical deletion' },
                legalHold: { type: 'bool', required: true, default: false, searchOptions: { enabled: true }, description: 'Cleanup is blocked while legal hold is true' },
                status: {
                    enum: ['CLEANUP_CANDIDATE', 'CLEANUP_PREVIEWED', 'PASSIVE_PENDING_APPROVAL', 'PASSIVE', 'CLEANUP_APPROVED', 'CLEANUP_IN_PROGRESS', 'CLEANED', 'CLEANUP_REJECTED', 'CLEANUP_FAILED', 'LEGAL_HOLD_BLOCKED'],
                    required: true,
                    default: 'CLEANUP_CANDIDATE',
                    searchOptions: { enabled: true },
                    description: 'Governed cleanup candidate lifecycle state',
                },
                evidence: { type: 'object', required: false, description: 'Scan, passive marking, approval, physical deletion, and provider evidence' },
            },
        },
        mediaReference: {
            super: 'base',
            model: true,
            service: { enabled: true },
            event: { enabled: true, type: 'SYNC' },
            router: { enabled: true },
            definition: {
                code: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Unique media reference code',
                },
                ownerModule: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Module that owns the business object referencing this media',
                },
                ownerSchema: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Schema that owns the business object referencing this media',
                },
                ownerCode: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Business object code that references media',
                },
                mediaCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Referenced media item code',
                },
                mediaSetCode: {
                    type: 'string',
                    required: false,
                    searchOptions: { enabled: true },
                    description: 'Referenced media set code',
                },
                relationType: {
                    type: 'string',
                    required: true,
                    searchOptions: { enabled: true },
                    description: 'Business relationship type such as PRIMARY_IMAGE, GALLERY, DOCUMENT, IMPORT_SOURCE, or CMS_ASSET',
                },
                position: {
                    type: 'int',
                    required: false,
                    description: 'Display or processing order',
                },
                status: {
                    enum: ['ACTIVE', 'INACTIVE', 'RETIRED'],
                    required: true,
                    default: 'ACTIVE',
                    description: 'Reference lifecycle status',
                },
                evidence: {
                    type: 'object',
                    required: false,
                    description: 'Media-owned approval, activation, rollback, and target-usage evidence for governed references',
                },
            },
        },
    },
};
