/*
    Nodics - Enterprice Micro-Services Management Framework

    Copyright (c) 2026 Nodics All rights reserved.

    This software is governed by the Nodics Source-Available Commercial License.
    You may use, copy, modify, deploy, or distribute it only as permitted by the
    root LICENSE file or a separate written agreement with Nodics.

 */
/** @module customerFeedback/src/service/defaultCustomerFeedbackApiService @description Implements bounded public, customer, and operator feedback use cases. @layer service @owner customerFeedback @override Later modules may extend actions through secured engagementApi contracts. */
module.exports = {
    /** Verifies explicit project activation. */ assertEnabled: function () { let engagement = CONFIG.get('engagement') || {}; if (!(engagement.capabilities && engagement.capabilities.customerFeedback === true)) throw SERVICE.DefaultCustomerFeedbackGovernanceService.error('ERR_FEEDBACK_00008', 'customer feedback is disabled'); },
    /** Resolves the authenticated principal when available. */ principal: function (request) { let auth = request.authData || {}; return request.principalId || auth.principalId || auth.code || auth.loginId; },
    /** Accepts one validated anonymous or identified submission. */ submit: function (request) { this.assertEnabled(); let policy = (CONFIG.get('customerFeedback') || {}).intake || {}; let principal = this.principal(request); let input = Object.assign({}, request.payload, { tenant: request.tenant, ownerId: principal, anonymous: request.payload.anonymous === true || !principal, correlationId: request.correlationId || request.requestId }); let value = SERVICE.DefaultCustomerFeedbackGovernanceService.validate(input, policy); return SERVICE.DefaultCustomerFeedbackRepositoryService.save('customerFeedback', request.tenant, value, principal ? request.authData : undefined); },
    /** Lists feedback owned by the customer. */ listOwn: function (request) { this.assertEnabled(); return SERVICE.DefaultCustomerFeedbackRepositoryService.list('customerFeedback', request.tenant, { ownerId: this.principal(request) }, request.authData, request.query && request.query.limit); },
    /** Lists operator-scoped feedback. */ list: function (request) { this.assertEnabled(); return SERVICE.DefaultCustomerFeedbackRepositoryService.list('customerFeedback', request.tenant, request.query, request.authData, request.query && request.query.limit); },
    /** Executes one governed lifecycle action. */ act: async function (request) { this.assertEnabled(); let repository = SERVICE.DefaultCustomerFeedbackRepositoryService; let current = await repository.get('customerFeedback', request.tenant, request.feedbackCode, request.authData); if (!current) throw SERVICE.DefaultCustomerFeedbackGovernanceService.error('ERR_FEEDBACK_00001', 'feedback not found'); let value = SERVICE.DefaultCustomerFeedbackLifecycleService.transition(current, Object.assign({}, request.payload, { action: request.actionCode, actorId: this.principal(request) }), CONFIG.get('customerFeedback') || {}); return repository.save('customerFeedback', request.tenant, value, request.authData); },
    /** Records a manual or advisory classification with correction evidence. */ classify: async function (request) { this.assertEnabled(); let repository = SERVICE.DefaultCustomerFeedbackRepositoryService; let feedback = await repository.get('customerFeedback', request.tenant, request.feedbackCode, request.authData); if (!feedback) throw SERVICE.DefaultCustomerFeedbackGovernanceService.error('ERR_FEEDBACK_00001', 'feedback not found'); let value = Object.assign({}, request.payload, { tenant: request.tenant, feedbackCode: feedback.code, source: request.payload.source || 'OPERATOR', confidence: Number(request.payload.confidence || 1), policyVersion: request.payload.policyVersion || '1', correctedBy: this.principal(request), classifiedAt: new Date(), correlationId: feedback.correlationId }); return repository.save('customerFeedbackClassification', request.tenant, value, request.authData); },
    /** Creates one source-traceable advisory insight for operator review. */ deriveInsight: async function (request) { this.assertEnabled(); let repository = SERVICE.DefaultCustomerFeedbackRepositoryService; let values = await Promise.all((request.payload.feedbackCodes || []).map(code => repository.get('customerFeedback', request.tenant, code, request.authData))); let sources = values.filter(Boolean); let insight = SERVICE.DefaultCustomerFeedbackInsightService.derive(sources, Object.assign({}, request.payload, { tenant: request.tenant, correlationId: request.correlationId || request.requestId }), (CONFIG.get('customerFeedback') || {}).insight); return repository.save('customerFeedbackInsight', request.tenant, insight, request.authData); }
};
